### PR TITLE
Fix process local read write client side logics and add unit tests

### LINKED ISSUE #13766: Worker Fuse should support internal read when cache miss
**Alluxio Version:**
Master Alluxio 2.6

**Describe the bug**
When a block is cached in the local Alluxio worker and fuse is launched in the worker process, fuse read can go through worker internal read mechanism without grpc.
However, when the block is not cached in any of the Alluxio workers, even when we assign the local worker to be the worker to read from UFS and do the cache job, we still go through external gRPC call to connect to the local worker.

**To Reproduce**
launch a worker with internal fuse.
Prepare a file in UFS and is not cached in Alluxio.
Read the file through fuse mount point.
View worker metrics, will find BytesReadDirect = 0

**Expected behavior**
All read communication between the worker and the embedded fuse should go through internal method call without gRPC involved. No matter the block is in worker storage or in UFS.

**Urgency**
Urgent

**Additional context**

### PR DESCRIPTION
**Pull request by LuQQiu**
Fixes #13766 
### What changes are proposed in this pull request?
Support fuse read from worker through internal method call when cache miss.
Add worker is local check to correct fuse write to process local worker logics.
Add process local read write related metrics

### Why are the changes needed?
When cache miss, the local worker can still help fetch the data from UFS and provide to the internal client without RPC involved.
Remove the unneeded RPC overhead between Fuse and Worker.
Correct the fuse write to local worker logics

### Does this PR introduce any user facing changes?
No

### CODE REVIEW

**Comment by LuQQiu** [comment]
Will have a followup PR about how to correctly record the BytesReadUfs metrics.

**Comment by apc999** [comment]
can you add UT or integration tests on this?

File: core/client/fs/src/main/java/alluxio/client/block/stream/DataWriter.java [hunk 1]
```diff
@@ -62,12 +62,15 @@ public static DataWriter create(FileSystemContext context, long blockId, long bl
...
-      if (context.hasProcessLocalWorker() && !ufsFallbackEnabled) {
+      if (workerIsLocal && context.hasProcessLocalWorker() && !ufsFallbackEnabled) {
+        LOG.debug("Creating worker process local output stream for block {} @ {}",
+            blockId, address);
         return BlockWorkerDataWriter.create(context, blockId, blockSize, options);
       }
 
-      if (CommonUtils.isLocalHost(address, alluxioConf)
+      if (workerIsLocal
           && shortCircuit
```
Comment (apc999) [inline core/client/fs/src/main/java/alluxio/client/block/stream/DataWriter.java:74]: wiered format

File: core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java [hunk 2]
```diff
@@ -204,7 +204,13 @@ public BlockInStream getInStream(BlockInfo info, InStreamOptions options,
               .setLocations(locations))
           .setBlockWorkerInfos(blockWorkerInfo);
       dataSource = policy.getWorker(getWorkerOptions);
+      // TODO(lu) update the bytesReadUfs metrics
+      if (dataSource != null && mContext.hasProcessLocalWorker()
+          && dataSource.equals(mContext.getNodeLocalWorker())) {
```
Comment (ggezer) [inline core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java:209]: I'm not sure if this is right. Why do we consider node-local worker as process-local? Would this cause an issue somewhere when during process-local communication?

Comment (apc999) [reply core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java:208]: `mContext.hasProcessLocalWorker() == true` assures the client is running together with a worker.
In this case, there is no need to go RPC to communicate with this worker

File: core/client/fs/src/main/java/alluxio/client/block/stream/DataWriter.java [hunk 3]
```diff
@@ -62,13 +62,15 @@ public static DataWriter create(FileSystemContext context, long blockId, long bl
           alluxioConf.getBoolean(PropertyKey.USER_SHORT_CIRCUIT_PREFERRED);
       boolean ufsFallbackEnabled = options.getWriteType() == WriteType.ASYNC_THROUGH
           && alluxioConf.getBoolean(PropertyKey.USER_FILE_UFS_TIER_ENABLED);
+      boolean workerIsLocal = CommonUtils.isLocalHost(address, alluxioConf);
 
-      if (context.hasProcessLocalWorker() && !ufsFallbackEnabled) {
+      if (workerIsLocal && context.hasProcessLocalWorker() && !ufsFallbackEnabled) {
+        LOG.debug("Creating worker process local output stream for block {} @ {}",
+            blockId, address);
```
Comment (jiacheliu3) [inline core/client/fs/src/main/java/alluxio/client/block/stream/DataWriter.java:69]: Thanks a lot for the extra logs!

File: core/client/fs/src/main/java/alluxio/client/block/stream/DataReader.java [hunk 4]
```diff
@@ -21,6 +21,17 @@
...
 
+  /**
+   * The data reader type.
+   */
+  enum DataReaderType {
+    BLOCK_WORKER,
+    GRPC,
+    SHORT_CIRCUIT,
+    SHARED,
+    TEST
```
Comment (jiacheliu3) [inline core/client/fs/src/main/java/alluxio/client/block/stream/DataReader.java:32]: Comment to explain each one of them?

File: core/client/fs/src/main/java/alluxio/client/block/stream/DataWriter.java [hunk 5]
```diff
@@ -62,13 +62,15 @@ public static DataWriter create(FileSystemContext context, long blockId, long bl
...
         return BlockWorkerDataWriter.create(context, blockId, blockSize, options);
       }
 
-      if (CommonUtils.isLocalHost(address, alluxioConf)
-          && shortCircuit
+      if (workerIsLocal && shortCircuit
```
Comment (jiacheliu3) [inline core/client/fs/src/main/java/alluxio/client/block/stream/DataWriter.java:73]: Other than the logs when the if conditions are all met, I think it is also very important to know which condition is NOT met. In other words, we may expect the if condition to be true but when it is not true, there should be some hints how it is not true. I'd recommend this:
```
if (conditionA && conditionB && conditionC) {
  LOG.debug(...)
  // do sth
  // Actually if you can return here, just return explicitly to avoid confusing
}
LOG.debug("a message that contains conditionA={} conditionB={} conditionC={}")
...
```
This is not logging more than you are already doing right now, because we are logging one line when the IF block executes, we should also accept logging one message for the implicit ELSE block.

File: core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java (hunk 2 above)
Comment (jiacheliu3) [reply core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java:208]: What I get from this conversation is that people don't understand what is `PROCESS_LOCAL`, when should it happen and what does that imply. Those information should either be commented here (when `PROCESS_LOCAL` value is given) or in the enum definition (comment after each field).

**Review by jiacheliu3 — CHANGES_REQUESTED** [review]
@LuQQiu Thanks! Added some comment requesting for more comments. Requesting these just because last week I had to read this part of the code when debugging and it took me quite a while to understand the intention. The if condition is a combination of many conditions (which each comes from yet a few other conditions). It is hard to reverse-guess what each scenario means and hard to debug. Those are gaps I hope we can close by comments and logging (as you are doing right now).

File: core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java (hunk 2 above)
Comment (LuQQiu) [reply core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java:208]: The definition is in the enum comments

**Comment by LuQQiu** [comment]
@apc999 @jiacheliu3 Addressed the comments, PTAL, thanks!

File: core/client/fs/src/main/java/alluxio/client/block/stream/DataReader.java [hunk 6]
```diff
@@ -22,14 +22,21 @@
 public interface DataReader extends Closeable {
 
   /**
-   * The data reader type.
+   * The data reader type represents different ways to read data.
    */
   enum DataReaderType {
-    BLOCK_WORKER,
-    GRPC,
+    BLOCK_WORKER, // Read from a worker in the same process
```
Comment (jiacheliu3) [inline core/client/fs/src/main/java/alluxio/client/block/stream/DataReader.java:28]: nit: If this only applies to FUSE, maybe mention this in the comment? People may not understand when you have a worker in the same process.

File: core/client/fs/src/main/java/alluxio/client/block/stream/DataReader.java [hunk 7]
```diff
@@ -22,14 +22,21 @@
 public interface DataReader extends Closeable {
 
   /**
-   * The data reader type.
+   * The data reader type represents different ways to read data.
    */
   enum DataReaderType {
```
Comment (jiacheliu3) [inline core/client/fs/src/main/java/alluxio/client/block/stream/DataReader.java:27]: Which one applies for domain socket? If domain socket and short circuit both use `SHORT_CIRCUIT` maybe we split them or rename?

**Review by jiacheliu3 — APPROVED** [review]
Thanks for the improvements! LGTM with some minor comments.

File: core/client/fs/src/main/java/alluxio/client/block/stream/DataReader.java (hunk 7 above)
Comment (LuQQiu) [reply core/client/fs/src/main/java/alluxio/client/block/stream/DataReader.java:27]: Domain socket using GrpcDataReader. I don't feel I have enough knowledge to do domain socket related changes. The reader type here refects the data reader names/classes that are using.

**Comment by LuQQiu** [comment]
@apc999 @jiacheliu3  please take a look, thanks!

File: core/client/fs/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java [hunk 8]
```diff
@@ -284,28 +289,49 @@ public Object answer(InvocationOnMock invocation) {
...
+        Lists.newArrayList(new BlockWorkerInfo(remote, 100, 0),
+            new BlockWorkerInfo(local, 100, 0)));
 
-    // Location policy chooses worker1 first.
-    assertEquals(worker1, mBlockStore.getInStream(BLOCK_ID, options).getAddress());
-    // Location policy chooses worker2 second.
-    assertEquals(worker2, mBlockStore.getInStream(BLOCK_ID, options).getAddress());
+    BlockInStream stream = mBlockStore.getInStream(BLOCK_ID, options);
+    assertEquals(local, stream.getAddress());
+    assertEquals(DataReader.DataReaderType.GRPC, stream.getDataReaderType());
```
Comment (apc999) [inline core/client/fs/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java:334]: I feel it is fine to directly assert on `stream.getDataReader()`

**Review by apc999 — CHANGES_REQUESTED** [review]

File: core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java [hunk 9]
```diff
@@ -430,7 +430,8 @@ private void triggerAsyncCaching(BlockInStream stream) {
 
   private void handleRetryableException(BlockInStream stream, IOException e) {
     WorkerNetAddress workerAddress = stream.getAddress();
-    LOG.warn("Failed to read block {} of file {} from worker {}, will retry: {}",
+    LOG.warn("Failed to read block {} of file {} from worker {}. "
+        + "This worker will be skipped for future read operations, will retry: {}.",
         stream.getId(), mStatus.getPath(), workerAddress, e.getMessage());
```
[the remark this answers is not in the document]
Comment (LuQQiu) [reply core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java:435]: Good call. The related comparison between e.toString() & e.getMessage() https://stackoverflow.com/questions/28272473/java-logging-exceptions-use-getmessage-or-tostring-log-warnex-getmessage FYI @ssz1997

File: core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java [hunk 10]
```diff
@@ -458,8 +462,8 @@ public void close() throws IOException {
   /**
    * @return whether the reader is reading data directly from a local file
    */
-  public boolean isShortCircuit() {
-    return mDataReaderFactory.isShortCircuit();
+  public DataReader.DataReaderType getDataReaderType() {
```
[the remark this answers is not in the document]
Comment (LuQQiu) [reply core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java]: Yeah, get class way is better! Changed to getClass, PTAL!

**Comment by LuQQiu** [comment]
@apc999 PTAL, thanks!

**Review by apc999 — APPROVED** [review]

**Comment by apc999** [comment]
alluxio-bot, merge this please
