### PR TITLE
Get service version out of retryRpc loop

### LINKED ISSUE #11228: Abstract Client infinite loop
**Alluxio Version:**
master

**Describe the bug**
In a condition where a channel creation succeeds but getRemoteServiceVersion() always fails;

`retryRpcInternal` will call `disconnect` after the RPC fails, then `connect` again on the next attempt.  `connect` will call `getRemoteServiceVersion()` again in the call chain because disconnect was called.

### PR DESCRIPTION
**Pull request by ggezer**
`getServiceVersion()` is a simple unauthenticated code, that is called after a successful connection.
Calling it with `retryRpc` utility opens a way for some allowed exceptions to fuel an infinite loop.

Fixes #11228

### CODE REVIEW

**Comment by ggezer** [comment]
jenkins, test this please

File: core/common/src/main/java/alluxio/AbstractClient.java [hunk 1]
```diff
@@ -123,11 +123,10 @@ public AbstractClient(ClientContext context, InetSocketAddress address,
   protected abstract ServiceType getRemoteServiceType();
 
   protected long getRemoteServiceVersion() throws AlluxioStatusException {
-    return retryRPC(() ->
```
Comment (gpang) [inline core/common/src/main/java/alluxio/AbstractClient.java:126]: Are you saying there is a retry of `getRemoteServiceVersion` outside of this, so we don't need to use `retryRPC`? I don't understand where the infinite loop is happening.

Comment (ggezer) [reply core/common/src/main/java/alluxio/AbstractClient.java:126]: When a channel creation succeeds but `getRemoteServiceVersion()` fails always.
In that case, `retryRpcInternal` will call disconnect after the rpc, then connect again. After disconnect, connect will call `getRemoteServiceVersion()` again.

Comment (ggezer) [reply core/common/src/main/java/alluxio/AbstractClient.java:126]: This will create connect -> getRemoteServiceVersion -> connect -> getRemoteServiceVersion loop. `connect` after `getRemoveServiceVersion` being the second attempts.

Comment (gpang) [reply core/common/src/main/java/alluxio/AbstractClient.java:126]: I see. Then, could you add a comment here saying we don't need to retry here, since the the entire connection/channel will be retried outside?

**Comment by ggezer** [comment]
alluxio-bot, merge this please

**Comment by ggezer** [comment]
alluxio-bot, cherry-pick this to branch-2.2 please
