### PR TITLE
Check for more results when the filtered result is empty

### LINKED ISSUE #18043: fs load succeeded but no file processed
**Alluxio Version:**
2.9.3

**Describe the bug**

for the preheated alluxio cluster, when the worker is restarted due to oom, use `fs loadmeta` and  `fs load --verify` to warm up again;

```
./bin/alluxio fs load / --submit --partial-listing --verify
./bin/alluxio fs load / --progress
Progress for loading path '/':
	Settings:	bandwidth: unlimited	verify: true
	Job State: SUCCEEDED
	Files Processed: 0
	Bytes Loaded: 0B
	Throughput: 0B/s
	Block load failure rate: 0.00%
	Files Failed: 0
```
But using `fs ls` can still find that there are no cached files. and alluxio cluster has enough capacity:

```
./bin/alluxio fs ls /write_newtrain_facepoints_temp.py
           1507       PERSISTED 07-26-2023 12:54:49:659   0% /write_newtrain_facepoints_temp.py


fsadmin report
Total Capacity: 3120.00GB
        Tier: SSD  Size: 3120.00GB
    Used Capacity: 777.11GB
        Tier: SSD  Size: 777.11GB
    Free Capacity: 2342.89GB
```

master, worker no err log, try warming up a specific file instead of /

```
./bin/alluxio fs ls /write_newtrain_facepoints_temp.py
           1507       PERSISTED 07-26-2023 12:54:49:659   0% /write_newtrain_facepoints_temp.py


./bin/alluxio fs load /write_newtrain_facepoints_temp.py --submit --partial-listing --verify
Load '/write_newtrain_facepoints_temp.py' is successfully submitted. JobId: c2facde4-d3f4-4f1d-be0a-4a26aa9ca78e


./bin/alluxio fs load /write_newtrain_facepoints_temp.py --progress
Progress for loading path '/write_newtrain_facepoints_temp.py':
	Settings:	bandwidth: unlimited	verify: true
	Job State: FAILED (alluxio.exception.runtime.InternalRuntimeException: Job failed because it's not healthy.)
	Files Processed: 2052
	Bytes Loaded: 7.36KB
	Block load failure rate: 99.76%
	Files Failed: 1


./bin/alluxio fs ls /write_newtrain_facepoints_temp.py
           1507       PERSISTED 07-26-2023 12:54:49:659 100% /write_newtrain_facepoints_temp.py
```

worker no err log, master err log:

```
2023-08-17 06:18:36,790 WARN  [master-rpc-executor-TPE-thread-297](DefaultBlockMaster.java:1133) - Rejecting attempt to change block length from 1507 to 0
2023-08-17 06:18:36,792 WARN  [master-rpc-executor-TPE-thread-333](DefaultBlockMaster.java:1133) - Rejecting attempt to change block length from 1507 to 0
2023-08-17 06:18:36,796 WARN  [master-rpc-executor-TPE-thread-402](DefaultBlockMaster.java:1133) - Rejecting attempt to change block length from 1507 to 0
2023-08-17 06:18:36,798 WARN  [master-rpc-executor-TPE-thread-405](DefaultBlockMaster.java:1133) - Rejecting attempt to change block length from 1507 to 0
```

**Additional context**

### PR DESCRIPTION
**Pull request by Haoning-Sun**
### What changes are proposed in this pull request?

Check for more results when the filtered result is null when loading data.

### Why are the changes needed?
Fix #18043.

### CODE REVIEW

**Comment by yyongycy** [comment]
@jja725  could you please help review this one?

File: core/server/master/src/main/java/alluxio/master/job/FileIterable.java [hunk 1]
```diff
@@ -151,28 +152,37 @@ private void partialListFileInfos() {
...
+      Supplier<ListStatusContext> context = () -> {
+        return ListStatusContext.create(ListStatusPartialPOptions
+            .newBuilder()
+            .setOptions(mListOptions)
+            .setBatchSize(PARTIAL_LISTING_BATCH_SIZE)
+            .setStartAfter(mStartAfter));
+      };
+
+      List<FileInfo> fileInfos;
+      while ((fileInfos = listStatus(context.get())) != null
```
Comment (jja725) [inline core/server/master/src/main/java/alluxio/master/job/FileIterable.java:164]: in which situation this would be null? doesn't seems like we would get null

**Review by jja725 — COMMENTED** [review]
mostly lgtm, thanks for the fix

File: core/server/master/src/main/java/alluxio/master/job/FileIterable.java (hunk 1 above)
Comment (Haoning-Sun) [reply core/server/master/src/main/java/alluxio/master/job/FileIterable.java:164]: Condition ` !fileInfos.isEmpty()` should be judged after condition `(mFiles = fileInfos.stream().filter(mFilter).collect(Collectors.toList())).isEmpty()`, otherwise `mFiles` may not be updated. I added a judgment of whether or not it is null to update fileInfos first.

**Review by jja725 — COMMENTED** [review]
The fix LGTM, Do you mind adding a unit test for this?

**Comment by Haoning-Sun** [comment]
> The fix LGTM, Do you mind adding a unit test for this?

Done.

**Review by jja725 — APPROVED** [review]
Thanks for the fix

**Comment by jja725** [comment]
alluxio-bot, merge this please

**Comment by jja725** [comment]
alluxio-bot, merge this please

**Comment by jiacheliu3** [comment]
i understand this fix is not needed in `main` because the issue is more about metadata on the Master? @jja725 WDYT?

**Comment by jja725** [comment]
> i understand this fix is not needed in `main` because the issue is more about metadata on the Master? @jja725 WDYT?

Yes you are correct
