### PR TITLE
Fix throw CCE when using Fuse while enable client cache bug

### LINKED ISSUE #13442: Throw CCE when using Fuse while enable client cache
**Alluxio Version:**
Alluxio master branch, HEAD

**Describe the bug**

image

```
java.lang.ClassCastException: alluxio.client.file.cache.LocalCacheFileInStream cannot be cast to alluxio.client.file.AlluxioFileInStream
        at alluxio.fuse.AlluxioJniFuseFileSystem.readInternal(AlluxioJniFuseFileSystem.java:429)
        at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$read$17(AlluxioJniFuseFileSystem.java:404)
        at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:280)
        at alluxio.fuse.AlluxioJniFuseFileSystem.read(AlluxioJniFuseFileSystem.java:404)
        at alluxio.jnifuse.AbstractFuseFileSystem.readCallback(AbstractFuseFileSystem.java:180)
```

**To Reproduce**

Enable client cache in `alluxio-site.properties`

```
alluxio.user.client.cache.enabled=true
```

And then start Alluxio-fuse, read a file

**Expected behavior**

get the content of the file.

**Urgency**

Urgent, block to use Alluxio Local Cache.

**Additional context**
No.

### PR DESCRIPTION
**Pull request by bzheng888**
Fix #13442

### CODE REVIEW

File: core/client/fs/src/main/java/alluxio/client/file/FileInStream.java [hunk 1]
```diff
@@ -24,4 +26,31 @@
...
+     * Reads up to len bytes of data from the input stream into the byte buffer.
+     *
+     * @param byteBuffer the buffer into which the data is read
+     * @param off the start offset in the buffer at which the data is written
+     * @param len the maximum number of bytes to read
+     * @return the total number of bytes read into the buffer, or -1 if there is no more data because
+     *         the end of the stream has been reached
+     */
+    public int read(ByteBuffer byteBuffer, int off, int len) throws IOException {
+        int nread = 0;
```
Comment (maobaolong) [inline core/client/fs/src/main/java/alluxio/client/file/FileInStream.java:39]: Please fix the wrap line ident from 4 to 2.

File: core/client/fs/src/main/java/alluxio/client/file/FileInStream.java [hunk 2]
```diff
@@ -24,4 +26,31 @@
  */
 public abstract class FileInStream extends InputStream implements BoundedStream, PositionedReadable,
     Seekable {
+    /**
+     * Reads up to len bytes of data from the input stream into the byte buffer.
+     *
+     * @param byteBuffer the buffer into which the data is read
+     * @param off the start offset in the buffer at which the data is written
+     * @param len the maximum number of bytes to read
+     * @return the total number of bytes read into the buffer, or -1 if there is no more data because
```
Comment (maobaolong) [inline core/client/fs/src/main/java/alluxio/client/file/FileInStream.java:35]: keep line length less than 100 chars.

File: core/client/fs/src/main/java/alluxio/client/file/FileInStream.java [hunk 3]
```diff
@@ -24,4 +26,31 @@
...
+     *         the end of the stream has been reached
+     */
+    public int read(ByteBuffer byteBuffer, int off, int len) throws IOException {
+        int nread = 0;
+        int rd = 0;
+        final int sz = len;
+        final byte[] dest = new byte[sz];
+        while (rd >= 0 && nread < sz) {
```
Comment (maobaolong) [inline core/client/fs/src/main/java/alluxio/client/file/FileInStream.java:43]: Is this while loop necessary? @LuQQiu @apc999 , this code fragment is copied from `AlluxioFuseFileSystem#copyInternal`.

File: integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java [hunk 4]
```diff
@@ -402,7 +402,7 @@ private int readInternal(String path, ByteBuffer buf, long size, long offset, Fu
         if (offset - is.getPos() < is.remaining()) {
           is.seek(offset);
           while (rd >= 0 && nread < sz) {
```
Comment (maobaolong) [inline integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java:404]: The same question, is this while loop necessary? @LuQQiu @apc999

**Review by maobaolong — CHANGES_REQUESTED** [review]
Thank you for fix this `CCE` and let the `Local Cache` can be used in Alluxio-Fuse.
Please fix the style issue and pass all of the ci checks.

**Comment by apc999** [comment]
@bzheng888  can you add some more info into the PR description, so we know the context of this fix?

File: integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java (hunk 4 above)
Comment (maobaolong) [reply integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java:404]: After an offline discussion with @LuQQiu , I knew the the reason is that we want keep read a specific size of input stream or touch the EOF, when the actual read length is smaller that the specific length, using while-read mode can continue to read the inputstream.

**Comment by bzheng888** [comment]
@apc999 Sorry, I forgot to mention the issue, this pr is to Fix #13442.

**Review by maobaolong — APPROVED** [review]
It LGTM, @apc999 Would you please take another look, this blocker make `LocalCache` cannot be used in Alluxio Fuse.

**Review by apc999 — APPROVED** [review]

**Comment by apc999** [comment]
alluxio-bot, merge this please

File: core/client/fs/src/main/java/alluxio/client/file/FileInStream.java [hunk 5]
```diff
@@ -24,4 +26,31 @@
...
+    final int sz = len;
+    final byte[] dest = new byte[sz];
+    while (rd >= 0 && nread < sz) {
+      rd = read(dest, nread, sz - nread);
+      if (rd >= 0) {
+        nread += rd;
+      }
+    }
+    if (nread == -1) { // EOF
+      nread = 0;
```
Comment (dbw9580) [inline core/client/fs/src/main/java/alluxio/client/file/FileInStream.java:50]: These lines don't look right: `nread` is only updated by adding `rd`, where `rd` is non-negative. `nread` is 0 at the beginning. Therefore `nread` is non-negative. Why do we check if it is -1?

Comment (bzheng888) [reply core/client/fs/src/main/java/alluxio/client/file/FileInStream.java:50]: @dbw9580 Good catch! This code is obtained from AlluxioFuseFileSystem.java->readInternal, so it seems both of them have similar problems, can you fix this?

Comment (dbw9580) [reply core/client/fs/src/main/java/alluxio/client/file/FileInStream.java:50]: This line was added in this commit https://github.com/Alluxio/alluxio/commit/0d30732ba71674357d9d30c3c34fa701efaacfda so it's almost been here since like genesis. 🤦

Comment (bzheng888) [reply core/client/fs/src/main/java/alluxio/client/file/FileInStream.java:50]: And this is indeed an obvious mistake!
