### PR TITLE
[#8419] Utilize configuration when populating gRPC options objects

### LINKED ISSUE #8417: SetAttributePOptions contains setTtl and setTtlAction
**Alluxio Version:** 2.0.0-SNAPSHOT

**Describe the bug**

The gRPC-generated options SetAttributePOptions contains numerous fields. Two of them being `Ttl` and `TtlAction`. The issue with having these two fields specified is that they also exist within the `CommonOptions`. This allows us to set the TTL in two separate places. This means if the client doesn't set the proper options in both places it's possible the master will pick the wrong option to read from when it receives the request. The TTL options should only be set in one place.

**To Reproduce**
N/A

**Expected behavior**
There should only be one set of TTL options that can be set in `SetAttributePOptions`

**Additional context**

### LINKED ISSUE #8419: grpc POptions getDefaultInstance doesn't get the proper defaults
**Alluxio Version:** 2.0

**Describe the bug**
gRPC code to get the correct defaults on filesystem operations ignores client side properties that are set in alluxio-site.properties or as options in the CLI

**To Reproduce**
Create a local test file and run 'bin/alluxio fs copyFromLocal test.txt /path/to/directory -Dalluxio.user.file.writetype.default=CACHE_THROUGH'. The resulting file in Alluxio will be in state NOT_PERSISTED but the file itself will have been written correctly to the UFS.

**Expected behavior**
The file should be in state PERSISTED and fully loaded to memory.

**Additional context**
The proposed fix is to add a util class that will set the correct options/flags based on the client context. Please correct this explanation as required @ZacBlanco and @calvinjia.

### PR DESCRIPTION
**Pull request by ZacBlanco**
I've also removed the ttl and ttlAction fields from the setAttributes option as it is already included in the common options (#8417). Proto files have been regenerated.

Methods which need options passed on the client side should now utilize the `FileSystemOptions` class to generate the proper options based off of a configuration object. This will respect users' configuration on the client side. Otherwise options created with getDefaultInstance() don't respect a user's configuration with write type, ttl, etc.

Previously before this change the master would merge options with the client based on the configuration once an RPC is received. The new behavior populate all options on the client side, with any user-specified defaults overriding the configuration. All of the OperationContexts on the master side have had their constructors updated so that each now has a `defaults()` `create` and `mergeFrom`. `create` is to be used when accepting options from client requests `mergeFrom` and `defaults` should be used when a new context is needed on the master which doesn't come from the client options.

Fixes #8417 
Fixes #8419

### CODE REVIEW

File: core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java [hunk 1]
```diff
@@ -3585,14 +3585,17 @@ private void setAttributeSingleFile(RpcContext rpcContext, LockedInodePath inode
...
       mInodeTree.setReplication(rpcContext, inodePath, replicationMax, replicationMin, opTimeMs);
     }
-    if (protoOptions.hasTtl()) {
-      long ttl = protoOptions.getTtl();
-      if (inode.getTtl() != ttl || inode.getTtlAction() != protoOptions.getTtlAction()) {
+    if (protoOptions.hasCommonOptions() && protoOptions.getCommonOptions().hasTtl()
+        && protoOptions.getCommonOptions().hasTtlAction()) {
+      long ttl = protoOptions.getCommonOptions().getTtl();
+      if (inode.getTtl() != ttl
+          || inode.getTtlAction() != protoOptions.getCommonOptions().getTtlAction()) {
```
Comment (calvinjia) [inline core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java]: Can these conditions be cleaned up, it seems like we check `inode.getTtl()` twice, if `entry.setTtl` is idempotent, we could just set it regardless of whether or not it has changed (since the main thing is whether or not to update last mod time).

File: core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java [hunk 2]
```diff
@@ -0,0 +1,248 @@
...
+
+  /**
+   * @param conf Alluxio configuration
+   * @return options based on the configuration
+   */
+  public static CreateDirectoryPOptions getCreateDirectoryPOptions(AlluxioConfiguration conf) {
+    return CreateDirectoryPOptions.newBuilder()
+        .setCommonOptions(getFileSystemMasterCommonPOptions(conf))
+        .setWriteType(conf.getEnum(PropertyKey.USER_FILE_WRITE_TYPE_DEFAULT, WritePType.class))
+        // No default configuration values, will pull from gRPC defaultInstance
```
[the remark this answers is not in the document]
Comment (ZacBlanco) [reply core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java]: I think it would be better to control non-configuration defaults from within the proto file rather than from these functions. Users don't necessarily have to go through this class to create these options and enforcing defaults from the proto definitions are a sure way to make sure that we always get the same defaults. Thoughts?

[the remark this answers is not in the document]
Comment (calvinjia) [reply core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java]: We should make `getDefaultInstance` unavailable to end users. I think its better to control the defaults in one place rather than have some default in code and others in the proto definition. Also the proto def can be less flexible since it cannot be updated without recompilation.

[the remark this answers is not in the document]
Comment (ZacBlanco) [reply core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java]: The issue I believe is that `getDefaultInstance()` isn't a function that we control. It's generated by protobuf. Obviously we could go in and manually change it to private but that means any time the file is regenerated we'd need to make that change. As far as I'm aware after glancing over the docs we can't control the availability of the `getDefaultInstance` function.

File: core/base/src/main/java/alluxio/wire/LoadMetadataType.java [hunk 3]
```diff
@@ -24,15 +24,15 @@
   /**
    * Never loads metadata.
    */
-  Never(0),
+  NEVER(0),
```
Comment (apc999) [inline core/base/src/main/java/alluxio/wire/LoadMetadataType.java]: good catch!

File: core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java [hunk 4]
```diff
@@ -0,0 +1,259 @@
...
+ */
+public class GrpcDefaultOptions {
+
+  /**
+   * @param conf Alluxio configuration
+   * @return options based on the configuration
+   */
+  public static CreateDirectoryPOptions getCreateDirectoryPOptions(AlluxioConfiguration conf) {
+    return CreateDirectoryPOptions.newBuilder()
+        .setCommonOptions(getFileSystemMasterCommonPOptions(conf))
```
Comment (apc999) [inline core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java]: nit: keep these setters in alphabetical order so in the future when adding more fields, there will be unique locations to insert

File: core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java [hunk 5]
```diff
@@ -0,0 +1,259 @@
...
+import alluxio.grpc.SetAttributePOptions;
+import alluxio.grpc.TtlAction;
+import alluxio.grpc.UnmountPOptions;
+import alluxio.grpc.WritePType;
+
+/**
+ * This class contains static methods which can be passed Alluxio configuration objects that
+ * will populate the gRPC options objects with the proper values based on the given configuration.
+ */
+public class GrpcDefaultOptions {
```
Comment (apc999) [inline core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java]: should this become a util class then with private constructors since it has no instance members.

Comment (ZacBlanco) [reply core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java]: good catch

**Comment by gpang** [comment]
@ZacBlanco is `Fixes 8415` the correct number? 8415 seems to point to another PR.

**Comment by ZacBlanco** [comment]
God catch! It's supposed to be #8417

File: core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (calvinjia) [reply core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java]: We don't want to modify the autogenerated code. One soft method is to make `GrpcDefaultOptions` the public facing API. Users should only use the utils class when they need to get a default option, and if they decide to use the proto object directly they are on their own.

File: core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java (hunk 1 above)
Comment (ZacBlanco) [reply core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java]: While minor, the tradeoff is whether or not checking `inode.getTtl` twice is worth the tradeoff of setting the field on the entry. It looks like under the covers the entry does some other iother internal actions when you set a field. I don't know what the overhead is like, but doing that boolean comparison could possibly save some operations rather than setting it every time. An alternative so we don't do the comparison twice could be 

```
      long ttl = protoOptions.getCommonOptions().getTtl();
      boolean changedTtl = inode.getTtl() != ttl;
      if (changedTtl
          || inode.getTtlAction() != protoOptions.getCommonOptions().getTtlAction()) {
        if (changedTtl) {
          entry.setTtl(ttl);
        }
        entry.setLastModificationTimeMs(opTimeMs);
        entry.setTtlAction(ProtobufUtils.toProtobuf(
            protoOptions.getCommonOptions().getTtlAction()));
      }
```

File: core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (ZacBlanco) [reply core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java]: Sorry I don't quite understand your suggestion. Are you saying that the client methods should take a different type instead (some kind of wrapper around the options)? or just that users should always use the `GrpcDefaultOptions` class?

File: core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java (hunk 5 above)
Comment (ggezer) [inline core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java]: We have a master counterpart of this class named FileSystemMasterOptions and it's a util class.
For the sake of consistency can we rename it as FileSystemClientOptions? We had this intermediary class before and it was named as such. This logic is not gRPC related so we don't need to name it as such.

**Comment by ZacBlanco** [comment]
Thanks for the comments @ggezer!

The issue surrounding these changes is that the Alluxio client isn't sending requests with the values configured via cluster defaults, site-properties, runtime, etc.. Calling `getDefaultInstance()` on any of the `POptions` classes simply returns the auto-generated gRPC defaults from our proto files. We should make sure that all requests which are sent, unless explicity modified, contain the options which respect a user's Alluxio configuration. Otherwise if the options aren't populated with the proper values we'll be sending requests that may not match what the user is expecting to be sending.

To address 1:

- I modified some tests too because the rationale is that pretty much anywhere in the codebase that uses `getDefaultInstance` should be populating values based on configuration, not based on the gRPC defaults. Thus, I changed tests where `getDefaultInstance` was utilized to make sure clients were sending the proper options. If there's a specific test in question you can point me to it.

To address 2:

- I don't know if I fully understand what you mean by "patching to BaseFileSystem" but I don't see how it would allow us to be more picky about which configuration sources to use. You're correct in that we can query sources of configuration, however I don't think the source of configuration applies in this situation. For example, if a client is sending a request, and the default TTL action is configured as `FREE` but the gRPC POptions default is `DELETE` the client should always override the POption default of `DELETE` regardless of the configuration source, no?

File: core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java (hunk 5 above)
Comment (ZacBlanco) [reply core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java]: I can agree with that. However I don't necessarily see the logic here as client-side only issues. After taking a look at `FileSystemMasterOptions` we have much of the same code. It's just that the class relies on `ServerConfiguration` which is unavailable to the client.

I see this functionality as something that's shared on both on the client and server side. The logic between both classes is effectively the same. Originally I was going to put `GrpcDefaultOptions` in `core-common` but it relied on the `core-transport` dependency which I didn't want to add, so I moved it into the client. If we do want to add that dependency and move the logic to `core-common` then both client and server can rely on the same logic to populate the options objects. The server side will just need to pass `ServerConfiguration.global()` to all of the methods.

File: core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (calvinjia) [reply core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java]: Users should always use the `GrpcDefaultOptions` class.

File: core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java (hunk 1 above)
Comment (calvinjia) [reply core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java]: My suggestion is for improving code readability and not performance. I don't think the cost of either checking the boolean or setting the fields should be significant.

File: core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java (hunk 5 above)
Comment (ggezer) [reply core/client/fs/src/main/java/alluxio/util/GrpcDefaultOptions.java]: My motivation is to restrict this change's impact to client side. Server should have the authority to enforce defaults, and client should only send when it wants to override those defaults.

File: core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java [hunk 6]
```diff
@@ -436,7 +436,7 @@ private static MountInfo getRootMountInfo(MasterUfsManager ufsManager) {
       Map<String, String> rootUfsConf =
           ServerConfiguration.getNestedProperties(PropertyKey.MASTER_MOUNT_TABLE_ROOT_OPTION);
       MountPOptions mountOptions = MountContext
-          .defaults(MountPOptions.newBuilder().setShared(shared).putAllProperties(rootUfsConf))
+          .mergeFrom(MountPOptions.newBuilder().setShared(shared).putAllProperties(rootUfsConf))
```
Comment (calvinjia) [inline core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java]: (Applies in general)
Should the `mergeFrom` be the other way around? This way will override the options from the mount context which should be respected?

Comment (ZacBlanco) [reply core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java]: I'm not sure. Currently this will respect the previous implementation's behavior.

Comment (calvinjia) [reply core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java]: Ah I see, the implemented `mergeFrom` is the opposite of the Protobuf `mergeFrom`. This is slightly confusing, could you leave a TODO to change the method name or have some other way of disambiguating this?

File: core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java [hunk 7]
```diff
@@ -147,13 +148,15 @@ public boolean isClosed() {
   @Override
   public void createDirectory(AlluxioURI path)
       throws FileAlreadyExistsException, InvalidPathException, IOException, AlluxioException {
-    createDirectory(path, CreateDirectoryPOptions.getDefaultInstance());
+    createDirectory(path, FileSystemOptions.createDirectoryDefaults(mFsContext.getConf()));
```
Comment (ggezer) [inline core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java]: You don't need to pass the defaults since the options that you pass from here will be merged once again with the defaults. getDefaultInstance() should be fine in these utility versions.

Comment (ggezer) [reply core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java]: Same for all utility methods (the ones without options) in BaseFileSystem.

File: core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java [hunk 8]
```diff
@@ -232,7 +233,7 @@ public void mount(final AlluxioURI alluxioPath, final AlluxioURI ufsPath,
   @Override
   public void rename(final AlluxioURI src, final AlluxioURI dst)
```
Comment (ggezer) [inline core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java]: Does this one even have any callers? I don't see a reason to have an utility at client level. Could you double check and remove if this method is redundant?

File: core/client/fs/src/main/java/alluxio/util/FileSystemOptions.java [hunk 9]
```diff
@@ -0,0 +1,258 @@
...
+ * This class contains static methods which can be passed Alluxio configuration objects that
+ * will populate the gRPC options objects with the proper values based on the given configuration.
+ */
+public class FileSystemOptions {
+
+  /**
+   * @param conf Alluxio configuration
+   * @return options based on the configuration
+   */
+  public static CreateDirectoryPOptions createDirectoryDefaults(AlluxioConfiguration conf) {
```
Comment (ggezer) [inline core/client/fs/src/main/java/alluxio/util/FileSystemOptions.java]: Did you consider returning builder instead? That will decrease the merging overhead at BaseFileSystem. 
Or it could be both. createDirectoryDefaults() vs createDirectoryDefaultsBuilder(), the former can call the latter.

File: core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java (hunk 6 above)
Comment (ggezer) [reply core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java]: It's actually similar behaviour to protobuf, but I agree that it doesn't communicate on with what it's merging from. If we decide to change the name, all Context.mergeFrom() should be being used from master side, so it should be an easy refactor.

File: core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java (hunk 8 above)
Comment (ZacBlanco) [reply core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java]: Removing would require changing the public-facing API. I don't think removing this is in-scope for the PR.

File: core/server/master/src/main/java/alluxio/master/file/FileSystemMasterOptions.java [hunk 10]
```diff
@@ -12,199 +12,24 @@
...
-            ServerConfiguration.getEnum(PropertyKey.USER_FILE_CREATE_TTL_ACTION, TtlAction.class))
-        .setSyncIntervalMs(ServerConfiguration.getMs(PropertyKey.USER_FILE_METADATA_SYNC_INTERVAL))
-        .build();
-  }
+public final class FileSystemMasterOptions {
 
   /**
    * @return Master side defaults for {@link CompleteFilePOptions}
    */
   public static CompleteFilePOptions completeFileDefaults() {
```
Comment (ggezer) [inline core/server/master/src/main/java/alluxio/master/file/FileSystemMasterOptions.java]: Is this the only method that keeps this file alive? Can't this be moved to FileSystemOptions?

File: core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java (hunk 8 above)
Comment (ggezer) [reply core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java]: This is not public API.

File: core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java (hunk 7 above)
Comment (ZacBlanco) [reply core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java]: Good catch, fixed

File: core/server/master/src/main/java/alluxio/master/file/FileSystemMasterOptions.java (hunk 10 above)
Comment (ZacBlanco) [reply core/server/master/src/main/java/alluxio/master/file/FileSystemMasterOptions.java]: It could be, but I also wanted to separate on the master v. client-side options because there are many options objects but only a few are used on client. Even with one method I felt it warranted enough difference to keep this file

File: core/server/proxy/src/main/java/alluxio/proxy/PathsRestServiceHandler.java [hunk 11]
```diff
@@ -110,7 +111,7 @@ public Response createDirectory(@PathParam("path") final String path,
     return RestUtils.call((RestUtils.RestCallable<Void>) () -> {
       if (options == null) {
         mFileSystem.createDirectory(new AlluxioURI(path),
-                CreateDirectoryPOptions.getDefaultInstance());
+                FileSystemOptions.createDirectoryDefaults(ServerConfiguration.global()));
```
Comment (ggezer) [inline core/server/proxy/src/main/java/alluxio/proxy/PathsRestServiceHandler.java]: This goes to FileSystem. Why do you need to supply the defaults here?

Comment (ggezer) [reply core/server/proxy/src/main/java/alluxio/proxy/PathsRestServiceHandler.java]: Same for all.

File: job/server/src/main/java/alluxio/job/migrate/MigrateDefinition.java [hunk 12]
```diff
@@ -246,7 +246,7 @@ private static String computeTargetPath(String path, String source, String desti
   private void migrateDirectory(String path, String source, String destination) throws Exception {
     String newDir = computeTargetPath(path, source, destination);
     mFileSystem.createDirectory(new AlluxioURI(newDir),
-        CreateDirectoryPOptions.getDefaultInstance());
+        FileSystemOptions.createDirectoryDefaults(ServerConfiguration.global()));
```
Comment (ggezer) [inline job/server/src/main/java/alluxio/job/migrate/MigrateDefinition.java]: Doesn't mFileSystem do the merging already?

File: shell/src/main/java/alluxio/cli/fs/command/CatCommand.java [hunk 13]
```diff
@@ -54,7 +55,7 @@ protected void runPlainPath(AlluxioURI path, CommandLine cl)
     if (status.isFolder()) {
       throw new FileDoesNotExistException(ExceptionMessage.PATH_MUST_BE_FILE.getMessage(path));
     }
-    OpenFilePOptions options = OpenFilePOptions.getDefaultInstance();
+    OpenFilePOptions options = FileSystemOptions.openFileDefaults(mFileSystem.getConf());
```
Comment (ggezer) [inline shell/src/main/java/alluxio/cli/fs/command/CatCommand.java]: This is passed to a FileSystem. Merging should be done there.

File: shell/src/main/java/alluxio/cli/fs/command/CheckConsistencyCommand.java [hunk 14]
```diff
@@ -109,7 +110,8 @@ public int run(CommandLine cl) throws AlluxioException, IOException {
   private void runConsistencyCheck(AlluxioURI path, boolean repairConsistency) throws
       AlluxioException, IOException {
     List<AlluxioURI> inconsistentUris =
-        checkConsistency(path, CheckConsistencyPOptions.getDefaultInstance());
```
Comment (ggezer) [inline shell/src/main/java/alluxio/cli/fs/command/CheckConsistencyCommand.java]: FileSystem should do merging.

File: shell/src/main/java/alluxio/cli/fs/command/CpCommand.java [hunk 15]
```diff
@@ -521,7 +522,8 @@ private void copy(AlluxioURI srcPath, AlluxioURI dstPath, boolean recursive)
   private void copyFile(AlluxioURI srcPath, AlluxioURI dstPath)
       throws AlluxioException, IOException {
     try (Closer closer = Closer.create()) {
-      OpenFilePOptions openFileOptions = OpenFilePOptions.getDefaultInstance();
```
Comment (ggezer) [inline shell/src/main/java/alluxio/cli/fs/command/CpCommand.java]: FileSystem should do merging.

File: shell/src/main/java/alluxio/cli/fs/command/CpCommand.java [hunk 16]
```diff
@@ -738,7 +740,7 @@ private void copyFileToLocal(AlluxioURI srcPath, AlluxioURI dstPath)
     File tmpDst = new File(outputFile.getPath() + randomSuffix);
 
     try (Closer closer = Closer.create()) {
-      OpenFilePOptions options = OpenFilePOptions.getDefaultInstance();
```
Comment (ggezer) [inline shell/src/main/java/alluxio/cli/fs/command/CpCommand.java]: FileSystem should do merging.

File: shell/src/main/java/alluxio/cli/fs/command/FileSystemCommandUtils.java [hunk 17]
```diff
@@ -43,7 +44,9 @@ private FileSystemCommandUtils() {} // prevent instantiation
   public static void setTtl(FileSystem fs, AlluxioURI path, long ttlMs,
       TtlAction ttlAction) throws AlluxioException, IOException {
     SetAttributePOptions options = SetAttributePOptions.newBuilder().setRecursive(true)
-        .setTtl(ttlMs).setTtlAction(ttlAction).build();
```
Comment (ggezer) [inline shell/src/main/java/alluxio/cli/fs/command/FileSystemCommandUtils.java]: FileSystem should do merging.

File: shell/src/main/java/alluxio/cli/fs/command/HeadCommand.java [hunk 18]
```diff
@@ -70,7 +71,7 @@ protected void runPlainPath(AlluxioURI plainPath, CommandLine cl)
     if (status.isFolder()) {
       throw new IOException(ExceptionMessage.PATH_MUST_BE_FILE.getMessage(plainPath));
     }
-    OpenFilePOptions options = OpenFilePOptions.getDefaultInstance();
```
Comment (ggezer) [inline shell/src/main/java/alluxio/cli/fs/command/HeadCommand.java]: FileSystem should do merging.

File: shell/src/main/java/alluxio/cli/fs/command/TailCommand.java [hunk 19]
```diff
@@ -68,7 +69,7 @@ protected void runPlainPath(AlluxioURI path, CommandLine cl)
     if (status.isFolder()) {
       throw new IOException(ExceptionMessage.PATH_MUST_BE_FILE.getMessage(path));
     }
-    OpenFilePOptions options = OpenFilePOptions.getDefaultInstance();
```
Comment (ggezer) [inline shell/src/main/java/alluxio/cli/fs/command/TailCommand.java]: FileSystem should do merging.

File: core/server/proxy/src/main/java/alluxio/proxy/PathsRestServiceHandler.java (hunk 11 above)
Comment (ZacBlanco) [reply core/server/proxy/src/main/java/alluxio/proxy/PathsRestServiceHandler.java]: Good catch. I changed this before we did the merging. Fixed

File: tests/src/main/java/alluxio/master/backcompat/ops/PersistFile.java [hunk 20]
```diff
@@ -37,10 +38,10 @@ public void apply(Clients clients) throws Exception {
     FileSystem fs = clients.getFileSystemClient();
     Utils.createFile(fs, PATH);
     clients.getFileSystemMasterClient().scheduleAsyncPersist(PATH,
-        ScheduleAsyncPersistencePOptions.getDefaultInstance());
```
Comment (ggezer) [inline tests/src/main/java/alluxio/master/backcompat/ops/PersistFile.java]: FileSystem should do merging.

File: tests/src/test/java/alluxio/client/cli/fs/FileSystemShellUtilsTest.java [hunk 21]
```diff
@@ -125,9 +126,11 @@ public static String resetFileHierarchy(FileSystem fs, WritePType writeType)
     if (fs.exists(new AlluxioURI(TEST_DIR))) {
       fs.delete(new AlluxioURI(TEST_DIR), DeletePOptions.newBuilder().setRecursive(true).build());
     }
-    fs.createDirectory(new AlluxioURI(TEST_DIR));
-    fs.createDirectory(new AlluxioURI(TEST_DIR + "/foo"));
-    fs.createDirectory(new AlluxioURI(TEST_DIR + "/bar"));
+    CreateDirectoryPOptions dirOptions = CreateDirectoryPOptions.getDefaultInstance().toBuilder()
```
Comment (ggezer) [inline tests/src/test/java/alluxio/client/cli/fs/FileSystemShellUtilsTest.java]: Why did you have to change this now?

File: tests/src/test/java/alluxio/client/cli/fs/command/LsCommandIntegrationTest.java [hunk 22]
```diff
@@ -393,10 +394,10 @@ public void lsWithExtendedAcl() throws IOException, AlluxioException {
 
     mFileSystem.setAcl(new AlluxioURI("/testRoot/testDir"), SetAclAction.MODIFY,
         Arrays.asList(AclEntry.fromCliString("default:user:nameduser:rwx")),
-        SetAclPOptions.getDefaultInstance());
```
Comment (ggezer) [inline tests/src/test/java/alluxio/client/cli/fs/command/LsCommandIntegrationTest.java]: FileSystem should do merging.

File: tests/src/test/java/alluxio/client/fs/BufferedBlockInStreamIntegrationTest.java [hunk 23]
```diff
@@ -62,7 +64,8 @@ public static void beforeClass() throws Exception {
 
   private static List<CreateFilePOptions> getOptionSet() {
     List<CreateFilePOptions> ret = new ArrayList<>(3);
-    CreateFilePOptions optionsDefault = CreateFilePOptions.getDefaultInstance();
```
Comment (ggezer) [inline tests/src/test/java/alluxio/client/fs/BufferedBlockInStreamIntegrationTest.java]: FileSystem should do merging.

File: tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterSetTtlTest.java [hunk 24]
```diff
@@ -133,7 +134,9 @@ public void run() {
             AuthenticatedClientUser.set(TEST_USER);
             barrier.await();
             mFileSystem.setAttribute(paths[iteration], SetAttributePOptions.newBuilder()
-                .setTtl(ttls[iteration]).setTtlAction(TtlAction.DELETE).build());
```
Comment (ggezer) [inline tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterSetTtlTest.java]: FileSystem should do merging.

File: tests/src/test/java/alluxio/client/fs/FileSystemIntegrationTest.java [hunk 25]
```diff
@@ -334,8 +335,8 @@ public void createExistingDirectory() throws Exception {
   @Test
   public void createDirectoryOnTopOfFile() throws Exception {
     AlluxioURI path = new AlluxioURI("/dir");
-    FileSystemTestUtils.createByteFile(mFileSystem, path, CreateFilePOptions.getDefaultInstance(),
-        10);
+    FileSystemTestUtils.createByteFile(mFileSystem, path,
```
Comment (ggezer) [inline tests/src/test/java/alluxio/client/fs/FileSystemIntegrationTest.java]: FileSystem should do merging.

File: shell/src/main/java/alluxio/cli/fs/command/FileSystemCommandUtils.java (hunk 17 above)
Comment (ZacBlanco) [reply shell/src/main/java/alluxio/cli/fs/command/FileSystemCommandUtils.java]: The user is passing a specific ttl+action here we want to override options

File: tests/src/test/java/alluxio/client/fs/LoadMetadataIntegrationTest.java [hunk 26]
```diff
@@ -174,35 +174,33 @@ public void loadMetadataOnceAfterUfsDelete() throws Exception {
 
   @Test
   public void loadAlwaysConfiguration() throws Exception {
```
Comment (ggezer) [inline tests/src/test/java/alluxio/client/fs/LoadMetadataIntegrationTest.java]: Whole test goes through FileSystem. So merging should supply the defaults.

File: tests/src/main/java/alluxio/master/backcompat/ops/PersistFile.java (hunk 20 above)
Comment (ZacBlanco) [reply tests/src/main/java/alluxio/master/backcompat/ops/PersistFile.java]: Not here, we don't use a `FileSystem` object. Options must be specified to this client.

File: tests/src/test/java/alluxio/client/cli/fs/FileSystemShellUtilsTest.java (hunk 21 above)
Comment (ZacBlanco) [reply tests/src/test/java/alluxio/client/cli/fs/FileSystemShellUtilsTest.java]: Because the client configuration write type is set as `CACHE_THROUGH` and when the directories are created we expect them to be in a not-persisted state. Without passing the write type here the directories weren't being created with the proper write type and the assertion was failing for tests which checked that the directory wasn't persisted after creating the file hierarchy

File: tests/src/main/java/alluxio/master/backcompat/ops/PersistFile.java (hunk 20 above)
Comment (ggezer) [reply tests/src/main/java/alluxio/master/backcompat/ops/PersistFile.java]: Right. You're calling the client. My bad.
I was consumed by Copy/Paste rage...

File: tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterSetTtlTest.java (hunk 24 above)
Comment (ZacBlanco) [reply tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterSetTtlTest.java]: We want to specifically set the TTL and Ttl action here which varies from iteration to iteration. Passing options here is required. It's only changed because setAttribute no longer has TTL and TTL action as a top-level attribute. They both exists in common options now

File: core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java (hunk 8 above)
Comment (ZacBlanco) [reply core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java]: Yes, but the public API calls this rename method

File: core/client/fs/src/main/java/alluxio/util/FileSystemOptions.java (hunk 9 above)
Comment (ZacBlanco) [reply core/client/fs/src/main/java/alluxio/util/FileSystemOptions.java]: I considered it, but it would require another big change because all of the methods that call this will now need to use `build()` in a lot of places. I think the change would be for the better but I put it off because of the amount of work required.

If it's something you'd like to see I can implement it once I address the rest of the comments

File: shell/src/main/java/alluxio/cli/fs/command/CheckConsistencyCommand.java (hunk 14 above)
Comment (ZacBlanco) [reply shell/src/main/java/alluxio/cli/fs/command/CheckConsistencyCommand.java]: The checkConsistency function uses the underlying client, not the public client API. So it still needs to merge options.

File: tests/src/main/java/alluxio/master/backcompat/ops/PersistFile.java (hunk 20 above)
Comment (ZacBlanco) [reply tests/src/main/java/alluxio/master/backcompat/ops/PersistFile.java]: It happens to the best of us

File: tests/src/test/java/alluxio/client/fs/LoadMetadataIntegrationTest.java (hunk 26 above)
Comment (ZacBlanco) [reply tests/src/test/java/alluxio/client/fs/LoadMetadataIntegrationTest.java]: The issue is that the clients are created after the cluster is started and before we have a chance to set configuration, so these tests need to specifically set the options in order for their values to be respected

Comment (ZacBlanco) [reply tests/src/test/java/alluxio/client/fs/LoadMetadataIntegrationTest.java]: However after closer inspection I think I changed how this test expected to work.

I've restored the original functionality by adding cluster resource config annotations to those tests

```
  @LocalAlluxioClusterResource.Config(
      confParams = {
          PropertyKey.Name.USER_FILE_METADATA_LOAD_TYPE, "NEVER/ONCE/ALWAYS"
      })
```

File: job/server/src/main/java/alluxio/job/migrate/MigrateDefinition.java (hunk 12 above)
Comment (ZacBlanco) [reply job/server/src/main/java/alluxio/job/migrate/MigrateDefinition.java]: fixed

File: shell/src/main/java/alluxio/cli/fs/command/CatCommand.java (hunk 13 above)
Comment (ZacBlanco) [reply shell/src/main/java/alluxio/cli/fs/command/CatCommand.java]: fixed

File: shell/src/main/java/alluxio/cli/fs/command/CpCommand.java (hunk 15 above)
Comment (ZacBlanco) [reply shell/src/main/java/alluxio/cli/fs/command/CpCommand.java]: fixed

File: shell/src/main/java/alluxio/cli/fs/command/CpCommand.java (hunk 16 above)
Comment (ZacBlanco) [reply shell/src/main/java/alluxio/cli/fs/command/CpCommand.java]: fixed

File: shell/src/main/java/alluxio/cli/fs/command/HeadCommand.java (hunk 18 above)
Comment (ZacBlanco) [reply shell/src/main/java/alluxio/cli/fs/command/HeadCommand.java]: fixed

File: shell/src/main/java/alluxio/cli/fs/command/TailCommand.java (hunk 19 above)
Comment (ZacBlanco) [reply shell/src/main/java/alluxio/cli/fs/command/TailCommand.java]: fixed

File: tests/src/test/java/alluxio/client/cli/fs/command/LsCommandIntegrationTest.java (hunk 22 above)
Comment (ZacBlanco) [reply tests/src/test/java/alluxio/client/cli/fs/command/LsCommandIntegrationTest.java]: fixed

File: tests/src/test/java/alluxio/client/fs/FileSystemIntegrationTest.java (hunk 25 above)
Comment (ZacBlanco) [reply tests/src/test/java/alluxio/client/fs/FileSystemIntegrationTest.java]: fixed

File: tests/src/test/java/alluxio/client/fs/BufferedBlockInStreamIntegrationTest.java (hunk 23 above)
Comment (ZacBlanco) [reply tests/src/test/java/alluxio/client/fs/BufferedBlockInStreamIntegrationTest.java]: fixed

**Comment by ZacBlanco** [comment]
jenkins, test this please
