### PR TITLE
Disable passive cache for pinned files

### LINKED ISSUE #15912: Alluxio replicates the block repeatedly without committing it
**Alluxio Version:**
2.7.1

**Describe the bug**
Alluxio replicates the block repeatedly without committing it

**To Reproduce**
1. The file has 1 existing replica

```
$ ./bin/alluxio fs location /projects/test/test_dir/file.1
/projects/test/test_dir/file.1 with file id 134939148287 is on nodes:
dev01-xx
```

2. Set replicationMin to 2 and pin the file

```
$ ./bin/alluxio fs setReplication --min 2 /projects/test/test_dir/file.1
$ ./bin/alluxio fs pin /projects/test/test_dir/file.1
```

3. Alluxio replicates the file repeatedly without committing it

```
2022-07-19 15:55:56,690 INFO  task.TaskExecutorManager (TaskExecutorManager.java:executeTask) - Task 0 for job 1652866638371 received
2022-07-19 15:55:56,690 INFO  task.TaskExecutorManager (TaskExecutorManager.java:notifyTaskRunning) - Task 0 for job 1652866638371 started
2022-07-19 15:55:56,741 INFO  replicate.ReplicateDefinition (ReplicateDefinition.java:runTask) - Replicated file /projects/test/test_dir/file.1 block 134922371072
2022-07-19 15:55:56,742 INFO  task.TaskExecutorManager (TaskExecutorManager.java:notifyTaskCompletion) - Task 0 for job 1652866638371 completed.
2022-07-19 15:56:56,692 INFO  command.CommandHandlingExecutor (CommandHandlingExecutor.java:run) - Received run task 0 for job 1652866638372 on worker 1652866621069
2022-07-19 15:56:56,692 INFO  task.TaskExecutorManager (TaskExecutorManager.java:executeTask) - Task 0 for job 1652866638372 received
2022-07-19 15:56:56,693 INFO  task.TaskExecutorManager (TaskExecutorManager.java:notifyTaskRunning) - Task 0 for job 1652866638372 started
2022-07-19 15:56:56,763 INFO  replicate.ReplicateDefinition (ReplicateDefinition.java:runTask) - Replicated file /projects/test/test_dir/file.1 block 134922371072
2022-07-19 15:56:56,763 INFO  task.TaskExecutorManager (TaskExecutorManager.java:notifyTaskCompletion) - Task 0 for job 1652866638372 completed.
```

**Expected behavior**
Commit the block and do not replicate it repeatedly.

**Urgency**
High

**Are you planning to fix it**
Yes

### PR DESCRIPTION
**Pull request by secfree**
### What changes are proposed in this pull request?

Disable passive cache for pinned files.

### Why are the changes needed?

Fix #15912

### Does this PR introduce any user facing changes?

No

### CODE REVIEW

**Review by jja725 — APPROVED** [review]
LGTM

File: job/server/src/main/java/alluxio/job/util/JobUtils.java [hunk 1]
```diff
@@ -147,7 +147,7 @@ public static void loadBlock(URIStatus status, FileSystemContext context, long b
     // when the data to load is persisted, simply use local worker to load
     // from ufs (e.g. distributed load) or from a remote worker (e.g. setReplication)
     // Only use this read local first method to load if nearest worker is clear
-    if (netAddress.size() <= 1 && pinnedLocation.isEmpty() && status.isPersisted()) {
+    if (netAddress.size() <= 1 && !status.getFileInfo().isPinned() && status.isPersisted()) {
```
Comment (yuzhu) [inline job/server/src/main/java/alluxio/job/util/JobUtils.java:150]: could you explain why pinned files can not go through this code path? and why this would fix the previous issue? it is not too clear to me.

**Review by rongrong — APPROVED** [review]

File: job/server/src/main/java/alluxio/job/util/JobUtils.java (hunk 1 above)
Comment (yuzhu) [reply job/server/src/main/java/alluxio/job/util/JobUtils.java:150]: discussed offlline with @jja725 . LGTM

**Review by yuzhu — APPROVED** [review]

**Comment by yyongycy** [comment]
aluxio-bot, merge this please

Since it is approved by 3 reviewers
