### PR TITLE
Fix bug in meta cache in MetadataCachingBaseFileSystem

### LINKED ISSUE #11765: Incorrect cache update strategy in MetadataCachingBaseFileSystem
**Alluxio Version:**
v2.2.0

**Describe the bug**
meta data may be deleted in client cache although it is very hot. 
Now MetadataCache holds mStatus which stores the current file/dir status and mDirStatuses which stores the children status.
```
  private class CachedItem {
    private final URIStatus mStatus;
    private final List<URIStatus> mDirStatuses;
```
1. For example, There is a path '/A/B/C'.
2. We run the listStatus request on the directory '/A/B'. After receiving result from alluxio master, it caches 'A/B' into the cache map which stores the children status for the path '/A/B' as mDirStatuses and its children '/A/B/C' into the cach map which stores the file/dir status as mStatus. 
3. Then we run the listStatus request on the directory '/A'. After receiving result from alluxio master, it caches '/A' into the cache map which stores the children status for the path '/A' as mDirStatuses  and its children '/A/B' into the cach map which stores the file/dir status as mStatus. It replaces the previous content with a new CachedItem for '/A/B'.
```
public void put(AlluxioURI dir, List<URIStatus> statuses) {
    mCache.put(dir.getPath(), new CachedItem(statuses));
    for (URIStatus status : statuses) {
      mCache.put(status.getPath(), new CachedItem(status));
    }
```
4. If you rerun the listStatus request on the directory '/A/B', you could not get the result. Because although the path '/A/B' is in the cache, it holds the content with mStatus. And the CachedItem with mDirStatuses has been replaced in the step 3. 

**To Reproduce**
As above

**Expected behavior**

**Urgency**

**Additional context**

### PR DESCRIPTION
**Pull request by QianxiZhang**
Fix #11765

Description:
meta data may be deleted in client cache although it is very hot. 
Now MetadataCache holds mStatus which stores the current file/dir status and mDirStatuses which stores the children status.
```
  private class CachedItem {
    private final URIStatus mStatus;
    private final List<URIStatus> mDirStatuses;
```
1. For example, There is a path '/A/B/C'.
2. We run the listStatus request on the directory '/A/B'. After receiving result from alluxio master, it caches 'A/B' into the cache map which stores the children status for the path '/A/B' as mDirStatuses and its children '/A/B/C' into the cach map which stores the file/dir status as mStatus. 
3. Then we run the listStatus request on the directory '/A'. After receiving result from alluxio master, it caches '/A' into the cache map which stores the children status for the path '/A' as mDirStatuses  and its children '/A/B' into the cach map which stores the file/dir status as mStatus. It replaces the previous content with a new CachedItem for '/A/B'.
```
public void put(AlluxioURI dir, List<URIStatus> statuses) {
    mCache.put(dir.getPath(), new CachedItem(statuses));
    for (URIStatus status : statuses) {
      mCache.put(status.getPath(), new CachedItem(status));
    }
```
4. If you rerrun the listStatus request on the directory '/A/B', you could not get the result. Because although the path '/A/B' is in the cache, it holds the content with mStatus. And the CachedItem with mDirStatuses has been replaced in the step 3. 

Fixes #11765

### CODE REVIEW

**Comment by gpang** [comment]
@QianxiZhang Thanks for this contribution!

Could you create an issue (https://github.com/Alluxio/alluxio/issues) for this bug? The content in the PR description can go there.

Also, could add a unit test for this fix?

**Comment by QianxiZhang** [comment]
> @QianxiZhang Thanks for this contribution!
> Could you create an issue (https://github.com/Alluxio/alluxio/issues) for this bug? The content in the PR description can go there.
> Also, could add a unit test for this fix?

Sure. Will do. @gpang

File: core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java [hunk 1]
```diff
@@ -118,9 +127,19 @@ public void put(String path, URIStatus status) {
...
+        public CachedItem call() throws Exception {
+          return new CachedItem();
+        }
+      });
+      item.setDirStatuses(statuses);
+      for (URIStatus status : statuses) {
+        put(status.getPath(), status);
+      }
+    } catch (Exception e) {
+      e.printStackTrace();
```
Comment (ZacBlanco) [inline core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java:142]: We should be logging any exceptions here instead of calling `printStackTrace`

Example:

at the top of the class

```java
private static final Logger LOG = LoggerFactory.getLogger(MetadataCache.class);
```

then in here and the other try/catch

```java
LogUtils.warnWithException(LOG, "Failed to cache metadata", e)
```

File: core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java [hunk 2]
```diff
@@ -100,15 +99,25 @@ public URIStatus get(AlluxioURI path) {
...
+      CachedItem item = mCache.get(path, new Callable<CachedItem>() {
+        @Override
+        public CachedItem call() throws Exception {
+          return new CachedItem();
+        }
+      });
+      item.setStatus(status);
+    } catch (Exception e) {
+      e.printStackTrace();
+    }
```
Comment (ZacBlanco) [inline core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java:120]: same comments about logging and catching exceptions here.

File: core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java [hunk 3]
```diff
@@ -118,9 +127,19 @@ public void put(String path, URIStatus status) {
...
+        @Override
+        public CachedItem call() throws Exception {
+          return new CachedItem();
+        }
+      });
+      item.setDirStatuses(statuses);
+      for (URIStatus status : statuses) {
+        put(status.getPath(), status);
+      }
+    } catch (Exception e) {
```
Comment (ZacBlanco) [inline core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java:141]: Generally, it's not a good practice to catch `Exception` - we should really only catch exceptions that we know can be thrown. Is there a list of exceptions you know could be thrown here?

File: core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java [hunk 4]
```diff
@@ -100,15 +99,25 @@ public URIStatus get(AlluxioURI path) {
...
-    mCache.put(path, new CachedItem(status));
+    try {
+      CachedItem item = mCache.get(path, new Callable<CachedItem>() {
+        @Override
+        public CachedItem call() throws Exception {
+          return new CachedItem();
+        }
+      });
+      item.setStatus(status);
+    } catch (Exception e) {
```
Comment (apc999) [inline core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java:118]: good to be explicit on which Exception we are catching here?

File: core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java [hunk 5]
```diff
@@ -67,6 +48,24 @@ public URIStatus getStatus() {
     public List<URIStatus> getDirStatuses() {
       return mDirStatuses;
     }
+
+    /**
+     *  put the status into cache
```
Comment (apc999) [inline core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java:53]: `Puts the status into cache.` or the style checker will fail and complain

File: core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java [hunk 6]
```diff
@@ -67,6 +48,24 @@ public URIStatus getStatus() {
...
+     *
+     *  @param status the metadata of the path
+     */
+    public void setStatus(URIStatus status) {
+      mStatus = status;
+    }
+
+    /**
+     *  put the directory status into cache
```
Comment (apc999) [inline core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java:62]: ditto 👆

**Comment by apc999** [comment]
@QianxiZhang can you address these comments? thanks

**Comment by QianxiZhang** [comment]
@apc999 Sorry. I have some trouble with my account. Sure, I will handle these comments.

File: core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java (hunk 2 above)
Comment (QianxiZhang) [reply core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java:116]: Sure. It should be ExecutionException and log the error info.

**Comment by QianxiZhang** [comment]
@apc999 @ZacBlanco 
I have updated the commit. Please review.
Thanks.

**Comment by apc999** [comment]
I made some minor tuning on logging and indent.
LGTM and will merge this improvement after tests pass

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by apc999** [comment]
Jenkins, test this please

**Comment by gpang** [comment]
@QianxiZhang 
@apc999

Is there a github issue we can link to? Also, is there a more specific PR title we can use as to what was exactly fixed? Lastly, is there a simple unittest we can add to verify the correct behavior?

**Comment by zqxjjj** [comment]
> @QianxiZhang
> @apc999
> 
> Is there a github issue we can link to? Also, is there a more specific PR title we can use as to what was exactly fixed? Lastly, is there a simple unittest we can add to verify the correct behavior?
@gpang 
1. Here is the issue. https://github.com/Alluxio/alluxio/issues/11765
2. I agree. Let me think another title which can describe this PR more accurately.
3. I am writing a unittest for this issue. Will update later.

**Comment by apc999** [comment]
@QianxiZhang @zqxjjj  Thanks! Please update the unit test here so I could merge them together

**Comment by QianxiZhang** [comment]
@apc999 
I have added unit test for this issue. Please help to review.
Thanks

**Comment by ZacBlanco** [comment]
jenkins, test this please

**Comment by ZacBlanco** [comment]
jenkins, test this please

**Comment by apc999** [comment]
alluxio-bot, merge this please
