### PR TITLE
Fix worker/client to get right cluster config

### LINKED ISSUE #10745: Incorrect cluster-default configuration propagation
**Alluxio Version:**
2.1.1

**Describe the bug**
Incorrect cluster-default configuration propagation:
- Currently we only propagates property keys with scope `CLIENT` or `ALL` to both client and workers, but not these property keys with scope `WORKER` to workers.
- Some job server property keys are marked with scope `ALL` and got propagated.

**To Reproduce**

**Expected behavior**
- Propagate `CLIENT` or `ALL` to client side conf
- Propagate `WORKER` or `ALL` to worker side conf

**Urgency**
Medium

**Additional context**

See the following list of properties received by a worker

```
2020-01-14 01:07:45,832 INFO  ConfigurationUtils - Loading property: alluxio.user.network.netty.worker.threads (CLIENT) -> 0
2020-01-14 01:07:45,832 INFO  ConfigurationUtils - Loading property: alluxio.debug (ALL) -> false
2020-01-14 01:07:45,832 INFO  ConfigurationUtils - Loading property: alluxio.master.hostname (ALL) -> localhost
2020-01-14 01:07:45,832 INFO  ConfigurationUtils - Loading property: alluxio.web.cors.enabled (ALL) -> false
2020-01-14 01:07:45,832 INFO  ConfigurationUtils - Loading property: alluxio.master.persistence.initial.interval (ALL) -> 1s
2020-01-14 01:07:45,832 INFO  ConfigurationUtils - Loading property: alluxio.user.network.writer.buffer.size.messages (CLIENT) -> 16
2020-01-14 01:07:45,832 INFO  ConfigurationUtils - Loading property: alluxio.user.conf.sync.interval (CLIENT) -> 1min
2020-01-14 01:07:45,832 INFO  ConfigurationUtils - Loading property: alluxio.job.master.finished.job.retention.time (ALL) -> 300sec
2020-01-14 01:07:45,832 INFO  ConfigurationUtils - Loading property: alluxio.conf.dir (ALL) -> /Users/binfan/Dropbox/Work/alluxio/alluxio/conf
2020-01-14 01:07:45,832 INFO  ConfigurationUtils - Loading property: alluxio.job.master.embedded.journal.port (ALL) -> 20003
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.user.file.copyfromlocal.block.location.policy.class (CLIENT) -> alluxio.client.block.policy.RoundRobinPolicy
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.user.network.zerocopy.enabled (CLIENT) -> true
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.network.host.resolution.timeout (ALL) -> 5sec
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.user.logs.dir (ALL) -> /Users/binfan/Dropbox/Work/alluxio/alluxio/logs/user
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.master.embedded.journal.port (ALL) -> 19200
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.zookeeper.leader.path (ALL) -> /alluxio/leader
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.zookeeper.session.timeout (ALL) -> 60s
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.user.network.netty.channel (CLIENT) -> EPOLL
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.user.network.data.timeout (CLIENT) -> 30sec
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.user.file.writetype.default (CLIENT) -> MUST_CACHE
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.zookeeper.connection.timeout (ALL) -> 15s
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.network.connection.shutdown.timeout (ALL) -> 60sec
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.master.persistence.max.interval (ALL) -> 1hr
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.user.block.avoid.eviction.policy.reserved.size.bytes (CLIENT) -> 0MB
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.master.persistence.max.total.wait.time (ALL) -> 1day
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.locality.script (ALL) -> alluxio-locality.sh
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.job.master.hostname (ALL) -> localhost
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.user.network.writer.close.timeout (CLIENT) -> 30min
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.user.block.worker.client.read.retry (CLIENT) -> 5
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.user.local.writer.chunk.size.bytes (CLIENT) -> 64KB
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.user.ufs.block.read.concurrency.max (CLIENT) -> 2147483647
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.job.worker.data.port (ALL) -> 30002
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.user.ufs.block.location.all.fallback.enabled (CLIENT) -> false
2020-01-14 01:07:45,833 INFO  ConfigurationUtils - Loading property: alluxio.underfs.version (ALL) -> 2.7
2020-01-14 01:07:45,834 INFO  ConfigurationUtils - Loading property: alluxio.user.file.master.client.threads (CLIENT) -> 10
2020-01-14 01:07:45,834 INFO  ConfigurationUtils - Loading property: alluxio.zookeeper.job.leader.path (ALL) -> /job_leader
2020-01-14 01:07:45,834 INFO  ConfigurationUtils - Loading property: alluxio.master.persistence.scheduler.interval (ALL) -> 1s
2020-01-14 01:07:45,834 INFO  ConfigurationUtils - Loading property: alluxio.logs.dir (ALL) -> /Users/binfan/Dropbox/Work/alluxio/alluxio/logs
2020-01-14 01:07:45,834 INFO  ConfigurationUtils - Loading property: alluxio.user.block.worker.client.pool.gc.threshold (CLIENT) -> 300sec
2020-01-14 01:07:45,834 INFO  ConfigurationUtils - Loading property: alluxio.user.block.size.bytes.default (CLIENT) -> 64MB
2020-01-14 01:07:45,834 INFO  ConfigurationUtils - Loading property: alluxio.job.worker.throttling (ALL) -> false
2020-01-14 01:07:45,834 INFO  ConfigurationUtils - Loading property: alluxio.debug (ALL) -> false
2020-01-14 01:07:45,834 INFO  ConfigurationUtils - Loading property: alluxio.web.cors.enabled (ALL) -> false
2020-01-14 01:07:45,834 INFO  ConfigurationUtils - Loading property: alluxio.user.network.writer.buffer.size.messages (CLIENT) -> 16
2020-01-14 01:07:45,834 INFO  ConfigurationUtils - Loading property: alluxio.job.master.finished.job.retention.time (ALL) -> 300sec
2020-01-14 01:07:45,834 INFO  ConfigurationUtils - Loading property: alluxio.job.master.embedded.journal.port (ALL) -> 20003
2020-01-14 01:07:45,834 INFO  ConfigurationUtils - Loading property: alluxio.user.network.zerocopy.enabled (CLIENT) -> true
2020-01-14 01:07:45,834 INFO  ConfigurationUtils - Loading property: alluxio.user.logs.dir (ALL) -> /Users/binfan/Dropbox/Work/alluxio/alluxio/logs/user
2020-01-14 01:07:45,834 INFO  ConfigurationUtils - Loading property: alluxio.zookeeper.leader.path (ALL) -> /alluxio/leader
2020-01-14 01:07:45,834 INFO  ConfigurationUtils - Loading property: alluxio.user.network.netty.channel (CLIENT) -> EPOLL
2020-01-14 01:07:45,834 INFO  ConfigurationUtils - Loading property: alluxio.user.file.writetype.default (CLIENT) -> MUST_CACHE
2020-01-14 01:07:45,834 INFO  ConfigurationUtils - Loading property: alluxio.network.connection.shutdown.timeout (ALL) -> 60sec
2020-01-14 01:07:45,894 INFO  AlluxioWorkerProcess - Started Alluxio worker @10.0.1.55:29999 with id 9222847217999742283
```

### PR DESCRIPTION
**Pull request by LuQQiu**
Fixes #10745

### CODE REVIEW

**Comment by LuQQiu** [comment]
Jenkins, test this please

File: core/common/src/main/java/alluxio/conf/PropertyKey.java [hunk 1]
```diff
@@ -485,54 +497,62 @@ public String toString() {
...
           .setDescription("Address of ZooKeeper.")
           .setConsistencyCheckLevel(ConsistencyCheckLevel.ENFORCE)
+          .setScope(Scope.ALL)
           .build();
   public static final PropertyKey ZOOKEEPER_CONNECTION_TIMEOUT =
       new Builder(Name.ZOOKEEPER_CONNECTION_TIMEOUT)
           .setDefaultValue("15s") // matches Zookeeper's default
           .setDescription("Connection timeout to use when connecting to Zookeeper")
           .setConsistencyCheckLevel(ConsistencyCheckLevel.WARN)
+          .setScope(Scope.MASTER)
```
Comment (apc999) [inline core/common/src/main/java/alluxio/conf/PropertyKey.java]: is this `Scope.ALL`? don't we use it on client side?

File: core/common/src/main/java/alluxio/conf/PropertyKey.java [hunk 2]
```diff
@@ -292,6 +292,7 @@ public String toString() {
           .setDescription("The directory containing files used to configure Alluxio.")
           .setIgnoredSiteProperty(true)
           .setConsistencyCheckLevel(ConsistencyCheckLevel.WARN)
+          .setScope(Scope.ALL)
```
Comment (apc999) [inline core/common/src/main/java/alluxio/conf/PropertyKey.java]: default scope is `Scope.ALL` right?

File: core/common/src/main/java/alluxio/conf/PropertyKey.java [hunk 3]
```diff
@@ -485,54 +497,62 @@ public String toString() {
               + "the journal, logs, and under file storage data (if using local filesystem) "
               + "are written here.")
           .setConsistencyCheckLevel(ConsistencyCheckLevel.WARN)
+          .setScope(Scope.ALL)
```
Comment (apc999) [inline core/common/src/main/java/alluxio/conf/PropertyKey.java]: `Scope.SERVER`?

File: core/server/common/src/main/java/alluxio/conf/ServerConfiguration.java [hunk 4]
```diff
@@ -345,13 +346,13 @@ public static InstancedConfiguration global() {
...
    */
-  public static synchronized void loadClusterDefaultsIfNotLoaded(InetSocketAddress address)
+  public static synchronized void loadClusterDefaultsIfNotLoadedForWorker(InetSocketAddress address)
       throws AlluxioStatusException {
     if (sConf.getBoolean(PropertyKey.USER_CONF_CLUSTER_DEFAULT_ENABLED)
         && !sConf.clusterDefaultsLoaded()) {
       GetConfigurationPResponse response = ConfigurationUtils.loadConfiguration(address, sConf,
           false, true);
-      AlluxioConfiguration conf = ConfigurationUtils.getClusterConf(response, sConf);
+      AlluxioConfiguration conf = ConfigurationUtils.getClusterConf(response, sConf, Scope.WORKER);
```
Comment (apc999) [inline core/server/common/src/main/java/alluxio/conf/ServerConfiguration.java]: @calvinjia do we now also have client on worker (or job worker)? Do we need to respect cluster-default client-side setting on worker / job worker too?

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 2 above)
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: Yeah, but this can distinguish the property keys that do not consider about its scope / undefined and the property keys that are actually of scope.ALL. And remind following developers to always set scope.

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 1 above)
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: It was used by primary selector to connect to Zookeeper, so it only used by Alluxio masters or job masters.
 I will update the description of this property

File: core/common/src/main/java/alluxio/util/ConfigurationUtils.java [hunk 5]
```diff
@@ -504,21 +504,22 @@ public static GetConfigurationPResponse loadConfiguration(InetSocketAddress addr
...
+   * Filters and loads properties contains certain scope from the property list returned by grpc.
    *
    * @param properties the property list returned by grpc
+   * @param scope the scope to filter the received property list
    * @param logMessage a function with key and value as parameter and returns debug log message
    * @return the loaded properties
    */
-  private static Properties loadClientProperties(List<ConfigProperty> properties,
-      BiFunction<PropertyKey, String, String> logMessage) {
+  private static Properties filterAndLoadProperties(List<ConfigProperty> properties,
```
[the remark this answers is not in the document]
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/util/ConfigurationUtils.java]: Another 
```
  /**
   * @param stream the stream to read properties from
   * @return a properties object populated from the stream
   */
  @Nullable
  public static Properties loadProperties(InputStream stream) {
```
already exists in the same file, that's why I give it another name

File: core/server/common/src/main/java/alluxio/conf/ServerConfiguration.java (hunk 4 above)
Comment (LuQQiu) [reply core/server/common/src/main/java/alluxio/conf/ServerConfiguration.java]: In my testing, there is one long-running client in leading master (not sure about the followers) and one long-running client on each worker. Those clients may be used for loading configuration from the leading master.

File: core/common/src/main/java/alluxio/ClientContext.java [hunk 6]
```diff
@@ -124,7 +125,7 @@ private ClientContext(@Nullable Subject subject, @Nullable AlluxioConfiguration
    * @param loadPathConf whether to load path level configuration
    * @throws AlluxioStatusException
    */
-  public synchronized void loadConf(InetSocketAddress address, boolean loadClusterConf,
+  public synchronized void loadConfForClient(InetSocketAddress address, boolean loadClusterConf,
```
[the remark this answers is not in the document]
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/ClientContext.java]: Make sense, Renamed back to `loadConf`, thanks

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 3 above)
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: Done, thanks

**Comment by LuQQiu** [comment]
@apc999 Addressed the comments, PTAL, thanks

**Comment by LuQQiu** [comment]
@apc999 PTAL, thanks

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 2 above)
Comment (ZacBlanco) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: Can we just enforce that all property keys define a scope? I think it would be better that way

File: core/common/src/main/java/alluxio/conf/PropertyKey.java [hunk 7]
```diff
@@ -350,7 +356,7 @@ public String toString() {
           .setDescription("The file path of the metrics system configuration file. By default "
               + "it is `metrics.properties` in the `conf` directory.")
           .setConsistencyCheckLevel(ConsistencyCheckLevel.WARN)
-          .setScope(Scope.SERVER)
+          .setScope(Scope.ALL)
```
Comment (ZacBlanco) [inline core/common/src/main/java/alluxio/conf/PropertyKey.java]: Does this really apply to `ALL`? For clients, this defines a path to a metrics properties file which might not necessarily exist if the client is remote to Alluxio.

File: core/common/src/main/java/alluxio/conf/PropertyKey.java [hunk 8]
```diff
@@ -441,6 +450,7 @@ public String toString() {
           .setDescription("Version of Alluxio. User should never modify this property.")
           .setIgnoredSiteProperty(true)
           .setIsHidden(true)
+          .setScope(Scope.ALL)
```
Comment (ZacBlanco) [inline core/common/src/main/java/alluxio/conf/PropertyKey.java]: could this be `Scope.NONE`?

File: core/common/src/main/java/alluxio/conf/PropertyKey.java [hunk 9]
```diff
@@ -417,13 +424,15 @@ public String toString() {
...
           .setConsistencyCheckLevel(ConsistencyCheckLevel.WARN)
+          .setScope(Scope.ALL)
           .build();
   public static final PropertyKey TEST_MODE =
       new Builder(Name.TEST_MODE)
           .setDefaultValue(false)
           .setDescription("Flag used only during tests to allow special behavior.")
           .setConsistencyCheckLevel(ConsistencyCheckLevel.WARN)
           .setIsHidden(true)
+          .setScope(Scope.ALL)
```
Comment (ZacBlanco) [inline core/common/src/main/java/alluxio/conf/PropertyKey.java]: Should this be `Scope.NONE`

File: core/common/src/main/java/alluxio/conf/PropertyKey.java [hunk 10]
```diff
@@ -2443,7 +2469,7 @@ public String toString() {
           .setDefaultValue(29999)
           .setDescription("The port for Alluxio worker's RPC service.")
           .setConsistencyCheckLevel(ConsistencyCheckLevel.WARN)
-          .setScope(Scope.WORKER)
+          .setScope(Scope.ALL)
```
Comment (ZacBlanco) [inline core/common/src/main/java/alluxio/conf/PropertyKey.java]: why is this `Scope.ALL`?

File: core/common/src/main/java/alluxio/conf/PropertyKey.java [hunk 11]
```diff
@@ -2724,6 +2750,7 @@ public String toString() {
           .setDefaultValue(Constants.S3_MULTIPART_TEMPORARY_DIR_SUFFIX)
           .setDescription("Suffix for the directory which holds parts during a multipart upload.")
           .setConsistencyCheckLevel(ConsistencyCheckLevel.ENFORCE)
+          .setScope(Scope.NONE)
```
Comment (ZacBlanco) [inline core/common/src/main/java/alluxio/conf/PropertyKey.java]: why is this `Scope.NONE`? Shouldn't this be `Scope.SERVER`?

File: core/common/src/main/java/alluxio/conf/PropertyKey.java [hunk 12]
```diff
@@ -3690,76 +3732,90 @@ public String toString() {
...
               + Name.JOB_MASTER_FINISHED_JOB_RETENTION_TIME + ".")
           .setDefaultValue(100000)
+          .setScope(Scope.MASTER)
           .build();
   public static final PropertyKey JOB_MASTER_WORKER_HEARTBEAT_INTERVAL =
       new Builder(Name.JOB_MASTER_WORKER_HEARTBEAT_INTERVAL)
           .setDescription("The amount of time that the Alluxio job worker should wait in between "
               + "heartbeats to the Job Master.")
           .setDefaultValue("1sec")
+          .setScope(Scope.MASTER)
```
Comment (ZacBlanco) [inline core/common/src/main/java/alluxio/conf/PropertyKey.java]: shouldn't this be `Scope.WORKER`?

File: core/common/src/main/java/alluxio/conf/PropertyKey.java [hunk 13]
```diff
@@ -3804,20 +3865,23 @@ public String toString() {
                   + "%s using the port defined in %s",
               Name.MASTER_RPC_ADDRESSES, Name.JOB_MASTER_RPC_PORT,
               Name.JOB_MASTER_EMBEDDED_JOURNAL_ADDRESSES, Name.JOB_MASTER_RPC_PORT))
-          .setScope(Scope.CLIENT)
+          .setScope(Scope.MASTER)
```
Comment (ZacBlanco) [inline core/common/src/main/java/alluxio/conf/PropertyKey.java]: shouldn't this be `Scope.ALL`? Clients need that information to connect to the job master? Mainly for CLI use cases

File: core/common/src/main/java/alluxio/conf/PropertyKey.java [hunk 14]
```diff
@@ -3804,20 +3865,23 @@ public String toString() {
...
           .build();
   public static final PropertyKey JOB_MASTER_EMBEDDED_JOURNAL_ADDRESSES =
       new Builder(Name.JOB_MASTER_EMBEDDED_JOURNAL_ADDRESSES)
           .setDescription(String.format("A comma-separated list of journal addresses for all job "
               + "masters in the cluster. The format is 'hostname1:port1,hostname2:port2,...'. "
               + "Defaults to the journal addresses set for the Alluxio masters (%s), but with the "
               + "job master embedded journal port.", Name.MASTER_EMBEDDED_JOURNAL_ADDRESSES))
+          .setScope(Scope.MASTER)
```
Comment (ZacBlanco) [inline core/common/src/main/java/alluxio/conf/PropertyKey.java]: shouldn't this be Scope.ALL? Clients need that information to connect to the job master? Mainly for CLI use cases

File: core/common/src/main/java/alluxio/util/ConfigurationUtils.java [hunk 15]
```diff
@@ -504,22 +504,23 @@ public static GetConfigurationPResponse loadConfiguration(InetSocketAddress addr
   }
 
   /**
-   * Loads client scope properties from the property list returned by grpc.
+   * Filters and loads properties contains certain scope from the property list returned by grpc.
```
Comment (ZacBlanco) [inline core/common/src/main/java/alluxio/util/ConfigurationUtils.java]: nit

```suggestion
   * Filters and loads properties with a certain scope from the property list returned by grpc.
```

File: core/common/src/main/java/alluxio/util/ConfigurationUtils.java [hunk 16]
```diff
@@ -504,22 +504,23 @@ public static GetConfigurationPResponse loadConfiguration(InetSocketAddress addr
...
     Properties props = new Properties();
     for (ConfigProperty property : properties) {
       String name = property.getName();
       // TODO(binfan): support propagating unsetting properties from master
       if (PropertyKey.isValid(name) && property.hasValue()) {
         PropertyKey key = PropertyKey.fromString(name);
-        if (!GrpcUtils.contains(key.getScope(), Scope.CLIENT)) {
-          // Only propagate client properties.
+        if (!GrpcUtils.contains(key.getScope(), scope)) {
+          // Only propagate properties contains the target scope
```
Comment (ZacBlanco) [inline core/common/src/main/java/alluxio/util/ConfigurationUtils.java]: If a property has scope `ALL` we want that included along with properties from the `CLIENT` scope, correct?

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 9 above)
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: One problem now is that there is no fix criteria for which scope a property falls in. My criteria is that if the PropertyKey is used in master or worker only, then they are Scope.MASTER or Scope.WORKER. If a property is used by both master and worker, or job master and job worker, then it falls to Scope.Server. If it's used by both server and client, it falls to ALL. For some property key that ony used by certain integration like MESOS, it falls to Scope.NONE. TEST_MODE is used in server and common codes.

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 10 above)
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: Because this property key is used by Core-common/InstanceConfiguration.validate()

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 11 above)
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: Previously all the Proxy properties are given `Scope.NONE`,  I actually not quite sure what scope should be given to Proxy properties. `Scope.NONE` and `Scope.SERVER` both make sense

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 12 above)
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: Yeah, you are right

File: core/common/src/main/java/alluxio/util/ConfigurationUtils.java (hunk 16 above)
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/util/ConfigurationUtils.java]: I add a description to only allow Scope=WORKER/CLIENT. 
Not sure about the SCOPE=ALL result

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 2 above)
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: I prefer not to because there are maybe some property keys generated from templates.

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 7 above)
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: Client will also check this file and start sink metrics if the file exists.

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 8 above)
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: The same as I talked before, not sure the gap between Scope.NONE and ALL. 
In my criteria, this properties used in everywhere, so it falls into the category of ALL

File: core/common/src/main/java/alluxio/util/ConfigurationUtils.java (hunk 15 above)
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/util/ConfigurationUtils.java]: Changed

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 14 above)
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: Changed to Scope.ALL, thanks

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 13 above)
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: Changed, thanks

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 12 above)
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: Changed, thanks

**Comment by LuQQiu** [comment]
@ZacBlanco  PTAL, thanks

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 8 above)
Comment (ZacBlanco) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: My worry is that in the case of client/server version mismatch, that the client would get this value from cluster defaults and subsequently report that it is the same version as the server - which may not be the case.

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 9 above)
Comment (ZacBlanco) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: I see. It sounds like we need to have more defined criteria for `Scope.NONE`. I am fine making this `ALL` for now.

File: core/common/src/main/java/alluxio/util/ConfigurationUtils.java (hunk 16 above)
Comment (ZacBlanco) [reply core/common/src/main/java/alluxio/util/ConfigurationUtils.java]: My understanding is that for properties marked with `Scope.CLIENT` and `Scope.ALL` should be propagated to the client when loading the cluster default values  - if only one is defined in the function, then we could be missing properties?

Comment (ZacBlanco) [reply core/common/src/main/java/alluxio/util/ConfigurationUtils.java]: I guess I also don't fully understand what `GrpcUtils.contains` actually does

File: core/common/src/main/java/alluxio/util/ConfigurationUtils.java [hunk 17]
```diff
@@ -531,26 +533,28 @@ private static Properties loadClientProperties(List<ConfigProperty> properties,
   }
 
   /**
-   * Loads the cluster level configuration from the get configuration response, and merges it with
-   * the existing configuration.
+   * Loads the cluster level configuration from the get configuration response,
+   * filters out the configuration for certain scope,
```
Comment (ZacBlanco) [inline core/common/src/main/java/alluxio/util/ConfigurationUtils.java]: nit: is there a reason to line break on the commas?

File: core/common/src/main/java/alluxio/util/ConfigurationUtils.java (hunk 16 above)
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/util/ConfigurationUtils.java]: I tested this function, if given scope == CLIENT,
Scope == CLIENT & ALL will be propagated to client
if given scope == WORKER, Scope == WORKER/SERVER/ALL will be propagated to worker.

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 8 above)
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: Oh, that's possible, then this property should not be propagated to client or worker. Will change it to None

File: core/common/src/main/java/alluxio/util/ConfigurationUtils.java (hunk 16 above)
Comment (ZacBlanco) [reply core/common/src/main/java/alluxio/util/ConfigurationUtils.java]: got it. thanks!

File: core/common/src/main/java/alluxio/util/ConfigurationUtils.java (hunk 17 above)
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/util/ConfigurationUtils.java]: Changed to no break, thanks

**Comment by LuQQiu** [comment]
alluxio.multi.process.MultiProcessClusterTest

**Comment by LuQQiu** [comment]
Jenkins, test this please

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 8 above)
Comment (LuQQiu) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: The test failed because of they check VERSION on the client side, if it's different from the current one, this property will be removed and not merged into client/worker configuration.
I changed the Scope back to ALL

Comment (ZacBlanco) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: oh :(

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please
