### PR TITLE
Fix failures reading data from HDFS files when HDFS EC is enabled

### LINKED ISSUE #13532: Failed to read data from HDFS files when HDFS EC is enabled
**Alluxio Version:**
2.3.0, 2.4.0, 2.5.0-1

**Describe the bug**
the ufs is HDFS and EC(Erasure Coding) is enabled, alluxio can't read data from hdfs when the erasure coding policy is specified on the files.

exec hdfs cli command to get file ec policy:
```
$ /opt/hadoop/bin/hdfs ec -getPolicy -path /data/bl_user_dot_event_detail/partition_date=20190922/partition_category=origin/partition_event_type=task/partition_hour=04/40026_sink12.1569096007179
RS-6-3-1024k
```

exec alluxio cli command:
`$ bin/alluxio fs load /data/bl_user_dot_event_detail/partition_date=20190922/partition_category=origin/partition_event_type=task/partition_hour=04/40026_sink12.1569096007179`

The following is the error message：
```
2021-06-02 16:38:16,894 WARN  BlockReadHandler - Exception occurred while reading data for read request BlockReadRequest{chunkSize=4194304, end=225236, id=50331648, openUfsBlockOptions=ufs_path: "hdfs://nameservice7/data/bl_user_dot_event_detail/partition_date=20190922/partition_category=origin/partition_event_type=task/partition_hour=04/40026_sink12.1569096007179"
offset_in_file: 0
block_size: 225236
maxUfsReadConcurrency: 2147483647
mountId: 5896816853474834940
no_cache: false
, promote=false, sessionId=171306311215806424, start=0, positionShort=false}. session 171306311215806424: alluxio.exception.status.UnavailableException: Failed to read block ID=50331648 from tiered storage and UFS tier: java.io.IOException: Failed to read from UFS, sessionId=171306311215806424, blockId=50331648, offset=0, positionShort=false, options=ufs_path: "hdfs://nameservice7/data/bl_user_dot_event_detail/partition_date=20190922/partition_category=origin/partition_event_type=task/partition_hour=04/40026_sink12.1569096007179"
offset_in_file: 0
block_size: 225236
maxUfsReadConcurrency: 2147483647
mountId: 5896816853474834940
no_cache: false
: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Fail to create raw erasure decoder with given codec: rs
```

**To Reproduce**
use alluxio load command to read HDFS EC files

### PR DESCRIPTION
**Pull request by BUPTAnderson**
Fix #13532 (Failed to read data from HDFS files when HDFS EC is enabled)

  When alluxio use HDFS client to read EC files, the client will use the ContextClassLoader to initialize CodecRegistry which will load RawErasureCoderFactory. The ClassLoader of HDFS Configuration should be the same with CodecRegistry, otherwise we will get the error java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.io.erasurecode.CodecRegistry.

### CODE REVIEW

**Comment by BUPTAnderson** [comment]
@yuzhu Hi David, please review.

File: underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java [hunk 1]
```diff
@@ -148,6 +152,9 @@ public HdfsUnderFileSystem(AlluxioURI ufsUri, UnderFileSystemConfiguration conf,
       // Set Hadoop UGI configuration to ensure UGI can be initialized by the shaded classes for
       // group service.
       UserGroupInformation.setConfiguration(hdfsConf);
+      Class.forName(HDFS_EC_CODEC_REGISTRY_CLASS);
```
Comment (apc999) [inline underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java:155]: is it better to check `alluxio.UfsConstants.UFS_HADOOP_VERSION` here and only class load if the major version is 3.0 or later?

also this should be in its own separate try - catch block, which is best effort. 
I have seen `UserGroupInformation.setConfiguration(hdfsConf);` throw this `ClassNotFoundException` before

```java
try {
  ...
  try {
    Class.forName(HDFS_EC_CODEC_REGISTRY_CLASS);
  } catch (ClassNotFoundException e) {
    LOG.warn("Cannot initialize HDFS EC CodecRegistry. HDFS EC will not be supported.");
  }
}
```

File: underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java [hunk 2]
```diff
@@ -148,6 +152,9 @@ public HdfsUnderFileSystem(AlluxioURI ufsUri, UnderFileSystemConfiguration conf,
...
+    } catch (ClassNotFoundException e) {
+      LOG.warn("Cannot initialize HDFS EC CodecRegistry. HDFS EC will not be supported.");
```
Comment (apc999) [inline underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java:157]: also log class name `HDFS_EC_CODEC_REGISTRY_CLASS` here?

File: underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java (hunk 1 above)
Comment (BUPTAnderson) [reply underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java]: Hi Bin, thanks for your comment, I have made changes according to your suggestions. please review again.

**Review by apc999 — APPROVED** [review]
Thanks for the improvement!

**Comment by apc999** [comment]
alluxio-bot, merge this please
