### PR TITLE
Remove loadMetadata client RPC

### LINKED ISSUE #8381: Remove loadMetadata from Alluxio Client API
**Alluxio Version:** 1.8.1

**Describe the bug**

`loadMetadata` in `FileSystem.java` is deprecated and should be removed for 2.0

**To Reproduce**
N/A

**Expected behavior**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by ZacBlanco**
- LoadMetadataPOptions are still required because the
DefaultFileSystemMaster still uses them to create
LoadMetadataContext objects on calls to syncMetadata

Fixes #8381

### CODE REVIEW

File: core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java [hunk 1]
```diff
@@ -2382,44 +2382,27 @@ public UfsInfo getUfsInfo(long mountId) {
...
+   * @throws FileDoesNotExistException if there is no UFS path
+   * @throws InvalidFileSizeException if invalid file size is encountered
+   * @throws InvalidPathException if invalid path is encountered
    */
   private void loadMetadataInternal(RpcContext rpcContext, LockedInodePath inodePath,
       LoadMetadataContext context)
-      throws InvalidPathException, FileDoesNotExistException, BlockInfoException,
-      FileAlreadyCompletedException, InvalidFileSizeException, AccessControlException, IOException {
+      throws AccessControlException, BlockInfoException, FileAlreadyCompletedException,
+      FileDoesNotExistException, InvalidFileSizeException, InvalidPathException, IOException {
```
Comment (calvinjia) [inline core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java]: Does it make sense to keep the internal method?

Comment (ZacBlanco) [reply core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java]: What I found is that the `loadMetadataInternal` method is actually used in multiple places outside of being called from the Alluxio client. It is called other places depending on other RPCs' `LoadMetadataType` and `LoadMetadataInterval`.

i.e.

- `syncMetadataInternal` calls `loadMetadataInternal`
- `loadMetadataIfNotExist` calls `loadMetadataInternal`.
  - `getFileId` calls `loadMetadataIfNotExist`
  - `getFileInfo` calls `loadMetadataIfNotExist`
  - `listStatus` calls `loadMetadataIfNotExist`

I think the amount of usage warrants that we keep it.

Comment (calvinjia) [reply core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java]: The drawback is what you mentioned above, having to keep `LoadMetadataPOptions`. Would we be able to refactor this such that the core logic can be reused but took inputs based on the other options from the appropriate callers?

Comment (ZacBlanco) [reply core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java]: Well the original deprecation was simply the explicit `loadMetadata` method in the client. The current behavior to loading metadata from a UFS by setting `LoadMetadataType` and `LoadMetadataInterval` has not been deprecated/there hasn't been any discussion about changing the behavior. This is regarding when users utilize `ONCE`, `NEVER`, and `ALWAYS`. I think changes to that behavior would be out of scope for this PR.

Comment (calvinjia) [reply core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java]: Currently we have a `*Context` and `*POptions` which maps 1-to-1 with RPCs. With this change, we no longer have the `loadMetadata` RPC but still have the `loadMetadataContext` and the associated `LoadMetadataPOptions` (this should be unnecessary since we do not need to send it over the wire even). My question is if we can remove the context and options by refactoring the code such that the callers of `LoadMetadataInternal` can incorporate the options into their own respective options or the common options.

Comment (ZacBlanco) [reply core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java]: So looking again - I do like having 1-to-1 RPC to proto mappings. However, I guess what I'm seeing now is that if we remove the `LoadMetadataPOptions` - then we still need some object which is able to hold all the options that currently exist within it. It would basically just be a hand-written version of the current `LoadMetadataPOptions` - is there a point on using effort to write a class which basically already exists?

Comment (calvinjia) [reply core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java]: Removing it would only make sense if we could merge the fields in the options into existing options. Let's consider that in the future, I've created: https://github.com/Alluxio/alluxio/issues/8591
