### PR TITLE
Reduce getWorkerInfoList RPCs on client and job servers

### LINKED ISSUE #10959: GetWorkerInfoList is not cached when enabling metadata cache
**Alluxio Version:**
2.1.1

**Describe the bug**

Run alluxio-fuse with metadata cache

1.Enable metadata cache

```
alluxio getConf |grep metadata.cache
alluxio.user.metadata.cache.enabled=true
alluxio.user.metadata.cache.expiration.time=2day
alluxio.user.metadata.cache.max.size=1000000
```

2. Load the data

```
time alluxio fs distributedLoad --replication=1 /
```

3. Enable the debug of master service handler

```
alluxio logLevel --logName=alluxio.master.block.BlockMasterClientServiceHandler --target master --level=DEBUG
iZuf60ig21389wrykbcmrzZ:19999[master]LogInfo{DEBUG, alluxio.master.block.BlockMasterClientServiceHandler, Setting Level to DEBUG}
```

4. read the file three times:

```
[root@iZuf60ig21389wrykbcmrzZ train]# cat /alluxio-fuse/train/train-00683-of-01024 > /dev/null
[root@iZuf60ig21389wrykbcmrzZ train]# cat /alluxio-fuse/train/train-00683-of-01024 > /dev/null
[root@iZuf60ig21389wrykbcmrzZ train]# cat /alluxio-fuse/train/train-00683-of-01024 > /dev/null
```

5. And check the logs of alluxio-master

```
2020-02-20 15:28:16,575 DEBUG BlockMasterClientServiceHandler - Enter: GetWorkerInfoList: options=
2020-02-20 15:28:16,576 DEBUG BlockMasterClientServiceHandler - Exit: GetWorkerInfoList: options=
2020-02-20 15:28:16,713 DEBUG BlockMasterClientServiceHandler - Enter: GetWorkerInfoList: options=
2020-02-20 15:28:16,713 DEBUG BlockMasterClientServiceHandler - Exit: GetWorkerInfoList: options=
2020-02-20 15:28:21,941 DEBUG BlockMasterClientServiceHandler - Enter: GetWorkerInfoList: options=
2020-02-20 15:28:21,941 DEBUG BlockMasterClientServiceHandler - Exit: GetWorkerInfoList: options=
2020-02-20 15:28:22,022 DEBUG BlockMasterClientServiceHandler - Enter: GetWorkerInfoList: options=
2020-02-20 15:28:22,022 DEBUG BlockMasterClientServiceHandler - Exit: GetWorkerInfoList: options=
2020-02-20 15:28:23,738 DEBUG BlockMasterClientServiceHandler - Enter: GetWorkerInfoList: options=
2020-02-20 15:28:23,738 DEBUG BlockMasterClientServiceHandler - Exit: GetWorkerInfoList: options=
2020-02-20 15:28:23,798 DEBUG BlockMasterClientServiceHandler - Enter: GetWorkerInfoList: options=
2020-02-20 15:28:23,798 DEBUG BlockMasterClientServiceHandler - Exit: GetWorkerInfoList: options=
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

### PR DESCRIPTION
**Pull request by apc999**
`AlluxioBlockStore` was originally a singleton before 2.0, so `AlluxioBlockStore.getWorkerInfoList` can keep worker info cached across Input and Output Streams. However after 2.0, `AlluxioBlockStore` becomes instance class and the cached worker info list can only benefit its owner stream, causing performance issues due to too many unnecessary client-master RPCs when reading / writing many small files, as described https://github.com/Alluxio/alluxio/issues/10959

This PR moves `getWorkerInfoList` and `getAllWorkers` to `FileSystemContext` as the shared state.

This PR also changes the job servers to use cached worker info list instead of keep getting the most updated worker info list.

Fix #10959  and close #9977

### CODE REVIEW

**Comment by gpang** [comment]
`alluxio.client.block.AlluxioBlockStoreTest` is failing?

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java [hunk 1]
```diff
@@ -149,6 +154,14 @@
   /** Whether to do URI scheme validation for file systems using this context.  */
   private boolean mUriValidationEnabled = true;
 
+  /** Cached map for workers. */
+  @GuardedBy("this")
+  private volatile List<BlockWorkerInfo> mWorkerInfoList = null;
```
Comment (gpang) [inline core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java]: Should we just use the guava cache, like here: https://github.com/Alluxio/alluxio/pull/10963/files#diff-2d2ca0120802269babf6451df30b6279R273

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java [hunk 2]
```diff
@@ -562,6 +578,28 @@ public synchronized WorkerNetAddress getLocalWorker() throws IOException {
     return mLocalWorker;
   }
 
+  /**
+   * @return the info of all block workers eligible for reads and writes
+   */
+  public synchronized List<BlockWorkerInfo> getEligibleWorkers() throws IOException {
```
Comment (gpang) [inline core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java]: It seems like the only difference between this method and `getAllWorkers` is that this one is cached (so maybe stale)? It is not clear from the method names, and or java doc.

File: job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java [hunk 3]
```diff
@@ -181,8 +181,7 @@ private void checkMigrateValid(MigrateConfig config, FileSystem fs) throws Excep
     for (WorkerInfo workerInfo : jobWorkerInfoList) {
       hostnameToWorker.put(workerInfo.getAddress().getHost(), workerInfo);
     }
-    List<BlockWorkerInfo> alluxioWorkerInfoList =
-        AlluxioBlockStore.create(context.getFsContext()).getAllWorkers();
+    List<BlockWorkerInfo> alluxioWorkerInfoList = context.getFsContext().getAllWorkers();
```
Comment (LuQQiu) [inline job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java]: Change all the getAllWorkers to getEligibleWorkers?

i tested locally that if all job servers used `getEligibleWorkers()` instead of `getAllWorkers()`, a large amount of `getWorkerInfoList` call will be reduced on the job server side. 

This is because instead of creating a `AlluxioBlockStore` each time when needed, Those context used in job server definitions and job utils internally contain a shared `JobServerContext` which contains a `FileSystemContext`.
This FileSystemContext is shared so that the cached worker info list is shared.

Comment (apc999) [reply job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java]: agree

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java (hunk 1 above)
Comment (apc999) [reply core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java]: Agree. Let's at least keep a TODO. Leave it to @LuQQiu to decide if we want to switch to Guava Cache in this PR

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java (hunk 2 above)
Comment (apc999) [reply core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java]: Agree. I would rename this to `getCachedWorkers`

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java (hunk 1 above)
Comment (LuQQiu) [reply core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java]: @gpang I am not quite familiar of guava cache, but according to my understanding, if I define `refreshAfterWrite(interval)`, it will refresh periodically no matter the value is being get or not. This makes sense on the leading master side since we want the cached worker info list up to date enough.

However, on the client-side, a client may need worker info list for some period of time and no need it anymore. Using loadingcache and refresh periodically may introduce unneeded RPC call to the leading master.

**Comment by LuQQiu** [comment]
@gpang PTAL, I changed all the places that use direct getWorkerInfoList call to use the one with cache. Thanks

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java [hunk 4]
```diff
@@ -562,6 +578,28 @@ public synchronized WorkerNetAddress getLocalWorker() throws IOException {
     return mLocalWorker;
   }
 
+  /**
+   * @return the info of all block workers eligible for reads and writes
```
Comment (apc999) [inline core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java]: can you mention in javadoc the list of workers will be cached based on the expiration policy?

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java [hunk 5]
```diff
@@ -562,6 +578,28 @@ public synchronized WorkerNetAddress getLocalWorker() throws IOException {
...
+   */
+  public synchronized List<BlockWorkerInfo> getCachedWorkers() throws IOException {
+    if (mWorkerInfoList == null || mWorkerRefreshPolicy.attempt()) {
+      mWorkerInfoList = getAllWorkers();
+    }
+    return mWorkerInfoList;
+  }
+
+  /**
+   * @return the info of all block workers
```
Comment (apc999) [inline core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java]: can you indicate that this method is more expensive than `getCachedWorkers`?

**Comment by apc999** [comment]
two minor comments on Javadoc are left. Otherwise, LGTM

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java (hunk 4 above)
Comment (LuQQiu) [reply core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java]: Added! thanks

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java (hunk 5 above)
Comment (LuQQiu) [reply core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java]: Added thanks

**Comment by LuQQiu** [comment]
Jenkins, test this please

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please

**Comment by LuQQiu** [comment]
alluxio-bot, cherry-pick this to branch-2.2 please
