### PR TITLE
Fix client side leak caused by Gauge

### LINKED ISSUE #14766: MetricsSystem memory leak
**Alluxio Version:**
2.8.0-SNAPSHOT

**Describe the bug**
We add alluxio jar in hivemetastore classpath.
Hivemetastore crash down ,when we query hive through alluxio.

image

image

image
Host-1`G1 Old Gen` is normal, another host `G1 Old Gen` is abnormal .

### PR DESCRIPTION
**Pull request by jiacheliu3**
### What changes are proposed in this pull request?

Fixes #14766

This change replaces two client side gauges with counters.

### Why are the changes needed?

image
On the bottom right corner, it can be seen that the references of EpollGroup are from the metric Gauge lambda in `DynamicResourcePool`. Using `() -> size()` in lambda will implicitly leak the `this` reference or the `mResources` reference used in `size()`(Not sure if JVM just inlined that `size()`).

In my environment, the HMS can spend 40% heap on metrics due to this gauge.
Screen Shot 2022-04-13 at 5 13 18 PM

In one user environment, the HMS can spend 50G on such metrics.

### Does this PR introduce any user facing changes?

The metric to monitor will change

### CODE REVIEW

File: core/common/src/main/java/alluxio/resource/DynamicResourcePool.java [hunk 1]
```diff
@@ -275,15 +277,9 @@ public DynamicResourcePool(Options options) {
...
       }
     }, options.getInitialDelayMs(), options.getGcIntervalMs(), TimeUnit.MILLISECONDS);
-
-    registerGauges();
   }
 
-  private void registerGauges() {
-    MetricsSystem.registerGaugeIfAbsent(
-        MetricsSystem.getResourcePoolMetricName(this),
-        () -> size());
```
Comment (jiacheliu3) [inline core/common/src/main/java/alluxio/resource/DynamicResourcePool.java:285]: This leaks a `mResources` reference and that reference leads to the references of all resources. Consequently all references that our Clients point to are left alive and not GC-ed.

File: core/common/src/main/java/alluxio/resource/DynamicResourcePool.java [hunk 2]
```diff
@@ -436,6 +432,7 @@ private boolean add(ResourceInternal<T> resource) {
         return false;
       } else {
         mResources.put(resource.mResource, resource);
+        mCounter.inc();
```
Comment (jiacheliu3) [inline core/common/src/main/java/alluxio/resource/DynamicResourcePool.java:435]: These inc and dec lead to paranoia regarding performance, I admit. But I think compared to the cost of making and closing connections within the client, updating a counter should be relatively fine. Also the pooling will make such updates less frequent than it looks on 1st sight.

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java [hunk 3]
```diff
@@ -278,17 +273,6 @@ private synchronized void initContext(ClientContext ctx,
...
-    MetricsSystem.registerGaugeIfAbsent(TOTAL_RPC_CLIENTS_METRICS_NAME,
-       new CachedGauge<Integer>(1, TimeUnit.MINUTES) {
-          @Override
-          protected Integer loadValue() {
-            int totalClients = mFileSystemMasterClientPool.size() + mBlockMasterClientPool.size();
-            totalClients += mBlockWorkerClientPoolMap.values()
-                .stream().mapToInt(DynamicResourcePool::size).sum();
-            return totalClients;
-          }
-        });
```
Comment (jiacheliu3) [inline core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java:291]: Although I didn't directly find the leak in the customer environment from here, I suspect this one also leaks references to the pool. @dbw9580 do you know if using a lambda will leak refs but using anonymous inner class like this is fine? 

Regardless of the leak concerns, I'm not sure the metric is correct here. Is it true that one Alluxio Client will have only one FileSystemContext? If a client has multiple FileSystemContext instances, would the gauge be incorrect?

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java [hunk 4]
```diff
@@ -313,7 +297,6 @@ private synchronized void closeContext() throws IOException {
       // developers should first mark their resources as closed prior to any exceptions being
       // thrown.
       mClosed.set(true);
-      MetricsSystem.removeMetrics(TOTAL_RPC_CLIENTS_METRICS_NAME);
```
Comment (jiacheliu3) [inline core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java:316]: Removing is a good practice. But for some long running clients like HMS, I'm not sure if the FileSystemContext will be closed at all.

File: core/common/src/main/java/alluxio/metrics/MetricKey.java [hunk 5]
```diff
@@ -1904,15 +1904,6 @@ public MetricKey build() {
...
           .build();
-  public static final MetricKey CLIENT_TOTAL_RPC_CLIENTS =
-      new Builder("Client.TotalRPCClients")
-          .setDescription("The total number of RPC clients exist that is using to "
-              + "or can be used to connect to master or worker for operations. "
-              + "The sum of the sizes of FileSystemMasterClientPool, "
-              + "BlockMasterClientPool, and BlockWorkerClientPool.")
-          .setMetricType(MetricType.COUNTER)
-          .setIsClusterAggregated(false)
-          .build();
```
Comment (jiacheliu3) [inline core/common/src/main/java/alluxio/metrics/MetricKey.java:1915]: This one can now be summed from the 3 new metrics. If we do need one syntactic sugar gauge, we can sum the other 3 counters in this gauge, instead of leaving references to peek the pool sizes at all.

File: core/common/src/main/java/alluxio/resource/DynamicResourcePool.java (hunk 1 above)
Comment (yuzhu) [reply core/common/src/main/java/alluxio/resource/DynamicResourcePool.java:285]: still not sure why a reference to `mResources` would cause the leak here, since the reference exist in the object pool class anyways? Have we verified that this change fixes the memory issue seen earlier? was it because of this line or the change in MetricSystem.java?

Comment (jiacheliu3) [reply core/common/src/main/java/alluxio/resource/DynamicResourcePool.java:285]: image
This is the ref chain. `() -> size()` effectively gives out `mResources.size()` which gives out `mResources`. After removing this gauge I no longer see the large memory consumption from `ConcurrentHashMap$Node` from the metrics registry. 

Bowen sent me this link earlier and seems to explain
https://blog.jooq.org/beware-of-functional-programming-in-java/

Comment (jiacheliu3) [reply core/common/src/main/java/alluxio/resource/DynamicResourcePool.java:285]: I guess we can also say my current implementation is not the only possible fix, there are indeed other options:

1. By pooling, it is not easy to get rid of references to the things you pool. But maybe WeakReference can break the reference chain.

2. Indeed creating metrics per `FileSystemContext` with `DynamicResourcePool.registerGauges()` is too much excessive. And we are not de-registering those gauges. But I'm not even sure if HMS is caching FileSystemContext instances. Many compute engines may do that too, like Impala. I have not tested if only decreasing number of gauges will avoid the leak. However the thing is, if a client app has many `FileSystemContext`, what should a global gauge do(instead of being a counter)?

3. Maybe the reference chain can be broken at the client-connection step. But I haven't given it much thought.

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java (hunk 3 above)
Comment (dbw9580) [reply core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java:291]: > using anonymous inner class like this is fine?

No. Inner classes capture a reference to the enclosing class even the reference is not used. 

ref: https://stackoverflow.com/a/8590414

**Review by yuzhu — APPROVED** [review]
LGTM, thanks for catching this!

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by jiacheliu3** [comment]
@Xenorith could you help cherry picking this? Thx

**Comment by Xenorith** [comment]
alluxio-bot, cherry-pick this to branch-2.8 please
