### PR TITLE
Fix regression in AbsentUfsPathCache

### LINKED ISSUE #12833: AbsentUfsPathCache is not respected on getStatus and listStatus calls
**Alluxio Version:**
2.5.0-SNAPSHOT-9833d5f0841ef03fc9bb572fe4dccdd73bb98175

**Describe the bug**
when using spark write to alluxio,commit file takes a long time.
And we have alreay use the following config:
```
config("spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version","2")
alluxio.user.file.writetype.default: "MUST_CACHE"
```
we use the following code to write to alluxio:
`data_df.write.mode("overwrite").format("tfrecord").option("recordType", "Example").save("alluxio://fluid1-master-0.kf-partition:20009/s3/test/2020-02-05")`
and there are logs:
```
2021-02-10 02:48:18,272 DEBUG UnderFileSystemWithLogging - Exit (Error): GetStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000977_5577, Error=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000977_5577
2021-02-10 02:48:18,272 WARN  UfsStatusCache - Failed to fetch status for /s3/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000977_5577: java.io.FileNotFoundException: s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000977_5577
2021-02-10 02:48:19,025 WARN  ObjectUnderFileSystem - Error fetching directory status, assuming directory s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000970_5570 does not exist
2021-02-10 02:48:19,026 DEBUG UnderFileSystemWithLogging - Exit (Error): GetStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000970_5570, Error=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000970_5570
2021-02-10 02:48:19,026 WARN  UfsStatusCache - Failed to fetch status for /s3/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000970_5570: java.io.FileNotFoundException: s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000970_5570
2021-02-10 02:48:19,351 WARN  ObjectUnderFileSystem - Error fetching directory status, assuming directory s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000958_5558 does not exist
2021-02-10 02:48:19,352 DEBUG UnderFileSystemWithLogging - Exit (Error): GetStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000958_5558, Error=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000958_5558
2021-02-10 02:48:19,352 WARN  UfsStatusCache - Failed to fetch status for /s3/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000958_5558: java.io.FileNotFoundException: s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000958_5558
2021-02-10 02:48:19,583 WARN  ObjectUnderFileSystem - Error fetching directory status, assuming directory s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000981_5581 does not exist
2021-02-10 02:48:19,583 DEBUG UnderFileSystemWithLogging - Exit (Error): GetStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000981_5581, Error=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000981_5581
2021-02-10 02:48:19,583 WARN  UfsStatusCache - Failed to fetch status for /s3/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000981_5581: java.io.FileNotFoundException: s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000981_5581
2021-02-10 02:48:20,478 WARN  ObjectUnderFileSystem - Error fetching directory status, assuming directory s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000965_5565 does not exist
2021-02-10 02:48:20,479 DEBUG UnderFileSystemWithLogging - Exit (Error): GetStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000965_5565, Error=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000965_5565
2021-02-10 02:48:20,479 WARN  UfsStatusCache - Failed to fetch status for /s3/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000965_5565: java.io.FileNotFoundException: s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000965_5565
2021-02-10 02:48:20,528 DEBUG UnderFileSystemWithLogging - Exit (OK): ListStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000983_5583
2021-02-10 02:48:20,528 DEBUG UnderFileSystemWithLogging - Enter: GetStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000983_5583
2021-02-10 02:48:20,576 DEBUG UnderFileSystemWithLogging - Exit (OK): ListStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000985_5585
2021-02-10 02:48:20,576 DEBUG UnderFileSystemWithLogging - Enter: GetStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000985_5585
2021-02-10 02:48:20,639 WARN  ObjectUnderFileSystem - Error fetching directory status, assuming directory s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000973_5573 does not exist
2021-02-10 02:48:20,639 DEBUG UnderFileSystemWithLogging - Exit (Error): GetStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000973_5573, Error=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000973_5573
2021-02-10 02:48:20,639 WARN  UfsStatusCache - Failed to fetch status for /s3/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000973_5573: java.io.FileNotFoundException: s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000973_5573
2021-02-10 02:48:20,674 DEBUG UnderFileSystemWithLogging - Exit (OK): ListStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000987_5587
2021-02-10 02:48:20,674 DEBUG UnderFileSystemWithLogging - Enter: GetStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000987_5587
2021-02-10 02:48:20,675 DEBUG UnderFileSystemWithLogging - Exit (OK): ListStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000991_5591
2021-02-10 02:48:20,675 DEBUG UnderFileSystemWithLogging - Enter: GetStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000991_5591
2021-02-10 02:48:20,889 DEBUG UnderFileSystemWithLogging - Exit (OK): ListStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000990_5590
2021-02-10 02:48:20,889 DEBUG UnderFileSystemWithLogging - Enter: GetStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000990_5590
2021-02-10 02:48:20,890 WARN  ObjectUnderFileSystem - Error fetching directory status, assuming directory s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000954_5554 does not exist
2021-02-10 02:48:20,890 DEBUG UnderFileSystemWithLogging - Exit (Error): GetStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000954_5554, Error=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000954_5554
2021-02-10 02:48:20,890 WARN  UfsStatusCache - Failed to fetch status for /s3/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000954_5554: java.io.FileNotFoundException: s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000954_5554
2021-02-10 02:48:20,894 DEBUG UnderFileSystemWithLogging - Exit (OK): ListStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000989_5589
2021-02-10 02:48:20,894 DEBUG UnderFileSystemWithLogging - Enter: GetStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000989_5589
2021-02-10 02:48:21,122 WARN  ObjectUnderFileSystem - Error fetching directory status, assuming directory s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000982_5582 does not exist
2021-02-10 02:48:21,123 DEBUG UnderFileSystemWithLogging - Exit (Error): GetStatus: path=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000982_5582, Error=s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000982_5582
2021-02-10 02:48:21,123 WARN  UfsStatusCache - Failed to fetch status for /s3/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000982_5582: java.io.FileNotFoundException: s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000982_5582
2021-02-10 02:48:21,701 DEBUG UnderFileSystemWithLogging - Enter: GetSpace: path=/underFSStorage, type=SPACE_USED
2021-02-10 02:48:21,701 DEBUG UnderFileSystemWithLogging - Exit (OK): GetSpace: path=/underFSStorage, type=SPACE_USED
2021-02-10 02:48:21,702 DEBUG UnderFileSystemWithLogging - Enter: GetSpace: path=/underFSStorage, type=SPACE_FREE
2021-02-10 02:48:21,702 DEBUG UnderFileSystemWithLogging - Exit (OK): GetSpace: path=/underFSStorage, type=SPACE_FREE
2021-02-10 02:48:21,702 DEBUG UnderFileSystemWithLogging - Enter: GetSpace: path=/underFSStorage, type=SPACE_TOTAL
2021-02-10 02:48:21,702 DEBUG UnderFileSystemWithLogging - Exit (OK): GetSpace: path=/underFSStorage, type=SPACE_TOTAL
2021-02-10 02:48:22,171 WARN  ObjectUnderFileSystem - Error fetching directory status, assuming directory s3://fluid/test/2020-02-05/_temporary/0/_temporary/attempt_20210210023417_0005_m_000971_5571 does not exist
```
**Urgency**
Writing  efficiency is greatly affected and this  blocks the launch of alluxio in our company

Attached master logs for a new run:

[fluid1-master-0-alluxio-master.log](https://github.com/Alluxio/alluxio/files/6065014/fluid1-master-0-alluxio-master.log)

### PR DESCRIPTION
**Pull request by apc999**
Add a time stamp to indicate last refreshed time on the absent cache entries. 
Use absent cache to avoid UFS accesses when possible in the metadata sync and load Metadata processes. 

Added more comprehensive integration tests that ensures the number of accesses to the UFS through SleepingUnderFileSystem and unit tests for the absent cache. 

fixes #12833 because now instead of checking /a, /a/b, /a/b/c for non existent directories, we will only access the UFS once for /a because of absent cache. We know /a/b, /a/b/c can not exist on the UFS. 

Co-authored-by: David Zhu <david@alluxio.com>

### CODE REVIEW

File: core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java [hunk 1]
```diff
@@ -495,8 +495,8 @@ public UfsDirectoryStatus getDirectoryStatus(String path) throws IOException {
       return new UfsDirectoryStatus(path, permissions.getOwner(), permissions.getGroup(),
           permissions.getMode());
     }
-    LOG.warn("Error fetching directory status, assuming directory {} does not exist", path);
```
Comment (apc999) [inline core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java:498]: noisy message. Non-existence is often expected

File: core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java [hunk 2]
```diff
@@ -537,8 +537,8 @@ public UfsFileStatus getFileStatus(String path) throws IOException {
           details.getLastModifiedTimeMs(), permissions.getOwner(), permissions.getGroup(),
           permissions.getMode(), mUfsConf.getBytes(PropertyKey.USER_BLOCK_SIZE_BYTES_DEFAULT));
     } else {
-      LOG.warn("Error fetching file status, assuming file {} does not exist", path);
```
Comment (apc999) [inline core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java:540]: noisy message. Non-existence is often expected. Changed it to DEBUG level

File: core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java [hunk 3]
```diff
@@ -495,8 +495,8 @@ public UfsDirectoryStatus getDirectoryStatus(String path) throws IOException {
       return new UfsDirectoryStatus(path, permissions.getOwner(), permissions.getGroup(),
           permissions.getMode());
     }
-    LOG.warn("Error fetching directory status, assuming directory {} does not exist", path);
-    throw new FileNotFoundException(path);
```
Comment (apc999) [inline core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java:499]: Bad idea to through exception with only path. the error message eventually looks confusing, like this:

```
2021-02-10 02:34:30,893 DEBUG UnderFileSystemWithLogging - Exit (Error): GetStatus: path=s3://fluid/test/2020-02-05, Error=s3://fluid/test/2020-02-05
```

File: core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java [hunk 4]
```diff
@@ -3378,16 +3389,6 @@ public boolean recordActiveSyncTxid(long txId, long mountId) {
     return true;
   }
 
-  private boolean syncMetadata(RpcContext rpcContext, AlluxioURI path,
```
Comment (apc999) [inline core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java:3381]: this overloading method is not helping much. Consolidating two `syncMetadata` methods so it is very clear to see all methods exercise this code path, easier to reason

File: core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java [hunk 5]
```diff
@@ -85,7 +86,7 @@ public AsyncUfsAbsentPathCache(MountTable mountTable, int numThreads) {
 
   @Override
   public void process(AlluxioURI path, List<Inode> prefixInodes) {
-    mPool.submit(new ProcessPathTask(path, prefixInodes));
+    mPool.submit(() -> processPathSync(path, prefixInodes));
```
Comment (apc999) [inline core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java:89]: thanks to Java 8

**Comment by yuzhu** [comment]
Error: 0.071 [ERROR]   Run 2: FileSystemMasterIntegrationTest.createFileInvalidPath 
Expected: an instance of alluxio.exception.InvalidPathException
     but: <org.junit.runners.model.TestTimedOutException: test timed out after 60 seconds> is a org.junit.runners.model.TestTimedOutException
Stacktrace was: org.junit.runners.model.TestTimedOutException: test timed out after 60 seconds
	at alluxio.uri.StandardURI.createNewPath(StandardURI.java:88)
	at alluxio.uri.URI$Factory.create(URI.java:183)
	at alluxio.AlluxioURI.<init>(AlluxioURI.java:124)
	at alluxio.AlluxioURI.getParent(AlluxioURI.java:263)
	at alluxio.master.file.meta.AsyncUfsAbsentPathCache.isAbsent(AsyncUfsAbsentPathCache.java:126)
	at alluxio.master.file.DefaultFileSystemMaster.syncMetadata(DefaultFileSystemMaster.java:3416)
	at alluxio.master.file.DefaultFileSystemMaster.createFile(DefaultFileSystemMaster.java:1525)
	at alluxio.client.fs.FileSystemMasterIntegrationTest.createFileInvalidPath(FileSystemMasterIntegrationTest.java:302)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

File: core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java [hunk 6]
```diff
@@ -3412,7 +3413,7 @@ private boolean syncMetadata(RpcContext rpcContext, AlluxioURI path,
       boolean isGetFileInfo) throws AccessControlException, InvalidPathException {
     LockingScheme syncScheme = createSyncLockingScheme(path, options, isGetFileInfo);
 
-    if (!syncScheme.shouldSync()) {
+    if (mUfsAbsentPathCache.isAbsent(path) || !syncScheme.shouldSync()) {
```
Comment (yuzhu) [inline core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java:3416]: If a particular path got added to the absentPathCache and later that path is created out of band directly on the UFS, how do we discover that if we completely skip the sync?

Comment (yuzhu) [reply core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java:3416]: I think it will get processed and removed from the cache during the same ListStatus or GetStatus call but it happens too late in the process for the same call to return the right results.

**Review by yuzhu — CHANGES_REQUESTED** [review]
@apc999 a question about whether invalidation happens soon enough for the getStatus or listStatus to pick up the result. Also  do you mind adding an integration test where out of band writes to the ufs invalidates a cache entry in the absent cache and see how listStatus behaves in that setting?

File: core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java (hunk 6 above)
Comment (apc999) [reply core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java:3416]: one idea @calvinjia has is to make it similar to the UfsStatusCache and respect sync interval?

**Comment by yuzhu** [comment]
@apc999 @calvinjia PTAL. 
as I mentioned in the issue, I don't think the problem here is our sync is not using the absent cache. sync interval is set to -1 in the issue so sync should not have been triggered anyways. LoadMetadata was triggered, and that uses absent cache. The problem is that sync cache does not differentiate between something not cached and some path that is known to not exist in the UFS. Hence the negative hashset in the status cache.

I may move to use a single negative cache for the entire system in a separate PR, but then it needs to be timestamped with last retrieval time, which may add overhead.

**Comment by calvinjia** [comment]
I think a single negative cache would resolve the issue, just need to make sure we still respect sync interval. Though I can see a case where if the sync interval is set to a low value, we might still end up doing a lot of wasted calls. Ideally when we check a directory it also updates the absence time or equivalent so a call on /foo will stop UFS operations for /foo/bar1 in the sync interval.

File: core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java [hunk 7]
```diff
@@ -121,6 +122,15 @@
  *
  */
 public class InodeSyncStream {
+  /**
+   * Return status of a sync result.
+   */
+  public enum SyncStatus {
+    SYNC_SUCCESS,
+    SYNC_FAILED,
+    DO_NOT_NEED_SYNC
```
Comment (apc999) [inline core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java:131]: how about:
```suggestion
    OK,
    FAILED,
    UNNECESSARY
```

File: tests/src/test/java/alluxio/client/fs/LoadMetadataIntegrationTest.java [hunk 8]
```diff
@@ -101,63 +102,95 @@ public void after() throws Exception {
...
+  public void absentCache() throws Exception {
+    GetStatusPOptions options =
+        GetStatusPOptions.newBuilder().setLoadMetadataType(LoadMetadataPType.ONCE)
+            .setCommonOptions(FileSystemMasterCommonPOptions.newBuilder().setSyncIntervalMs(-1)
+        ).build();
+    checkGetStatus("/mnt/dir1/dirA/dirDNE/", options, false, 1);
+    checkGetStatus("/mnt/dir1/dirA/fileDNE1", options, false, 1);
+    checkGetStatus("/mnt/dir1/dirA/dirDNE/", options, false, 0);
+    checkGetStatus("/mnt/dir1/dirA/fileDNE1", options, false, 0);
+    checkGetStatus("/mnt/dir1/dirA/dirDNE/fileDNE", options, false, 0);
```
Comment (apc999) [inline tests/src/test/java/alluxio/client/fs/LoadMetadataIntegrationTest.java:128]: can you add

`checkGetStatus("/mnt/dir1/dirA/dirDNE/dirB/fileDNE", options, false, 0);`

**Comment by apc999** [comment]
@yuzhu  is this PR ready to review?

**Comment by yuzhu** [comment]
@apc999 Not yet, I am adding time stamp to the absent cache right now. Should have it ready tomorrow. 
I have reproduced the issue in an integration test. 

The root cause is our negative cache is used to check whether we start the loadMetadata or not, but once we start loadMetadata operation on a directory, we do not recheck the negative cache or update the negative cache again for any subsequent accesses to the UFS.

File: core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java [hunk 9]
```diff
@@ -121,6 +122,15 @@
  *
  */
 public class InodeSyncStream {
+  /**
+   * Return status of a sync result.
+   */
+  public enum SyncStatus {
```
Comment (gpang) [inline core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java:128]: I don't understand how this is in `InodeSyncStream`, but this file does not use this enum.

File: core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java [hunk 10]
```diff
@@ -647,15 +669,16 @@ private void syncExistingInodeMetadata(LockedInodePath inodePath)
...
       throws InvalidPathException, AccessControlException, IOException, FileDoesNotExistException,
       FileAlreadyCompletedException, InvalidFileSizeException, BlockInfoException {
-
     UfsStatus status = mStatusCache.fetchStatusIfAbsent(inodePath.getUri(), mMountTable);
-    LoadMetadataContext ctx = LoadMetadataContext.mergeFrom(
-        LoadMetadataPOptions.newBuilder()
-            .setCommonOptions(NO_TTL_OPTION)
-            .setCreateAncestors(true)
-            .setLoadDescendantType(GrpcUtils.toProto(mDescendantType)))
-        .setUfsStatus(status);
```
Comment (gpang) [inline core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java:657]: Did this previous code sometimes set it to `null`?

File: core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java [hunk 11]
```diff
@@ -359,6 +359,7 @@ public Resolution resolve(AlluxioURI uri) throws InvalidPathException {
     try (LockResource r = new LockResource(mReadLock)) {
       String path = uri.getPath();
       LOG.debug("Resolving {}", path);
+      PathUtils.validatePath(uri.getPath());
```
Comment (gpang) [inline core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java:362]: Is this change related to the rest?

**Review by gpang — COMMENTED** [review]
Is there an associated issue for this? I don't fully understand the incorrect behavior, and the desired/fixed behavior.

**Comment by yuzhu** [comment]
@gpang #12833 for the issue. basically if we write out a temporary directory in MUST_CACHE mode, and we try to ls -r the directory, it will walk the entire directory and find out that each of the path only exist in alluxio and does not exist in UFS， which is extremely slow.

File: core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java [hunk 12]
```diff
@@ -3402,23 +3406,26 @@ private boolean syncMetadata(RpcContext rpcContext, AlluxioURI path,
...
       @Nullable FileSystemMasterAuditContext auditContext,
       @Nullable Function<LockedInodePath, Inode> auditContextSrcInodeFunc,
       @Nullable PermissionCheckFunction permissionCheckOperation,
       boolean isGetFileInfo) throws AccessControlException, InvalidPathException {
     LockingScheme syncScheme = createSyncLockingScheme(path, options, isGetFileInfo);
-
     if (!syncScheme.shouldSync()) {
-      return false;
+      return NOT_NEEDED;
     }
```
Comment (apc999) [inline core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java:3420]: should we actually put following logic into `sync.sync()`?
```
    if (!syncScheme.shouldSync()) {
      return false;
      return NOT_NEEDED;
    }
```
and make `sync.sync` to return `InodeSyncStream.SyncStatus` instead of boolean?
i saw multiple different locations we call `InodeSyncStream#sync`, it will be good to fix it for all

File: core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java (hunk 9 above)
Comment (apc999) [reply core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java:128]: agree. as proposed above, we can make `#sync` to return this value

**Comment by yuzhu** [comment]
@calvinjia @apc999 @gpang The PR is mostly ready. Over the next few days I will add more integration tests to it. 
The main point of the PR is to add timestamp to the absent cache so that we can use it for sync metadata and load metadata. Therefore avoid the situation where we check /a, /a/b, /a/b/c only to find out all of them do not exist on the UFS. This is common when we have must cache temp directories.

File: core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java [hunk 13]
```diff
@@ -251,20 +278,22 @@ public InodeSyncStream(LockingScheme rootPath, DefaultFileSystemMaster fsMaster,
...
+      boolean isGetFileInfo, boolean forceSync, boolean loadOnly, boolean loadAlways) {
     this(rootScheme, fsMaster, rpcContext, descendantType, options, null, null, null,
-        isGetFileInfo, forceSync, loadOnly);
+        isGetFileInfo, forceSync, loadOnly, loadAlways);
   }
 
   /**
    * Sync the metadata according the the root path the stream was created with.
    *
    * @return true if at least one path was synced
```
Comment (apc999) [inline core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java:294]: nit: update javadoc on returned value?

File: core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java [hunk 14]
```diff
@@ -504,18 +537,29 @@ private void syncExistingInodeMetadata(LockedInodePath inodePath)
       }
       persistingLock.get().close();
 
-      UfsStatus cachedStatus = mStatusCache.getStatus(inodePath.getUri());
+      UfsStatus cachedStatus = null;
+      boolean fileNotFound = false;
+      try {
+        cachedStatus = mStatusCache.getStatus(inodePath.getUri());
+      } catch (FileNotFoundException e) {
```
Comment (apc999) [inline core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java:544]: side question: when does `getStatus` return null and when does it throw `FileNotFoundException`? it is not clear to me. Also, throwing an exception is considered expensive. If it is expected, can we indicate negative result by return value?

File: core/server/master/src/main/java/alluxio/master/file/meta/UfsAbsentPathCache.java [hunk 15]
```diff
@@ -24,14 +24,23 @@
...
+
   /**
    * Processes the given path for the cache. This will sequentially walk down the path to find
    * components which do and do not exist in the UFS, and updates the cache accordingly.
    *
    * @param path the path to process for the cache
    * @param prefixInodes the existing inodes for the path prefix
    */
-  void process(AlluxioURI path, List<Inode> prefixInodes);
+  void processAsync(AlluxioURI path, List<Inode> prefixInodes);
```
Comment (apc999) [inline core/server/master/src/main/java/alluxio/master/file/meta/UfsAbsentPathCache.java:37]: update javadoc so we know it is async?

File: core/server/master/src/main/java/alluxio/master/file/meta/UfsAbsentPathCache.java [hunk 16]
```diff
@@ -42,13 +51,14 @@
   void processExisting(AlluxioURI path);
 
   /**
-   * Returns true if the given path is absent, according to this cache. A path is absent if one of
-   * its ancestors is absent.
+   * Returns true if the given path was found to be absent since timeMs, according to this cache.
+   * A path is absent if one of its ancestors is absent.
    *
    * @param path the path to check
+   * @param timeMs the time when the cache entry would be considered valid
```
Comment (apc999) [inline core/server/master/src/main/java/alluxio/master/file/meta/UfsAbsentPathCache.java:58]: nit: maybe name this arg as `ttl` if I understand it correctly? `timeMs` is too neutral

File: core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java (hunk 4 above)
Comment (calvinjia) [reply core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java:3381]: Do we still plan to do this?

File: core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java [hunk 17]
```diff
@@ -828,16 +830,17 @@ public FileInfo getFileInfo(AlluxioURI path, GetStatusContext context)
         FileSystemMasterAuditContext auditContext =
             createAuditContext("getFileInfo", path, null, null)) {
 
-      if (syncMetadata(rpcContext, path, context.getOptions().getCommonOptions(),
+      if (!syncMetadata(rpcContext, path, context.getOptions().getCommonOptions(),
           DescendantType.ONE, auditContext, LockedInodePath::getInodeOrNull,
           (inodePath, permChecker) -> permChecker.checkPermission(Mode.Bits.READ, inodePath),
-          true)) {
+          true).equals(NOT_NEEDED)) {
```
Comment (calvinjia) [inline core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java:836]: Has this condition been modified? It seems like it would be equivalent to `.equals(OK)`?

File: core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java [hunk 18]
```diff
@@ -58,8 +60,10 @@
   private final MountTable mMountTable;
   /** Paths currently being processed. This is used to prevent duplicate processing. */
   private final ConcurrentHashMap<String, PathLock> mCurrentPaths;
-  /** Cache of paths which are absent in the ufs. */
-  private final Cache<String, Long> mCache;
+  /** Cache of paths which are absent in the ufs, maps an alluxio path to a Pair
+   *  which is the sync time and the mount id.
+   */
+  private final Cache<String, Pair<Long, Long>> mCache;
```
Comment (calvinjia) [inline core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java:66]: Does it make sense to add some metrics for the absent path cache?

**Review by calvinjia — CHANGES_REQUESTED** [review]

File: core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java (hunk 18 above)
Comment (yuzhu) [reply core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java:66]: yes, but maybe in a separate PR?

File: core/server/master/src/main/java/alluxio/master/file/meta/UfsAbsentPathCache.java (hunk 15 above)
Comment (yuzhu) [reply core/server/master/src/main/java/alluxio/master/file/meta/UfsAbsentPathCache.java:38]: done

File: core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java (hunk 17 above)
Comment (yuzhu) [reply core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java:836]: The rationale is that if a sync had failed, loadMetadata would  likely fail in similar fashion since the code path is very similar. So we can save some unnecessary loadMetadata operations?

**Review by yuzhu — COMMENTED** [review]
@apc999 @calvinjia replied to your comments

**Review by apc999 — COMMENTED** [review]
LGTM

**Comment by apc999** [comment]
@calvinjia  can you take a look at this PR?

**Comment by calvinjia** [comment]
I think this is good to go after we add some basic metrics to verify the cache is working. Up to @yuzhu if you want to do it in a separate PR or use this one.

**Comment by yuzhu** [comment]
@calvinjia  let's do it in a separate PR then, since i probably won't get to it today.

**Comment by yuzhu** [comment]
alluxio-bot, merge this please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.5 please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.5 please

**Comment by yuzhu** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please
