### PR TITLE
Clear metrics when closing JournalStateMachine

### LINKED ISSUE #16704: Stale raft journal metrics after leadership change
**Alluxio Version:**

2.9.0-SNAPSHOT (873bcca82e8cc1abb421bbb316bd9ef99b306c16)

**Describe the bug**

After a leadership change, journal entries (which is read from metrics) will get stuck:
before

(The WebUI is with the change in #16636)

In this screenshot, `localhost:19988` lost primacy, and its `Journal Entries` got stuck.

**To Reproduce**

1. Start a HA cluster
2. Use Ratis shell to transfer leadership
3. Perform some operations, to increase journal entries
4. Observe journal entries metrics in each master

**Expected behavior**

The master lost primacy should have its metrics up to date.

**Urgency**

Medium.

**Are you planning to fix it**

Yes.

### PR DESCRIPTION
**Pull request by kaijchen**
### What changes are proposed in this pull request?

Clear metrics when closing JournalStateMachine,
so when a new instance of JournalStateMachine is created, those metrics can be refreshed.

https://github.com/Alluxio/alluxio/blob/bd30e25d7b0103e30dd8de611da250ced85cdf27/core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java#L293-L297

Fix #16704.

### Why are the changes needed?

Fix a bug that after a primacy change, metrics of JournalStateMachine will get stuck.

### Does this PR introduce any user facing changes?

No.

### CODE REVIEW

**Review by maobaolong — APPROVED** [review]
It LGTM, Thanks for this fix.

**Comment by LuQQiu** [comment]
@kaijchen can you help create a github issue and link this PR to the issue? so that we can have more detailed information about why need to do this change

File: core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java [hunk 1]
```diff
@@ -367,6 +367,11 @@ public CompletableFuture<Message> query(Message request) {
   @Override
   public void close() {
     mClosed = true;
+    MetricsSystem.removeMetrics(MetricKey.MASTER_EMBEDDED_JOURNAL_SNAPSHOT_LAST_INDEX.getName());
```
Comment (LuQQiu) [inline core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java:370]: can we make it a separate method?

**Review by LuQQiu — COMMENTED** [review]
Can we have a MetricsUtils or similar file to put the methods of metrics clearance?
e.g. clearJournalStateMachineMetrics()

File: core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java (hunk 1 above)
Comment (kaijchen) [reply core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java:370]: Looks like methods in `MetricsUtils` are general utilities of metrics.
I'm not sure if `MetricsUtils.clearJournalStateMachineMetrics()` is general enough.
The `MetricKey` got cleared is related to what's registered in `JournalStateMachine`.
How about add a private method `JournalStateMachine.clearMetrics()`?

**Review by LuQQiu — APPROVED** [review]
LGTM, thanks

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please
alluxio-bot, merge this please
