### PR TITLE
Fix LostStorageIntegrationTest failure on user 'root'

### LINKED ISSUE #12187: LostStorageIntegrationTest failure on user 'root'
**Alluxio Version:**
2.3.1

**Describe the bug**
I noticed that when I run the `LostStorageIntegrationTest` in root user, the `reportLostStorageInWorkerRegister()` and `lostStorageWhenRestart()` fail because the `setReadOnly()` for the `ssdDir` and `hddDir` doesn't stop the root user from creating the directory "/alluxioworker".

I believe this isn't a flaky test reason as I have deep dived to check the temporary directory that is created in these tests, and I saw the directory /alluxioworker inside of it when it should've been readonly.

**To Reproduce**
Switch user to "root" or whichever is the most parent user on machine:
`sudo su - root`
and then run 
`mvn clean install -DskipTests` (if not built yet)
`mvn test -Dtest=LostStorageIntegrationTest -pl tests`

**Expected behavior**
```
Failed tests:
alluxio.server.tieredstore.LostStorageIntegrationTest.reportLostStorageInWorkerRegister(alluxio.server.tieredstore.LostStorageIntegrationTest)
  Run 1: LostStorageIntegrationTest.reportLostStorageInWorkerRegister:68->checkLostStorageResults:148 expected:<1> but was:<0>
  Run 2: LostStorageIntegrationTest.reportLostStorageInWorkerRegister:68->checkLostStorageResults:148 expected:<1> but was:<0>
Tests in error:
alluxio.server.tieredstore.LostStorageIntegrationTest.lostStorageWhenRestart(alluxio.server.tieredstore.LostStorageIntegrationTest)
  Run 1: LostStorageIntegrationTest.lostStorageWhenRestart:102->checkLostStorageResults:151 NullPointer
  Run 2: LostStorageIntegrationTest.lostStorageWhenRestart:102->checkLostStorageResults:151 NullPointer
```

**Urgency**
Not urgent

**Additional context**
This does not become an issue on normal 'user's since the directory is successfully 'readonly'

### PR DESCRIPTION
**Pull request by maobaolong**
Fix #12187

With this PR, root user and none-root user can pass the `LostStorageIntegrationTest` by exexuted

```bash
# mvn test -Dtest=LostStorageIntegrationTest -pl tests
```

the following is the test by root user.

```bash
[root@c2eaf3f187f2 alluxio]# /softwares/apache-maven-3.6.3/bin/mvn test -Dtest=LostStorageIntegrationTest -pl tests
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.alluxio:alluxio-shaded-hadoop:jar:3.3.0
[WARNING] 'version' contains an expression but should be a constant. @ org.alluxio:alluxio-shaded-hadoop:${ufs.hadoop.version}, /projects/github/alluxio/shaded/hadoop/pom.xml, line 23, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ---------------------< org.alluxio:alluxio-tests >----------------------
[INFO] Building Alluxio Tests 2.4.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-maven) @ alluxio-tests ---
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-versions) @ alluxio-tests ---
[INFO]
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ alluxio-tests ---
[INFO] Starting audit...
Audit done.
[INFO]
[INFO] --- license-maven-plugin:4.0.rc1:check (default) @ alluxio-tests ---
[INFO] Checking licenses...
[WARNING] Unable to find a comment style definition for some files. You may want to add a custom mapping for the relevant file extensions.
[INFO]
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ alluxio-tests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /projects/github/alluxio/tests/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ alluxio-tests ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 16 source files to /projects/github/alluxio/tests/target/classes
[INFO] /projects/github/alluxio/tests/src/main/java/alluxio/master/backcompat/BackwardsCompatibilityJournalGenerator.java: Some input files use or override a deprecated API.
[INFO] /projects/github/alluxio/tests/src/main/java/alluxio/master/backcompat/BackwardsCompatibilityJournalGenerator.java: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] >>> spotbugs-maven-plugin:4.0.4:check (default) > :spotbugs @ alluxio-tests >>>
[INFO]
[INFO] --- spotbugs-maven-plugin:4.0.4:spotbugs (spotbugs) @ alluxio-tests ---
[INFO] Fork Value is true
[INFO] Done SpotBugs Analysis....
[INFO]
[INFO] <<< spotbugs-maven-plugin:4.0.4:check (default) < :spotbugs @ alluxio-tests <<<
[INFO]
[INFO]
[INFO] --- spotbugs-maven-plugin:4.0.4:check (default) @ alluxio-tests ---
[INFO] BugInstance size is 0
[INFO] Error size is 0
[INFO] No errors/warnings found
[INFO]
[INFO] --- jcp:6.1.2:preprocessTests (preprocessSources) @ alluxio-tests ---
[INFO] Preprocess sources : /projects/github/alluxio/tests/src/test/java
[INFO] Preprocess destination : /projects/github/alluxio/tests/target/generated-test-sources/preprocessed
[INFO] -----------------------------------------------------------------
[INFO] Completed, preprocessed 209 files, copied 0 files, elapsed time 14016ms
[INFO] A Compile source root has been removed from the root list [/projects/github/alluxio/tests/src/test/java]
[INFO] The New compile source root has been added into the list [/projects/github/alluxio/tests/target/generated-test-sources/preprocessed]
[INFO]
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ alluxio-tests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 10 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ alluxio-tests ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 201 source files to /projects/github/alluxio/tests/target/test-classes
[INFO] /projects/github/alluxio/tests/target/generated-test-sources/preprocessed/alluxio/client/fs/FileSystemMasterRestartIntegrationTest.java: Some input files use or override a deprecated API.
[INFO] /projects/github/alluxio/tests/target/generated-test-sources/preprocessed/alluxio/client/fs/FileSystemMasterRestartIntegrationTest.java: Recompile with -Xlint:deprecation for details.
[INFO] /projects/github/alluxio/tests/target/generated-test-sources/preprocessed/alluxio/server/ft/MasterFaultToleranceIntegrationTest.java: Some input files use unchecked or unsafe operations.
[INFO] /projects/github/alluxio/tests/target/generated-test-sources/preprocessed/alluxio/server/ft/MasterFaultToleranceIntegrationTest.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ alluxio-tests ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running alluxio.server.tieredstore.LostStorageIntegrationTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 112.123 s - in alluxio.server.tieredstore.LostStorageIntegrationTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:03 min
[INFO] Finished at: 2020-10-14T03:20:08Z
[INFO] ------------------------------------------------------------------------
```

### CODE REVIEW

File: tests/src/test/java/alluxio/server/tieredstore/LostStorageIntegrationTest.java [hunk 1]
```diff
@@ -60,9 +78,21 @@ public void reportLostStorageInWorkerRegister() throws Exception {
     File hddDir = Files.createTempDir();
     String hddPath = hddDir.getAbsolutePath();
 
-    // Set to read only so worker storage paths cannot be initialize
-    ssdDir.setReadOnly();
-    hddDir.setReadOnly();
+//    // Mock no write permission so worker storage paths cannot be initialize
```
Comment (LuQQiu) [inline tests/src/test/java/alluxio/server/tieredstore/LostStorageIntegrationTest.java:81]: Please fix the comment way

File: tests/src/test/java/alluxio/server/tieredstore/LostStorageIntegrationTest.java [hunk 2]
```diff
@@ -60,9 +78,21 @@ public void reportLostStorageInWorkerRegister() throws Exception {
...
+        anyInt(),
+        anyLong(),
+        anyLong(),
+        anyString(),
+        anyString())).thenCallRealMethod();
+    Mockito.when(StorageDir.newStorageDir(any(StorageTier.class),
+        anyInt(),
+        anyLong(),
+        anyLong(),
+        or(startsWith(ssdPath), startsWith(hddPath)),
```
Comment (LuQQiu) [inline tests/src/test/java/alluxio/server/tieredstore/LostStorageIntegrationTest.java:93]: Why need two mockito mock? 
can the path be strings other than ssdPath and hdd path?

**Review by LuQQiu — COMMENTED** [review]
Thanks for fixing the test! Left some comments

File: tests/src/test/java/alluxio/server/tieredstore/LostStorageIntegrationTest.java (hunk 2 above)
Comment (maobaolong) [reply tests/src/test/java/alluxio/server/tieredstore/LostStorageIntegrationTest.java:93]: Yeah, the mem tier path is another path, we need to call real method when the path is mem path.

File: tests/src/test/java/alluxio/server/tieredstore/LostStorageIntegrationTest.java (hunk 1 above)
Comment (maobaolong) [reply tests/src/test/java/alluxio/server/tieredstore/LostStorageIntegrationTest.java:81]: OK, sorry for this

**Comment by maobaolong** [comment]
@LuQQiu Thanks for you review, I correct the comment and push a new commit, PTAL.

**Review by LuQQiu — APPROVED** [review]
Thanks for fixing it! LGTM

File: tests/src/test/java/alluxio/server/tieredstore/LostStorageIntegrationTest.java [hunk 3]
```diff
@@ -38,6 +53,9 @@
 /**
  * Tests for getting worker lost storage information.
  */
+@RunWith(PowerMockRunner.class)
+@PrepareForTest({StorageDir.class})
```
Comment (apc999) [inline tests/src/test/java/alluxio/server/tieredstore/LostStorageIntegrationTest.java:57]: is this because `StorageDir` is `final`?
In case yes, lets change `public final class StorageDir` to be `public class StorageDir`.
In general, we should avoid using `PowerMock` which has a lot limitation

**Review by apc999 — COMMENTED** [review]
One comment left regarding changing `StorageDir` to be non-final.
Otherwise i am good. Thanks for the fix!

**Review by apc999 — APPROVED** [review]
after discussing it offline, I understand the use of powerMock here. LGTM

**Comment by apc999** [comment]
alluxio-bot, merge this please

**Comment by apc999** [comment]
alluxio-bot, cherry-pick this to branch-2.4 please
