### PR TITLE
Make connection pools per connection instead of per db for hive udb

### LINKED ISSUE #13227: HiveClientPool causes the number of hive metastore connections to be too high
**Alluxio Version:**
2.5.0-1

**Describe the bug**
HiveClientPool causes the number of hive metastore connections to be too high, when there are many databases to synchronize

**To Reproduce**
We have more than 100 databases. Alluxio connected to hive metastore and generated more than 400 connections.

**Expected behavior**
There should not be so many connections. 

**Urgency**
MEDIUM

**Additional context**
The alluxio source code uses a database-level connection pool. In fact, it should use a hive metastore url connection pool.

### PR DESCRIPTION
**Pull request by yuzhu**
fixes #13227

### CODE REVIEW

File: table/server/underdb/hive/src/main/java/alluxio/table/under/hive/util/HiveClientPool.java [hunk 1]
```diff
@@ -79,20 +73,7 @@ protected IMetaStoreClient createNewResource() throws IOException {
 
       IMetaStoreClient client = HMSClientFactory.newInstance(
           RetryingMetaStoreClient.getProxy(conf, NOOP_HOOK, HiveMetaStoreClient.class.getName()));
```
Comment (yuzhu) [inline table/server/underdb/hive/src/main/java/alluxio/table/under/hive/util/HiveClientPool.java:75]: I think it works just as well to let other exception handling handle db not exist errors than explicitly checking for it. 
@gpang what do you think?

Comment (gpang) [reply table/server/underdb/hive/src/main/java/alluxio/table/under/hive/util/HiveClientPool.java:75]: I thought maybe there was a reasons to explicitly check for the db, but I forgot why...

File: table/server/underdb/hive/src/main/java/alluxio/table/under/hive/util/HiveClientPool.java [hunk 2]
```diff
@@ -41,24 +40,19 @@
...
    * Creates a new hive client client pool.
    *
    * @param connectionUri the connect uri for the hive metastore
-   * @param hiveDbName the db name in hive
    */
-  public HiveClientPool(String connectionUri, String hiveDbName) {
+  public HiveClientPool(String connectionUri) {
     super(Options.defaultOptions()
         .setMinCapacity(16)
         .setMaxCapacity(128)
```
Comment (gpang) [inline table/server/underdb/hive/src/main/java/alluxio/table/under/hive/util/HiveClientPool.java:52]: If we are re-using pools to the same hive db, we may need to change this to a configuration parameter?

**Review by gpang — COMMENTED** [review]
@yuzhu

**Comment by yuzhu** [comment]
@gpang  PTAL

File: core/common/src/main/java/alluxio/conf/PropertyKey.java [hunk 3]
```diff
@@ -5167,7 +5167,20 @@ public String toString() {
           .setConsistencyCheckLevel(ConsistencyCheckLevel.WARN)
           .setScope(Scope.MASTER)
           .build();
-
+  public static final PropertyKey TABLE_UDB_HIVE_CLIENTPOOL_MIN =
+      new Builder(Name.TABLE_UDB_HIVE_CLIENTPOOL_MIN)
+          .setDefaultValue("16")
+          .setDescription("The minimum capacity of the hive client pool per hive metastore")
```
Comment (gpang) [inline core/common/src/main/java/alluxio/conf/PropertyKey.java:5173]: If these pools are per UDB, then should they be UDB properties instead? (meaning, each `attach`ed db can have a different sized pool.)

**Review by gpang — APPROVED** [review]
@yuzhu Had a minor question.

LGTM

**Comment by LuQQiu** [comment]
@yuzhu Please help update the status of this PR? is it ready to merge

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 3 above)
Comment (yuzhu) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java:5173]: took another closer look, these pools are per connection, not per UDB. since we don't have properties associated with connectionUris, i am inclined to keep them as global property keys for now. we can address this in a separate PR if needed.

**Comment by yuzhu** [comment]
alluxio-bot, merge this please
