### PR TITLE
Avoid RuntimeException for unresolved hostname during metrics reporting

### LINKED ISSUE #12672: Avoid throwing RuntimeException when master hostname is not resolved on metrics reporting
**Alluxio Version:**
What version of Alluxio are you using?
2.4.1-1

**Describe the bug**

If I didn't set hostname and ip address mapping in /etc/hosts

```
2020-12-22 12:45:52,344 ERROR AbstractShell - Error running report
java.lang.RuntimeException: java.net.UnknownHostException: abc: abc: Name does not resolve
        at alluxio.util.network.NetworkAddressUtils.getLocalIpAddress(NetworkAddressUtils.java:501)
        at alluxio.util.network.NetworkAddressUtils.getLocalHostName(NetworkAddressUtils.java:423)
        at alluxio.util.network.NetworkAddressUtils.getLocalHostMetricName(NetworkAddressUtils.java:442)
        at alluxio.metrics.MetricsSystem.constructSourceName(MetricsSystem.java:201)
        at alluxio.metrics.MetricsSystem.lambda$static$0(MetricsSystem.java:88)
        at alluxio.util.CommonUtils$2.firstTime(CommonUtils.java:785)
        at alluxio.util.CommonUtils$2.get(CommonUtils.java:780)
        at alluxio.metrics.MetricsSystem.getMetricNameWithUniqueId(MetricsSystem.java:387)
        at alluxio.metrics.MetricsSystem.initShouldReportMetrics(MetricsSystem.java:749)
        at alluxio.metrics.MetricsSystem.reportMetrics(MetricsSystem.java:559)
        at alluxio.metrics.MetricsSystem.reportClientMetrics(MetricsSystem.java:635)
        at alluxio.client.metrics.ClientMasterSync.heartbeat(ClientMasterSync.java:88)
        at alluxio.client.metrics.MetricsHeartbeatContext.heartbeat(MetricsHeartbeatContext.java:95)
        at alluxio.client.metrics.MetricsHeartbeatContext.close(MetricsHeartbeatContext.java:125)
        at alluxio.client.metrics.MetricsHeartbeatContext.removeContext(MetricsHeartbeatContext.java:108)
        at alluxio.client.metrics.MetricsHeartbeatContext.removeHeartbeat(MetricsHeartbeatContext.java:198)
        at alluxio.client.file.FileSystemContext.closeContext(FileSystemContext.java:300)
        at alluxio.client.file.FileSystemContext.close(FileSystemContext.java:267)
        at alluxio.cli.fsadmin.FileSystemAdminShellUtils.checkMasterClientService(FileSystemAdminShellUtils.java:67)
        at alluxio.cli.fsadmin.command.ReportCommand.run(ReportCommand.java:107)
        at alluxio.cli.AbstractShell.run(AbstractShell.java:137)
        at alluxio.cli.fsadmin.FileSystemAdminShell.main(FileSystemAdminShell.java:71)
Caused by: java.net.UnknownHostException: abc: abc: Name does not resolve
        at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
        at alluxio.util.network.NetworkAddressUtils.getLocalIpAddress(NetworkAddressUtils.java:459)
        ... 21 more
Caused by: java.net.UnknownHostException: abc: Name does not resolve
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
        ... 22 more
```

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

### PR DESCRIPTION
**Pull request by JySongWithZhangCe**
Avoid throwing RuntimeException when hostname is not resolved on metrics reporting
Fix: https://github.com/Alluxio/alluxio/issues/12672

### CODE REVIEW

File: core/common/src/main/java/alluxio/metrics/MetricsSystem.java [hunk 1]
```diff
@@ -196,9 +196,15 @@ private static String constructSourceName() {
...
+    try {
+      hostName = NetworkAddressUtils.getLocalHostMetricName(sResolveTimeout);
+    } catch (RuntimeException e) {
+      hostName = "unhnown";
+      LOG.error("Can't find local host name", e.getMessage());
+    }
     AlluxioConfiguration conf = new InstancedConfiguration(ConfigurationUtils.defaults());
-    return sourceKey != null && conf.isSet(sourceKey)
-        ? conf.get(sourceKey) : NetworkAddressUtils.getLocalHostMetricName(sResolveTimeout);
+    return sourceKey != null && conf.isSet(sourceKey) ? conf.get(sourceKey) : hostName;
```
Comment (LuQQiu) [inline core/common/src/main/java/alluxio/metrics/MetricsSystem.java:207]: Can you help modify the code so that we only call `NetworkAddressUtils.getLocalHostMetricName`  if the condition `sourceKey != null && conf.isSet(sourceKey)` doesn't satisfy?

**Review by LuQQiu — COMMENTED** [review]
Thanks @JySongWithZhangCe , left some minor comments

File: core/common/src/main/java/alluxio/metrics/MetricsSystem.java (hunk 1 above)
Comment (JySongWithZhangCe) [reply core/common/src/main/java/alluxio/metrics/MetricsSystem.java:207]: May be add a `if` statement won't looks like better?
if (sourceKey != null && conf.isSet(sourceKey) {
    return conf.get(sourceKey);
}

Comment (jiacheliu3) [reply core/common/src/main/java/alluxio/metrics/MetricsSystem.java:207]: It will look better and avoid calling `NetworkAddressUtils.getLocalHostMetricName`, saving one call.

File: core/common/src/main/java/alluxio/metrics/MetricsSystem.java [hunk 2]
```diff
@@ -196,9 +196,15 @@ private static String constructSourceName() {
       default:
         break;
     }
+    String hostName;
+    try {
+      hostName = NetworkAddressUtils.getLocalHostMetricName(sResolveTimeout);
+    } catch (RuntimeException e) {
+      hostName = "unhnown";
```
Comment (jiacheliu3) [inline core/common/src/main/java/alluxio/metrics/MetricsSystem.java:203]: typo

**Review by jiacheliu3 — CHANGES_REQUESTED** [review]
@JySongWithZhangCe Left a minor comment. Thanks!

File: core/common/src/main/java/alluxio/metrics/MetricsSystem.java (hunk 1 above)
Comment (JySongWithZhangCe) [reply core/common/src/main/java/alluxio/metrics/MetricsSystem.java:207]: Ok, I'll take it

File: core/common/src/main/java/alluxio/metrics/MetricsSystem.java (hunk 2 above)
Comment (JySongWithZhangCe) [reply core/common/src/main/java/alluxio/metrics/MetricsSystem.java:203]: Got it！

**Review by LuQQiu — APPROVED** [review]
Thanks for fixing the issue and avoid the system crashing! LGTM

**Review by jiacheliu3 — APPROVED** [review]
LGTM, thanks for the improvement!

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please
