### PR TITLE
Set S3 endpoint region and support OCI object storage

### LINKED ISSUE #14133: Add ability to pass region as a field in S3 API call to support non-AWS S3 cloud storage
**Alluxio Version:**
alluxio-2.6.2

**Describe the bug**
non-AWS S3 cloud storage providers who has S3 compatible APIs like Oracle Cloud rely on a field in the request called: "region" to support multiple regions.  if the region value is not present,  it defaults to their customer account primary region.  Hence as of now,  I am unable to use Alluxio with an Oracle Cloud region which is not the "customer account primary region". 

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)
Configure for Oracle Cloud region: 
aws.accessKeyId=xxxx
aws.secretKey=xxxxx
alluxio.underfs.s3.endpoint=https://hpc.compat.objectstorage.us-phoenix-1.oraclecloud.com:443
alluxio.underfs.s3.disable.dns.buckets=true
alluxio.underfs.s3.inherit.acl=false

I can provide credentials to test it or I can do the test for you.   PM me.  

**Expected behavior**
Users able to use region which are not their "primary region".  Only one region can be primary and Oracle Cloud has 30+ regions across the world.  

**Additional context**
Here is the slack discussion with Lu at Alluxio.  
https://alluxio-community.slack.com/archives/CEXGGUBDK/p1632328635302400

Also given below is the request/response when I tried it and it failed.  

`
2021-09-22 15:49:02,188 DEBUG AWS4Signer - AWS4 Canonical Request: '"GET
/testbucket/
delimiter=%2F&fetch-owner=false&list-type=2&max-keys=1000&prefix=
amz-sdk-invocation-id:4a6ea300-dc15-9ccb-9abe-113b136f6fff
amz-sdk-request:ttl=20210922T154952Z;attempt=4;max=4
amz-sdk-retry:3/344/470
content-type:application/octet-stream
host:hpc.compat.objectstorage.ap-osaka-1.oraclecloud.com
user-agent:aws-sdk-java/1.11.815 Linux/5.4.17-2102.204.4.4.el7uek.x86_64 Java_HotSpot(TM)_64-Bit_Server_VM/25.301-b09 java/1.8.0_301 vendor/Oracle_Corporation
x-amz-content-sha256:UNSIGNED-PAYLOAD
x-amz-date:20210922T154902Z

amz-sdk-invocation-id;amz-sdk-request;amz-sdk-retry;content-type;host;user-agent;x-amz-content-sha256;x-amz-date
UNSIGNED-PAYLOAD"
2021-09-22 15:49:02,188 DEBUG AWS4Signer - AWS4 String to Sign: '"AWS4-HMAC-SHA256
20210922T154902Z
20210922/us-east-1/s3/aws4_request
18d8d72339457935d5bfc5ca752efbc6f2d17237f984531a8d1a4a505582587d"
2021-09-22 15:49:02,190 DEBUG wire - http-outgoing-0 >> "GET /testbucket/?list-type=2&delimiter=%2F&max-keys=1000&prefix=&fetch-owner=false HTTP/1.1[\r][\n]"
2021-09-22 15:49:02,190 DEBUG wire - http-outgoing-0 >> "Host: hpc.compat.objectstorage.ap-osaka-1.oraclecloud.com[\r][\n]"
2021-09-22 15:49:02,190 DEBUG wire - http-outgoing-0 >> "amz-sdk-invocation-id: 4a6ea300-dc15-9ccb-9abe-113b136f6fff[\r][\n]"
2021-09-22 15:49:02,190 DEBUG wire - http-outgoing-0 >> "amz-sdk-request: ttl=20210922T154952Z;attempt=4;max=4[\r][\n]"
2021-09-22 15:49:02,190 DEBUG wire - http-outgoing-0 >> "amz-sdk-retry: 3/344/470[\r][\n]"
2021-09-22 15:49:02,190 DEBUG wire - http-outgoing-0 >> "Authorization: AWS4-HMAC-SHA256 Credential=e461b1e1c78cc2f7701fe13e2bea4d853c6b8008/20210922/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;amz-sdk-retry;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=1e0c42b4fece85da658f125def1a4096251905e5a84810c7c5669837af6bdc19[\r][\n]"
2021-09-22 15:49:02,190 DEBUG wire - http-outgoing-0 >> "Content-Type: application/octet-stream[\r][\n]"
2021-09-22 15:49:02,190 DEBUG wire - http-outgoing-0 >> "User-Agent: aws-sdk-java/1.11.815 Linux/5.4.17-2102.204.4.4.el7uek.x86_64 Java_HotSpot(TM)_64-Bit_Server_VM/25.301-b09 java/1.8.0_301 vendor/Oracle_Corporation[\r][\n]"
2021-09-22 15:49:02,190 DEBUG wire - http-outgoing-0 >> "x-amz-content-sha256: UNSIGNED-PAYLOAD[\r][\n]"
2021-09-22 15:49:02,190 DEBUG wire - http-outgoing-0 >> "X-Amz-Date: 20210922T154902Z[\r][\n]"
2021-09-22 15:49:02,190 DEBUG wire - http-outgoing-0 >> "Content-Length: 0[\r][\n]"
2021-09-22 15:49:02,190 DEBUG wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2021-09-22 15:49:02,190 DEBUG wire - http-outgoing-0 >> "[\r][\n]"
2021-09-22 15:49:02,222 DEBUG wire - http-outgoing-0 << "HTTP/1.1 403 Forbidden[\r][\n]"
2021-09-22 15:49:02,222 DEBUG wire - http-outgoing-0 << "x-amz-request-id: kix-1:SWn09whNW7s8beRTf7yKaqDLsVJflTbDQE8n8NQApDD6FNj-ee5d4VA_VWWzELMi[\r][\n]"
2021-09-22 15:49:02,222 DEBUG wire - http-outgoing-0 << "Content-Type: application/xml; charset=utf-8[\r][\n]"
2021-09-22 15:49:02,222 DEBUG wire - http-outgoing-0 << "Content-Length: 253[\r][\n]"
2021-09-22 15:49:02,222 DEBUG wire - http-outgoing-0 << "date: Wed, 22 Sep 2021 15:49:02 GMT[\r][\n]"
2021-09-22 15:49:02,222 DEBUG wire - http-outgoing-0 << "opc-request-id: kix-1:SWn09whNW7s8beRTf7yKaqDLsVJflTbDQE8n8NQApDD6FNj-ee5d4VA_VWWzELMi[\r][\n]"
2021-09-22 15:49:02,222 DEBUG wire - http-outgoing-0 << "x-api-id: s3-compatible[\r][\n]"
2021-09-22 15:49:02,222 DEBUG wire - http-outgoing-0 << "[\r][\n]"
2021-09-22 15:49:02,222 DEBUG wire - http-outgoing-0 << "<?xml version="1.0" encoding="UTF-8"?><Error><Message>The secret key required to complete authentication could not be found. The region must be specified if this is not the home region for the tenancy.</Message><Code>SignatureDoesNotMatch</Code></Error>"
2021-09-22 15:49:02,222 DEBUG ClockSkewAdjuster - Reported server date (from 'Date' header): Wed, 22 Sep 2021 15:49:02 GMT
2021-09-22 15:49:02,223 DEBUG request - Received error response: com.amazonaws.services.s3.model.AmazonS3Exception: The secret key required to complete authentication could not be found. The region must be specified if this is not the home region for the tenancy. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: null; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
2021-09-22 15:49:02,223 DEBUG ClockSkewAdjuster - Reported server date (from 'Date' header): Wed, 22 Sep 2021 15:49:02 GMT
`

### PR DESCRIPTION
**Pull request by LuQQiu**
### What changes are proposed in this pull request?

Fixes #14133 

### Why are the changes needed?

Solves the issue that S3 cannot recognize endpoint region and supports OCI object storage

### Does this PR introduce any user facing changes?
add an s3 region property key

### CODE REVIEW

**Comment by LuQQiu** [comment]
@yuzhu PTAL, thanks!

File: underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java [hunk 1]
```diff
@@ -199,32 +206,69 @@ public static S3AUnderFileSystem createInstance(AlluxioURI uri,
...
-    AmazonS3Client amazonS3Client = new AmazonS3Client(credentials, clientConf);
-
-    // Set a custom endpoint.
-    if (conf.isSet(PropertyKey.UNDERFS_S3_ENDPOINT)) {
-      amazonS3Client.setEndpoint(conf.get(PropertyKey.UNDERFS_S3_ENDPOINT));
+    AmazonS3ClientBuilder clientBuilder = AmazonS3ClientBuilder
+        .standard()
+        .withCredentials(credentials)
+        .withClientConfiguration(clientConf)
+        .withPathStyleAccessEnabled(Boolean.parseBoolean(conf
```
Comment (ggezer) [inline underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java:213]: I think we don't want to override whatever is the default if `withPathStyleAccessEnabled` is not called.
So ideally, not even call `withPathStyleAccessEnabled` when `Boolean.parseBoolean(conf.get(PropertyKey.UNDERFS_S3_DISABLE_DNS_BUCKETS)` is false.

File: underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java [hunk 2]
```diff
@@ -199,32 +206,69 @@ public static S3AUnderFileSystem createInstance(AlluxioURI uri,
...
+      return null;
+    }
+    String endpoint = conf.get(PropertyKey.UNDERFS_S3_ENDPOINT);
+    final URI epr = RuntimeHttpUtils.toUri(endpoint, clientConf);
+    LOG.debug("Creating endpoint configuration for {}", epr);
+
+    String region;
+    if (conf.isSet(PropertyKey.UNDERFS_S3_ENDPOINT_REGION)) {
+      region = conf.get(PropertyKey.UNDERFS_S3_ENDPOINT_REGION);
+    } else if (!ServiceUtils.isS3USStandardEndpoint(endpoint)) {
```
Comment (ggezer) [inline underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java:258]: Could you explain this a little bit more in comments?

**Review by ggezer — CHANGES_REQUESTED** [review]
Thanks! just few minor asks...

File: underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java (hunk 2 above)
Comment (LuQQiu) [reply underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java]: Yeah, reorganize the code to make it more clear.
If ends with s3.amazonaws.com, that's the standard endpoint with default region so no need to set region

File: underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java (hunk 1 above)
Comment (LuQQiu) [reply underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java]: Sounds good! Only set when alluxio conf is set that property, PTAL, thanks

File: underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java [hunk 3]
```diff
@@ -209,9 +209,12 @@ public static S3AUnderFileSystem createInstance(AlluxioURI uri,
     AmazonS3ClientBuilder clientBuilder = AmazonS3ClientBuilder
         .standard()
         .withCredentials(credentials)
-        .withClientConfiguration(clientConf)
-        .withPathStyleAccessEnabled(Boolean.parseBoolean(conf
-            .get(PropertyKey.UNDERFS_S3_DISABLE_DNS_BUCKETS)));
+        .withClientConfiguration(clientConf);
+
+    if (conf.isSet(PropertyKey.UNDERFS_S3_DISABLE_DNS_BUCKETS)) {
```
Comment (ggezer) [inline underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java:214]: It'll always be set because it has a default value defined. So this if statement is redundant.
Earlier we were calling `withPathStyleAccessEnabled` only if it was set and true.

**Comment by LuQQiu** [comment]
@ggezer Addressed the comments, PTAL, thanks!

**Review by ggezer — APPROVED** [review]
Thanks for this new capability!

**Comment by LuQQiu** [comment]
alluxio-bot, merge this please
