### PR TITLE
Release clients back into pools during even during context reinit

### LINKED ISSUE #9922: Client hang for Presto query
**Alluxio Version:**
2.0.1

**Describe the bug**

We repeatedly run a query and find it hang when running for several days. 

The query is 
```sql
select count(1) from a table. 
```

This table we already load in ahead from hdfs to alluxio 
During the running period, some alluxio workers may be down and some lost data may need to read directly from hdfs.

From `jstack`, find 30 threads (as we set presto concurrency to 30) stuck at 
```
"20190919_081107_00969_nmmwc.1.7-19-4862" #4862 prio=5 os_prio=0 tid=0x00007f9618009dd0 nid=0xa86a2 waiting on condition [0x00007f925c2f1000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00007f9bf8c94008> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at alluxio.resource.ResourcePool.acquire(ResourcePool.java:132)
        at alluxio.resource.ResourcePool.acquire(ResourcePool.java:77)
        at alluxio.client.file.FileSystemContext.acquireBlockMasterClient(FileSystemContext.java:421)
        at alluxio.client.file.FileSystemContext.acquireBlockMasterClientResource(FileSystemContext.java:441)
        at alluxio.client.block.AlluxioBlockStore.getInStream(AlluxioBlockStore.java:169)
        at alluxio.client.file.FileInStream.positionedReadInternal(FileInStream.java:252)
        at alluxio.client.file.FileInStream.positionedRead(FileInStream.java:232)
        at alluxio.hadoop.HdfsFileInputStream.read(HdfsFileInputStream.java:128)
        at alluxio.hadoop.HdfsFileInputStream.readFully(HdfsFileInputStream.java:145)
        at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:111)
        at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:120)
        at io.prestosql.parquet.reader.MetadataReader.readFully(MetadataReader.java:313)
        at io.prestosql.parquet.reader.MetadataReader.readFooter(MetadataReader.java:92)
        at io.prestosql.plugin.hive.parquet.ParquetPageSourceFactory.createParquetPageSource(ParquetPageSourceFactory.java:161)
        at io.prestosql.plugin.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:120)
        at io.prestosql.plugin.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:162)
        at io.prestosql.plugin.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:96)
        at io.prestosql.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:53)
        at io.prestosql.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
        at io.prestosql.operator.TableScanOperator.getOutput(TableScanOperator.java:271)
        at io.prestosql.operator.Driver.processInternal(Driver.java:379)
        at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
        at io.prestosql.operator.Driver$$Lambda$2810/201986911.get(Unknown Source)
        at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
        at io.prestosql.operator.Driver.processFor(Driver.java:276)
        at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
        at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        at io.prestosql.$gen.Presto_shopee_101_dirty__shopee102____20190918_090137_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
Currently, not clear. 

**Expected behavior**
No hanging

**Urgency**
High

**Additional context**

### PR DESCRIPTION
**Pull request by ZacBlanco**
This removes a resource leak which may occur when a thread on a client is interrupted while performing any kind of operation.

Because it's possible for a fs context re-initialization to occur while the resource is
acquired this solution removes the `blockReinit` which throws a runtime exception during
an interrupt and is the root cause of the resource leak.

There are three different cases to which may occur during the release of the resource

1. Release while the context is re-initializing
   - The original mBlockMasterClientPool or mFileSystemMasterClientPool
   may be null, closed, or overwritten with a difference pool. The inner class here saves
   the original pool reference used to acquire the client initially. Releasing into the closed pool
   is harmless.
2. Release after the context has been re-initialized
   - Similar to the above scenario the original mBlockMasterClientPool or
   mFileSystemMasterClientPool are going to be using an entirely new pool. Since
   this method will save the original pool reference, this method would result in releasing
   into a closed pool which is harmless
3. Release before any re-initialization
   - This is the normal case. There are no special considerations

The issues mainly affected the FSMaster and BlockMaster clients, however upon inspection, BlockWorker clients have a similar issue, but seems to happen less frequently than the master clients. This PR also applies a similar strategy for BlockWorker clients to hold onto the references of the pool used during the acquire method to make a best-effort to release the resource when finished being used. 

Closes #9922 #10468

### CODE REVIEW

**Comment by chcn** [comment]
@ZacBlanco do you have a test case to show what the issue is and this PR fixes the issue?

**Comment by ZacBlanco** [comment]
@chcn There is a test here which I used to reproduce the issue: https://github.com/Alluxio/alluxio/pull/10714/files#diff-f570d0a32cd800fc55939b5f4175b3d8R610-R685

I haven't added it to the PR because it takes a bit of time to run locally, but essentially the test will hang indefinitely due to the leaked resources.

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java [hunk 1]
```diff
@@ -471,25 +471,33 @@ public void close() {
    * @param workerNetAddress the network address of the channel
    * @return the acquired block worker
```
Comment (gpang) [inline core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java]: update comment about the resource

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java [hunk 2]
```diff
@@ -471,25 +471,33 @@ public void close() {
...
-        .acquire();
+    ClientPoolKey key = new ClientPoolKey(address, AuthenticationUserUtils
+            .getImpersonationUser(context.getSubject(), context.getClusterConf()));
+    return new CloseableResource<BlockWorkerClient>(mBlockWorkerClientPool.computeIfAbsent(key,
+        k -> new BlockWorkerClientPool(context.getSubject(), serverAddress,
+            context.getClusterConf().getInt(PropertyKey.USER_BLOCK_WORKER_CLIENT_POOL_SIZE),
+            context.getClusterConf(), mWorkerGroup))
+        .acquire()) {
+      // Save the reference to the original pool map.
+      ConcurrentHashMap<ClientPoolKey, BlockWorkerClientPool> mPoolMap = mBlockWorkerClientPool;
```
Comment (gpang) [inline core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java]: Hrmmm, can we avoid explicitly defining it, and just define a local final var for it? It will get captured like that right?

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java (hunk 1 above)
Comment (ZacBlanco) [reply core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java]: done

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java (hunk 2 above)
Comment (ZacBlanco) [reply core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java]: done

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java [hunk 3]
```diff
@@ -476,27 +473,36 @@ public void close() {
...
-    return mBlockWorkerClientPool.computeIfAbsent(key,
-        k -> new BlockWorkerClientPool(subject, serverAddress,
-            getClusterConf().getInt(PropertyKey.USER_BLOCK_WORKER_CLIENT_POOL_SIZE),
-            getClusterConf(), mWorkerGroup))
-        .acquire();
+    ClientPoolKey key = new ClientPoolKey(address, AuthenticationUserUtils
+            .getImpersonationUser(context.getSubject(), context.getClusterConf()));
+    final ConcurrentHashMap<ClientPoolKey, BlockWorkerClientPool> poolMap =
+        mBlockWorkerClientPool;
+    return new CloseableResource<BlockWorkerClient>(mBlockWorkerClientPool.computeIfAbsent(key,
```
Comment (gpang) [inline core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java]:
```suggestion
    return new CloseableResource<BlockWorkerClient>(poolMap.computeIfAbsent(key,
```

**Comment by gpang** [comment]
@ggezer could you take a look at the block worker client changes?

**Comment by ZacBlanco** [comment]
alluxio-bot, merge this please

**Comment by ZacBlanco** [comment]
alluxio-bot, cherry-pick this to branch-2.1 please
