### PR TITLE
Fix client side config using wrong hash

### LINKED ISSUE #16491: Reinit client side cluster config hash failed
**Alluxio Version:**

Master branch

**Describe the bug**

Log file is full of the `The interval of Master Replication Check updated to 60000`

**To Reproduce**

Just start master.

**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.

**Are you planning to fix it**
Please indicate if you are already working on a PR. 

**Additional context**

### PR DESCRIPTION
**Pull request by chunxiaozheng**
### What changes are proposed in this pull request?
Revert "Remove ClientContext.mClusterConfHash"
Use the clusterConfHash calculated by the master as the hash version of all the clients.
fix #16491

### Why are the changes needed?
The master uses Configuration.hash() to calculate the hash, while client uses clusterConf to calculate the hash version, which will cause the client to judge that the master and its own clusterConfHash are always unequal, thus updating the client configuration all the time.

### CODE REVIEW

**Review by maobaolong — COMMENTED** [review]
@chunxiaozheng Good catch! Please sign the CLA first, we cannot merge your PR with cla-missing label.

It seems this fix look worth to cherry-pick to branch-2.9 @jiacheliu3 How about your idea?

Without this PR, each client would get configuration from master every 1 minute by default.

**Comment by yyongycy** [comment]
What tests have been done? Could you please upload your test results?
Modify the log level to debug, and check what the update looks like.

File: core/common/src/main/java/alluxio/ClientContext.java [hunk 1]
```diff
@@ -86,13 +87,15 @@ protected ClientContext(ClientContext ctx) {
...
     mUserState = ctx.getUserState();
+    mClusterConfHash = ctx.getClusterConfHash();
     mPathConfHash = ctx.getPathConfHash();
     mUriValidationEnabled = ctx.getUriValidationEnabled();
   }
 
   private ClientContext(Subject subject, AlluxioConfiguration alluxioConf) {
     requireNonNull(subject, "subject is null");
     mClusterConf = requireNonNull(alluxioConf, "alluxioConf is null");
+    mClusterConfHash = alluxioConf.hash();
```
Comment (yyongycy) [inline core/common/src/main/java/alluxio/ClientContext.java:98]: It is better to clarify why this hash needs to be cached.

**Comment by dbw9580** [comment]
the related change was introduced by https://github.com/Alluxio/alluxio/pull/15673

**Comment by maobaolong** [comment]
Hi @LuQQiu @rongrong Could you please give some context for the https://github.com/Alluxio/alluxio/pull/15673 ? So that we can know well with this PR.

**Comment by maobaolong** [comment]
@chunxiaozheng Have you signed the CLA? If so, ping @HelloHorizon here to remove the cla-missing label.

**Comment by chunxiaozheng** [comment]
> Email alerts were previously turned off

**Comment by maobaolong** [comment]
@chunxiaozheng I guess there should be only one revert commit, could you please combine the commits?

**Comment by HelloHorizon** [comment]
alluxio-bot, merge this please

**Comment by chunxiaozheng** [comment]
> @chunxiaozheng I guess there should be only one revert commit, could you please combine the commits?

Sure, I have combined the two commits into one revert commit.

**Review by maobaolong — APPROVED** [review]
It LGTM. @dbw9580 Would you like to take another look?

**Review by dbw9580 — APPROVED** [review]
LGTM, thanks!

**Review by jiacheliu3 — COMMENTED** [review]
If this PR is a revert of https://github.com/Alluxio/alluxio/commit/c5197f39e6632dbfc6cd4fa95bf25015547fde0f then I don't find the change in AlluxioFuse.java. @maobaolong @dbw9580  Could you have another look? Thx!

**Comment by dbw9580** [comment]
```java

  public static void main(String[] args) {
    LOG.info("Alluxio version: {}-{}", RuntimeConstants.VERSION, ProjectConstants.REVISION);
-    AlluxioConfiguration conf = InstancedConfiguration.defaults();
+    AlluxioConfiguration conf = Configuration.global();
```

This change to `AlluxioFuse` is irrelevant, and cannot be reverted as the method `InstancedConfiguration.defaults()` does not exist anymore.

**Review by jiacheliu3 — APPROVED** [review]
LGTM, thanks!

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please
