### PR TITLE
Avoid loads ufs jars multiple times during journal formatting

### LINKED ISSUE #12113: Alluxio loads ufs jars multiple times during journal formatting
**Alluxio Version:**
I'm working of `branch-2.3`

**Describe the bug**
Formatting journal results in `Native Library /tmp/mapr-root-libMapRClient.unknown.so already loaded in another classloader` error. For full log, please, see https://gist.github.com/ChernikovP/687d9bdcbec2b0f06fe318489ddb45ce.

What's happening is that for every single service: `BlockMaster`, `FileSystemMaster`, `MetaMaster`, `MetricsMaster` and `TableMaster` execution of https://github.com/Alluxio/alluxio/blob/680b2fd4ff13d3349572518f15e1f9f5b2fffa93/core/server/common/src/main/java/alluxio/cli/Format.java#L120 results in loading all possible ufs factories, filtering by path prefix the necessary one and trying to process journal entry

**To Reproduce**
- Add `mapr` repository to `pom.xml`:

```
<repository>
  <id>mapr-releases</id>
  <url>https://repository.mapr.com/maven/</url>
  <snapshots>
    <enabled>false</enabled>
  </snapshots>
  <releases>
    <enabled>true</enabled>
  </releases>
</repository>
```

- add follwoing module to `ufsModules` in `dev/scripts/src/alluxio.org/build-distribution/cmd/common.go`:

```
{"hadoop-mapr", true, "-pl underfs/hdfs -Pufs-hadoop-2 -Dufs.hadoop.version=2.7.0-mapr-1808 -PhdfsActiveSync"}
```

- build binaries by running `./dev/scripts/generate-tarballs single -ufs-modules=ufs-hadoop-mapr`

- conf file:

```
# Underfs setup
alluxio.underfs.hdfs.configuration=/opt/mapr/hadoop/hadoop-2.7.0/etc/hadoop/core-site.xml:/opt/mapr/hadoop/hadoop-2.7.0/etc/hadoop/hdfs-site.xml
alluxio.underfs.hdfs.prefixes=maprfs:/
alluxio.underfs.hdfs.impl=com.mapr.fs.MapRFileSystem
# Master setup
alluxio.master.backup.directory=maprfs:///storage/scratch/alluxio/backup
alluxio.master.journal.folder=maprfs:///storage/scratch/alluxio/journal
alluxio.master.journal.type=UFS
alluxio.master.mount.table.root.ufs=maprfs:///
```

- run `./bin/alluxio format` on Alluxio master

**Expected behavior**
Successful  journal formatting

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**
I tried s3 as ufs and get this eventually:

```
2020-08-18 08:42:05,559 INFO  ExtensionFactoryRegistry - Loading core jars from /opt/alluxio-2.3.1-SNAPSHOT-noHelm/lib
2020-08-18 08:42:05,760 DEBUG ExtensionFactoryRegistry - Factory implementation alluxio.underfs.s3a.S3AUnderFileSystemFactory@9f70c54 is eligible for path s3://chernikovp-alluxio/journal/BlockMaster
2020-08-18 08:42:07,212 INFO  ExtensionFactoryRegistry - Loading core jars from /opt/alluxio-2.3.1-SNAPSHOT-noHelm/lib
2020-08-18 08:42:07,243 DEBUG ExtensionFactoryRegistry - Factory implementation alluxio.underfs.s3a.S3AUnderFileSystemFactory@7d3e8655 is eligible for path s3://chernikovp-alluxio/journal/FileSystemMaster
2020-08-18 08:42:07,587 INFO  ExtensionFactoryRegistry - Loading core jars from /opt/alluxio-2.3.1-SNAPSHOT-noHelm/lib
2020-08-18 08:42:07,694 DEBUG ExtensionFactoryRegistry - Factory implementation alluxio.underfs.s3a.S3AUnderFileSystemFactory@346939bf is eligible for path s3://chernikovp-alluxio/journal/MetaMaster
2020-08-18 08:42:08,058 INFO  ExtensionFactoryRegistry - Loading core jars from /opt/alluxio-2.3.1-SNAPSHOT-noHelm/lib
2020-08-18 08:42:08,123 DEBUG ExtensionFactoryRegistry - Factory implementation alluxio.underfs.s3a.S3AUnderFileSystemFactory@62ddd21b is eligible for path s3://chernikovp-alluxio/journal/MetricsMaster
2020-08-18 08:42:08,432 INFO  ExtensionFactoryRegistry - Loading core jars from /opt/alluxio-2.3.1-SNAPSHOT-noHelm/lib
2020-08-18 08:42:08,577 DEBUG ExtensionFactoryRegistry - Factory implementation alluxio.underfs.s3a.S3AUnderFileSystemFactory@474c9131 is eligible for path s3://chernikovp-alluxio/journal/TableMaster
```
Basically, jars are loading multiple times regardless of underlying fs, but it seems like it leads to errors only in my case...

### PR DESCRIPTION
**Pull request by maobaolong**
Fix #12113 

I do the following test, and can only search one line loading core jars output, it is my expected.

```bash
alluxio formatMaster
```

I also start the master to check master can start successful, check alluxio master log only contains one line loading core jars output, it is my expected.

### CODE REVIEW

File: core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java [hunk 1]
```diff
@@ -146,7 +146,8 @@ protected static UnderFileSystemConfiguration getJournalUfsConf() {
    */
   public UfsJournal(URI location, Master master, long quietPeriodMs,
       Supplier<Set<JournalSink>> journalSinks) {
-    this(location, master, UnderFileSystem.Factory.create(location.toString(), getJournalUfsConf()),
+    this(location, master, master.getMasterContext().getUfsManager().getRoot().acquireUfsResource()
```
Comment (gpang) [inline core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java:149]: The root UFS is different from the journal UFS. If the UfsManager doesn't have it already, it should have a method for acquiring the journal UFS (to also use the journal conf, instead of the root ufs conf).

You can basically think of the journal UFS as a different mount point (separate from any other mount point), which is just for accessing the journal UFS.

**Review by gpang — CHANGES_REQUESTED** [review]
@maobaolong Thanks for this improvement! I left a high-level comment in the code.

File: core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java (hunk 1 above)
Comment (maobaolong) [reply core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java]: OK

**Comment by maobaolong** [comment]
@gpang Thanks for your review and suggestion, I've created a new method `getJournal` and a batch of configure keys. Please take another look, thank you.

File: core/common/src/main/java/alluxio/conf/PropertyKey.java [hunk 2]
```diff
@@ -1241,6 +1241,45 @@ public String toString() {
           .setScope(Scope.MASTER)
           .build();
 
+  //
+  // Mount table journal related properties
```
Comment (gpang) [inline core/common/src/main/java/alluxio/conf/PropertyKey.java:1245]: I don't these parameters are necessary. The journal is a not actually a mount point. There is already a config prefix for the journal config: https://github.com/Alluxio/alluxio/blob/v2.4.1/core/common/src/main/java/alluxio/conf/PropertyKey.java#L1163

File: tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java [hunk 3]
```diff
@@ -236,7 +236,7 @@ public void basicRenameTest7() throws Exception {
     // Due to Hadoop 1 support we stick with the deprecated version. If we drop support for it
     // FSDataOutputStream.hflush will be the new one.
     //#ifdef HADOOP1
-    o.sync();
+//    o.sync();
```
Comment (gpang) [inline tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java:239]: Why is this change necessary?

File: core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java [hunk 4]
```diff
@@ -146,7 +146,9 @@ protected static UnderFileSystemConfiguration getJournalUfsConf() {
    */
   public UfsJournal(URI location, Master master, long quietPeriodMs,
       Supplier<Set<JournalSink>> journalSinks) {
-    this(location, master, UnderFileSystem.Factory.create(location.toString(), getJournalUfsConf()),
```
Comment (gpang) [inline core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java:149]: Calling `getJournalUfsConf()`, or doing the same operations as that method (https://github.com/Alluxio/alluxio/blob/v2.4.1/core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java#L131), is important. Is the new behavior equivalent to the previous call to `getJournalUfsConf()`?

File: core/server/common/src/main/java/alluxio/master/NoopUfsManager.java [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+
+/**
+ * Implementation of UfsManager that does nothing. This is useful for testing and
+ * for situations where we don't want to start a real UfsManager,e.g. when formatting the journal.
+ */
+public class NoopUfsManager extends AbstractUfsManager {
+
+  @Override
+  protected void connectUfs(UnderFileSystem fs) throws IOException {
+    fs.connectFromMaster(
```
Comment (gpang) [inline core/server/common/src/main/java/alluxio/master/NoopUfsManager.java:29]: Does the NOOP one require this implementation?

File: core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java [hunk 6]
```diff
@@ -209,6 +210,30 @@ public UfsClient getRoot() {
...
+    synchronized (this) {
+      if (mJournalUfsClient == null) {
+        String uri = ServerConfiguration.get(PropertyKey.MASTER_MOUNT_TABLE_JOURNAL_UFS);
+        boolean readOnly =
+            ServerConfiguration.getBoolean(PropertyKey.MASTER_MOUNT_TABLE_JOURNAL_READONLY);
+        boolean shared = ServerConfiguration
+            .getBoolean(PropertyKey.MASTER_MOUNT_TABLE_JOURNAL_SHARED);
+        Map<String, String> conf =
+            ServerConfiguration.getNestedProperties(PropertyKey.MASTER_MOUNT_TABLE_JOURNAL_OPTION);
+        addMount(IdUtils.JOURNAL_MOUNT_ID, new AlluxioURI(uri),
```
Comment (gpang) [inline core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java:224]: It looks like we are reusing the mounts to store the journal UFS as well. Can you document that in a comment somewhere? Maybe near the top of this class?

File: core/common/src/main/java/alluxio/util/IdUtils.java [hunk 7]
```diff
@@ -34,6 +34,7 @@
   public static final long INVALID_WORKER_ID = -1;
   public static final long INVALID_MOUNT_ID = -1;
   public static final long ROOT_MOUNT_ID = 1;
+  public static final long JOURNAL_MOUNT_ID = Long.MAX_VALUE - 10000;
```
Comment (gpang) [inline core/common/src/main/java/alluxio/util/IdUtils.java:37]: NIT: I think this only applies to UFS journal, so maybe rename this to`UFS_JOURNAL_MOUNT_ID`, and add a comment that the journal ufs is stored as a special mount in the ufs manager.

**Review by gpang — CHANGES_REQUESTED** [review]
@maobaolong Thanks! I left a few comments.

File: core/common/src/main/java/alluxio/util/IdUtils.java (hunk 7 above)
Comment (maobaolong) [reply core/common/src/main/java/alluxio/util/IdUtils.java]: Done

File: core/server/common/src/main/java/alluxio/master/NoopUfsManager.java (hunk 5 above)
Comment (maobaolong) [reply core/server/common/src/main/java/alluxio/master/NoopUfsManager.java]: No, removed it in last commit

File: tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java (hunk 3 above)
Comment (maobaolong) [reply tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java]: Sorry, it is an accident change.

File: core/common/src/main/java/alluxio/conf/PropertyKey.java (hunk 2 above)
Comment (maobaolong) [reply core/common/src/main/java/alluxio/conf/PropertyKey.java]: Thanks for remind me, I've enlarge the access scope of the `getJournalUfsConf ` from `protected` to `public` and turn to use `getJournalUfsConf ` instead.

File: core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java (hunk 4 above)
Comment (maobaolong) [reply core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java:149]: Thanks for this suggestion, I'm doing the same operations `getJournalUfsConf()`  in the AbstractUfsManager#getJournal

File: core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java (hunk 6 above)
Comment (maobaolong) [reply core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java]: Done. added comments on the class java doc.

**Comment by maobaolong** [comment]
@gpang Thanks for your review again, I push several new commits to address your comments.

**Review by gpang — APPROVED** [review]
@maobaolong Thanks for this great improvement!

LGTM

**Comment by gpang** [comment]
alluxio-bot, merge this please

**Comment by maobaolong** [comment]
@gpang Thank you very much for merge this PR.
