### PR TITLE
[#8366] Move FileSystemUtils into FileSystem

### LINKED ISSUE #8366: FileSystemUtils methods should be included in the public FileSystem interface
**Alluxio Version:** 1.8.1

**Describe the Issue**

The `FileSystemUtils` class has a few crucial methods such as `persist`, `waitCompleted`, and `checkConsistency`. These methods require access to a `FileSystemContext` and `FileSystem`. The `BaseFileSystem` already contains a `FileSystemContext` so it seems odd that these utility methods need both. I believe these methods are also useful enough to warrant moving them directly into the client API so users can access their functionality.

**To Reproduce**
N/A

**Expected behavior**
The FileSystem class should expose the `waitCompleted`, `persistFile`, and `checkConsistency` functions.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by ZacBlanco**
It's odd that some functions of the Alluxio Filesystem are implemented within `FileSystemUtils` as opposed to the normal `FileSystem`. Passing a `FileSystem` and `FileSystemContext` together in any of the functions within `FileSystemUtils` implies that the `FileSystemContext` belongs to the `FileSystem` client that is being passed. While implied, it is not necessarily strictly enforced. Moving these functions into the FileSystem API and implementations to `BaseFileSystem` provides more flexibility because they no longer need direct access to the FileSystemContext to perform checkConsistency, persist, and waitCompleted operations.

Fixes #8366

### CODE REVIEW

**Comment by ZacBlanco** [comment]
Reviewers PTAL, thanks!
Primary: @aaudiber 
Secondary: @calvinjia

File: core/client/fs/src/main/java/alluxio/client/file/FileSystem.java [hunk 1]
```diff
@@ -243,6 +244,26 @@ public boolean equals(Object o) {
...
   boolean isClosed();
 
+  /**
+   * Convenience method for {@link #checkConsistency(AlluxioURI, CheckConsistencyPOptions)} with
+   * default options.
+   *
+   * @param path the root of the subtree to check
+   * @return a list of inconsistent files and directories
+   */
+  List<AlluxioURI> checkConsistency(AlluxioURI path) throws IOException;
```
Comment (aaudiber) [inline core/client/fs/src/main/java/alluxio/client/file/FileSystem.java]: I don't think `checkConsistency` belongs in the `FileSystem` API. It isn't very useful programmatically, and is really just used by the `checkConsistency` shell command, which could instead make a 1-off client and doesn't need any sort of pooling.

File: core/client/fs/src/main/java/alluxio/client/file/FileSystem.java [hunk 2]
```diff
@@ -500,6 +521,15 @@ FileInStream openFile(AlluxioURI path)
...
       throws FileDoesNotExistException, IOException, AlluxioException;
 
+  /**
+   * Schedules the given path to be asynchronously persisted to the under file system. If a
+   * synchronous persist operation is desired please see
+   * {@link FileSystemUtils#waitPersisted(FileSystem, AlluxioURI)}
+   *
+   * @param uri the uri of the file to persist
+   */
+  void persist(AlluxioURI uri) throws IOException;
```
Comment (aaudiber) [inline core/client/fs/src/main/java/alluxio/client/file/FileSystem.java]: even if there aren't any options now, it's still good to include an options argument so that we can add options in the future without breaking the API

File: examples/src/main/java/alluxio/cli/RunOperation.java [hunk 3]
```diff
@@ -147,7 +148,9 @@ private void applyOperation() throws IOException, AlluxioException {
           mFileSystem.delete(uri);
           break;
         case CreateFile:
-          try (FileOutStream file = mFileSystem.createFile(uri)) {
+          try (FileOutStream file =
+              mFileSystem.createFile(uri,
```
Comment (aaudiber) [inline examples/src/main/java/alluxio/cli/RunOperation.java]: 👍

File: shell/src/main/java/alluxio/cli/fs/command/PersistCommand.java [hunk 4]
```diff
@@ -56,6 +58,15 @@
           .desc("Number of concurrent persist operations, default: " + DEFAULT_PARALLELISM)
           .required(false)
           .build();
+  private static final int DEFAULT_TIMEOUT = 20 * Constants.MINUTE_MS;
+  private static final Option TIMEOUT_OPTION =
+      Option.builder("t")
+          .longOpt("timeout")
+          .argName("timeout milliseconds")
```
Comment (aaudiber) [inline shell/src/main/java/alluxio/cli/fs/command/PersistCommand.java]: timeout in milliseconds?

File: shell/src/main/java/alluxio/cli/fs/FileSystemShellUtils.java [hunk 5]
```diff
@@ -218,6 +220,23 @@ public static String validatePath(String path, AlluxioConfiguration alluxioConf)
...
+   * Gets the value of an option from the command line.
+   *
+   * @param cl command line object
+   * @param option the option to check for in the command line
+   * @param defaultValue default value for the option
+   * @return argument from command line or default if not present
+   */
+  public static int getIntArg(CommandLine cl, Option option, int defaultValue) {
+    int arg = defaultValue;
+    if (cl.hasOption(option.getLongOpt())) {
```
Comment (aaudiber) [inline shell/src/main/java/alluxio/cli/fs/FileSystemShellUtils.java]: does this work with both short and long options?

File: shell/src/main/java/alluxio/cli/fs/command/PersistCommand.java [hunk 6]
```diff
@@ -56,6 +58,15 @@
...
+          .numberOfArgs(1)
+          .desc("Time in milliseconds for a single file persist to time out: " + DEFAULT_TIMEOUT)
```
Comment (aaudiber) [inline shell/src/main/java/alluxio/cli/fs/command/PersistCommand.java]: is it clear here that the number is the default timeout?

File: tests/src/test/java/alluxio/client/cli/fs/command/PersistCommandTest.java [hunk 7]
```diff
@@ -259,16 +263,42 @@ public void persistParallelFilesGtParallelism() throws Exception {
     persistParallel(2, 1);
   }
 
-  public void persistParallel(int totalFiles, int parallelism) throws Exception {
-    int fileSize = 30;
+  @Test
+  public void persistShortTimeout() throws Exception {
+    createUnpersistedFiles("testPersistTimeout", 100, 50);
```
Comment (aaudiber) [inline tests/src/test/java/alluxio/client/cli/fs/command/PersistCommandTest.java]: strange to see an absolute path that doesn't start with "/" - I'd put the "/" here for clarity instead of in `createUnpersistedFiles`

File: tests/src/test/java/alluxio/client/fs/FileSystemIntegrationTest.java [hunk 8]
```diff
@@ -67,6 +67,9 @@
   private CreateFilePOptions mWriteBoth;
   private UnderFileSystem mUfs;
 
+  private static CreateFilePOptions sWriteBoth = CreateFilePOptions.newBuilder()
```
Comment (aaudiber) [inline tests/src/test/java/alluxio/client/fs/FileSystemIntegrationTest.java]: is this used?

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemUtils.java [hunk 9]
```diff
@@ -122,53 +119,43 @@ public static boolean waitCompleted(final FileSystem fs, final AlluxioURI uri,
...
+   * Persists the given path to the under file system and returns once the persist is complete.
+   * Note that if this method times out, the persist may still occur after the timeout period.
+   *
+   * @param fs {@link FileSystem} to carry out Alluxio operations
+   * @param uri the uri of the file to persist
+   * @param timeoutMs max amount of time to wait for persist in milliseconds. -1 to wait
+   *                  indefinitely
+   * @throws TimeoutException if the persist takes longer than the timeout
+   */
+  public static void waitPersisted(final FileSystem fs, final AlluxioURI uri, int timeoutMs)
```
Comment (aaudiber) [inline core/client/fs/src/main/java/alluxio/client/file/FileSystemUtils.java]: `waitPersisted` sounds like it would wait for something to be persisted, as opposed to persist something and then wait. Perhaps we could name it `persistAndWait`? Alternately, we could have callers call `persist` themselves before calling `waitPersisted`. This has the advantage of letting us specify separate options for persistence vs waiting for persistence

File: core/client/fs/src/main/java/alluxio/client/file/FileSystem.java (hunk 2 above)
Comment (ZacBlanco) [reply core/client/fs/src/main/java/alluxio/client/file/FileSystem.java]: good call. Will add. Didn't realize there's some options available already: `ScheduleAsyncPersistencePOptions`

File: shell/src/main/java/alluxio/cli/fs/FileSystemShellUtils.java (hunk 5 above)
Comment (ZacBlanco) [reply shell/src/main/java/alluxio/cli/fs/FileSystemShellUtils.java]: Yes. This is the same logic we used previously in the persist command for parallelism. I just generalized it

File: shell/src/main/java/alluxio/cli/fs/command/PersistCommand.java (hunk 6 above)
Comment (ZacBlanco) [reply shell/src/main/java/alluxio/cli/fs/command/PersistCommand.java]: good catch

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemUtils.java (hunk 9 above)
Comment (ZacBlanco) [reply core/client/fs/src/main/java/alluxio/client/file/FileSystemUtils.java]: I agree that we should probably change the names but I'm not quite sure what I want to rename them to. Another option is calling the client API method `asyncPersist` and the then we could put something like `synchronousPersist` in `FileSystemUtils`?

Calling the user-facing method `asyncPersist` removes any ambiguities on how the method behaves, but removes the flexibility of changing the behavior of the method in the future.

I'm not a huge fan of `persistAndWait` as a method name. It just sounds clunky. I also don't like `waitPersisted`

Comment (ZacBlanco) [reply core/client/fs/src/main/java/alluxio/client/file/FileSystemUtils.java]: So I see 3 options (ordered by my preference):

1. API method gets `asyncPersist`, `FileSystemUtils` gets `synchronousPersist`
2. API method remains `persist`, `FileSystemUtils` drops the persist action and we call it `waitPersisted`. It polls for a file's persistence state as opposed to persisting, and then polling
3. API method remains `persist`, `FileSystemUtils` gets renamed to `persistAndWait`

File: tests/src/test/java/alluxio/client/fs/FileSystemIntegrationTest.java (hunk 8 above)
Comment (ZacBlanco) [reply tests/src/test/java/alluxio/client/fs/FileSystemIntegrationTest.java]: Whoops. this shouldn't have made it in here

File: tests/src/test/java/alluxio/client/cli/fs/command/PersistCommandTest.java (hunk 7 above)
Comment (ZacBlanco) [reply tests/src/test/java/alluxio/client/cli/fs/command/PersistCommandTest.java]: 👍

File: core/client/fs/src/main/java/alluxio/client/file/FileSystem.java (hunk 1 above)
Comment (ZacBlanco) [reply core/client/fs/src/main/java/alluxio/client/file/FileSystem.java]: Could we move this directly into the `CheckConsistencyCommand` then?

Comment (aaudiber) [reply core/client/fs/src/main/java/alluxio/client/file/FileSystem.java]: sgtm

File: tests/src/test/java/alluxio/client/cli/fs/command/PersistCommandTest.java [hunk 10]
```diff
@@ -259,16 +263,42 @@ public void persistParallelFilesGtParallelism() throws Exception {
...
+    mFsShell.run("persist", "--timeout", String.valueOf(1), "/*"); // 1ms persist timeout
+    assertTrue("Should log at least one timeout",
+        mLogRule.wasLogged("Timed out waiting for file to be persisted:"));
+  }
+
+  @Test
+  public void persistLongTimeout() throws Exception {
+    int fileSize = 100;
+    List<AlluxioURI> files = createUnpersistedFiles("/testPersistTimeout", fileSize, 25);
+    int ret = mFsShell.run("persist", "--timeout", String.valueOf(60 * 1000), "/*");
```
Comment (aaudiber) [inline tests/src/test/java/alluxio/client/cli/fs/command/PersistCommandTest.java]: can we add a test for the short version ("-t" instead of "--timeout")?

Comment (ZacBlanco) [reply tests/src/test/java/alluxio/client/cli/fs/command/PersistCommandTest.java]: Added unit tests for `getIntArg` and for `PersistCommand` in 87224f3bfea9ea720615480bb9c090c2c6a6dfae

File: core/client/fs/src/main/java/alluxio/client/file/FileSystem.java [hunk 11]
```diff
@@ -500,6 +501,24 @@ FileInStream openFile(AlluxioURI path)
...
+   * Convenience method for {@link #persist(AlluxioURI, ScheduleAsyncPersistencePOptions)} which
+   * uses the default {@link ScheduleAsyncPersistencePOptions}.
+   *
+   * @param uri the uri of the file to persist
+   */
+  void persist(AlluxioURI uri) throws IOException;
+
+  /**
+   * Schedules the given path to be asynchronously persisted to the under file system. If a
+   * synchronous persist operation is desired please see
```
Comment (aaudiber) [inline core/client/fs/src/main/java/alluxio/client/file/FileSystem.java]: nit: First section of javadoc should be a single sentence, then additional content goes after an empty line.
nit: Prefer active voice over passive voice, e.g. "To persist synchronously ...", "If you would like to persist the file synchronously ...", etc.

File: core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java [hunk 12]
```diff
@@ -477,6 +478,22 @@ public void mount(AlluxioURI alluxioPath, AlluxioURI ufsPath, MountPOptions opti
...
+  public void persist(final AlluxioURI uri) throws IOException {
+    persist(uri, ScheduleAsyncPersistencePOptions.getDefaultInstance());
+  }
+
+  @Override
+  public void persist(final AlluxioURI uri, ScheduleAsyncPersistencePOptions options)
+      throws IOException {
+    FileSystemMasterClient client = mFsContext.acquireMasterClient();
+    try {
+      client.scheduleAsyncPersist(uri, options);
```
Comment (calvinjia) [inline core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java]: Should we have similar exception handling as the other methods? And name `client` -> `masterClient`, `uri` -> `path`?

File: core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java [hunk 13]
```diff
@@ -297,7 +298,8 @@ private void handleCacheWriteException(Exception e) throws IOException {
   protected void scheduleAsyncPersist() throws IOException {
     try (CloseableResource<FileSystemMasterClient> masterClient = mContext
         .acquireMasterClientResource()) {
-      masterClient.get().scheduleAsyncPersist(mUri);
+      masterClient.get().scheduleAsyncPersist(mUri,
+          ScheduleAsyncPersistencePOptions.getDefaultInstance());
```
Comment (calvinjia) [inline core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java]: Should these inherit common options?

Comment (ZacBlanco) [reply core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java]: What do you mean?

Comment (calvinjia) [reply core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java]: It actually seems a bit weird now that I dig deeper.
I was thinking `FileOutStream` has an `OutStreamOptions` object which has some fields like `TtlAction` that are included in the `CommonOptions` of `ScheduleAsyncPersistencePOptions` so we may want to carry those over.

File: core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java (hunk 12 above)
Comment (apc999) [reply core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java]: something like `LOG.debug("scheduleAsyncPersist for {}, options: {}", uri.getPath(), options);` ?

File: core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java (hunk 13 above)
Comment (ZacBlanco) [reply core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java]: Well for the options we'd need to consolidate some of the fields inside `OutStreamOptions` into `CommonPOptions` but that seems outside of the scope of this PR.

Comment (calvinjia) [reply core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java]: Yeah I agree, could you leave a todo/ticket for making sure we propagate options?

Comment (ZacBlanco) [reply core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java]: New issue created

File: core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java (hunk 12 above)
Comment (ZacBlanco) [reply core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java]: Addressed both of these in the last commit
