### PR TITLE
Cache BlockLocationPolicy for the current client

### LINKED ISSUE #15924: Block location Policy should not create for each file
**Alluxio Version:**
Master branch

**Describe the bug**
Block location Policy should not create for each file. 

**To Reproduce**

Use roundrobin block location policy cannot round robin now, because the policy is created for each file and the index is stored within each policy object.

**Expected behavior**

Each policy should used for all files from a client.

**Urgency**

Urgency.

**Are you planning to fix it**

Yeah

**Additional context**
No

### PR DESCRIPTION
**Pull request by maobaolong**
### What changes are proposed in this pull request?

Fix #15924

### CODE REVIEW

**Comment by maobaolong** [comment]
@jiacheliu3 @dengweisysu would you like to take a look at this PR? Thanks!

**Review by jiacheliu3 — COMMENTED** [review]
I don't think you need to cache Policy objects. Instead by this cache you effectively want a singleton-based solution. By `CommonUtils.createNewClassInstance()` it's hard to use singleton. So I'm proposing this:

```
class Factory {
  public static BlockLocationPolicy create(Class<?> clazz, AlluxioConfiguration conf) {
    switch(clazz) {
        // For all the policies defined in Alluxio
        case RoundRobinPolicy: return RoundRobinPolicy.getInstance();
        case LocalFirstPolicy: return new LocalFirstPolicy(); // You may even use singleton here too
        // Similarly for each class
        default: return CommonUtils.createNewClassInstance(...);
    }
  }
}
```
For all the classes you try to cache, you basically need a singleton. Otherwise you just want a new object.

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java [hunk 1]
```diff
@@ -164,6 +165,9 @@ public class FileSystemContext implements Closeable {
   @GuardedBy("this")
   private final RefreshPolicy mWorkerRefreshPolicy;
 
+  private volatile BlockLocationPolicy mReadBlockLocationPolicy;
+  private volatile BlockLocationPolicy mWriteBlockLocationPolicy;
```
Comment (jiacheliu3) [inline core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java:169]: Discussed with @maobaolong they are put in `FileSystemContext` instead of `ClientContext` because the policies are in `alluxio-core-client-fs` module but `ClientContext` is in `alluxio-core-common` module. If they are added to `ClientContext` that will introduce a circular dependency? I think this is fine. WDYT@dbw9580 ?

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java [hunk 2]
```diff
@@ -249,6 +253,12 @@ private FileSystemContext(AlluxioConfiguration conf, @Nullable BlockWorker block
     mBlockWorker = blockWorker;
     mWorkerRefreshPolicy =
         new TimeoutRefresh(conf.getMs(PropertyKey.USER_WORKER_LIST_REFRESH_INTERVAL));
+    mReadBlockLocationPolicy =
+        BlockLocationPolicy.Factory.create(
+            conf.getClass(PropertyKey.USER_UFS_BLOCK_READ_LOCATION_POLICY), conf);
+    mWriteBlockLocationPolicy =
+        BlockLocationPolicy.Factory.create(
+            conf.getClass(PropertyKey.USER_BLOCK_WRITE_LOCATION_POLICY), conf);
```
Comment (jiacheliu3) [inline core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java:261]: If you decide the policy here, the path config are not really resolved yet
https://github.com/Alluxio/alluxio/blob/5828d56a824748e7c91076842fad75efb42f92f9/core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java#L171

This is my biggest concern now and I think other parts of this PR look good.

**Comment by jiacheliu3** [comment]
added @elega for visibility

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java (hunk 2 above)
Comment (dbw9580) [reply core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java:261]: `RoundRobinPolicy` caches the worker infos the first time its `getWorker` method gets called:

https://github.com/Alluxio/alluxio/blob/da543a5b604cae9703d55dad4102996ab685c3b1/core/client/fs/src/main/java/alluxio/client/block/policy/RoundRobinPolicy.java#L75-L79

When the policy's lifetime is tied to a specific file stream, it's totally fine. But if it's tied to the lifetime of the client, the information can get stale and is likely to cause unavailable exceptions.

Comment (dbw9580) [reply core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java:261]: How about round-robin selection based on worker address hashcodes?

First add a new field:
```java
  // initialize with a random integer to start with a random worker
  private int mPreviousHashCode = new Random().nextInt();
```

Then implement the round-robin algorithm as:

```java

    // Round-robin selection based on worker address hashcodes
    // The assumption is that WorkerNetAddress has a well-implemented `hashCode()`
    // that ensures different workers have distinct hashcodes.

    // find the worker whose address object has a hashcode that is greater than
    // the previous selection but the smallest among all.
    Optional<WorkerNetAddress> candidate = Streams.stream(options.getBlockWorkerInfos())
        .map(BlockWorkerInfo::getNetAddress)
        .filter(workerNetAddress -> workerNetAddress.hashCode() > mPreviousHashCode)
        .min(Comparator.comparingInt(WorkerNetAddress::hashCode));
    if (!candidate.isPresent()) {
      // reset the hashcode and pick the smallest one
      Optional<WorkerNetAddress> smallest = Streams.stream(options.getBlockWorkerInfos())
          .map(BlockWorkerInfo::getNetAddress)
          .min(Comparator.comparingInt(WorkerNetAddress::hashCode));
      mPreviousHashCode = smallest.map(WorkerNetAddress::hashCode).orElse(Integer.MIN_VALUE);
      return smallest;
    } else {
      mPreviousHashCode = candidate.get().hashCode();
      return candidate;
    }
```

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java (hunk 1 above)
Comment (maobaolong) [reply core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java:169]: Thanks for the explanation for me.

File: core/client/fs/src/main/java/alluxio/client/file/options/OutStreamOptions.java [hunk 3]
```diff
@@ -113,23 +114,27 @@ public OutStreamOptions(CreateFilePOptions options, ClientContext context,
...
-    mLocationPolicy = BlockLocationPolicy.Factory.create(
-        alluxioConf.getClass(PropertyKey.USER_BLOCK_WRITE_LOCATION_POLICY),
-        alluxioConf);
+    Class<?> policyClass = alluxioConf.getClass(PropertyKey.USER_BLOCK_WRITE_LOCATION_POLICY);
+
+    if (context.getWriteBlockLocationPolicy() != null
+        && context.getWriteBlockLocationPolicy().getClass() == policyClass) {
+      mLocationPolicy = context.getWriteBlockLocationPolicy();
+    } else {
+      mLocationPolicy = BlockLocationPolicy.Factory.create(policyClass, alluxioConf);
```
Comment (jiacheliu3) [inline core/client/fs/src/main/java/alluxio/client/file/options/OutStreamOptions.java:132]: put this policy back into the `FileSystemContext`

File: tests/src/test/java/alluxio/client/fs/LocalFirstPolicyIntegrationTest.java [hunk 4]
```diff
@@ -107,22 +107,6 @@ public void test() throws Exception {
       assertEquals(100, blockWorker1.getStoreMeta().getUsedBytes());
       assertEquals(0, blockWorker2.getStoreMeta().getUsedBytes());
     }
-
```
Comment (jiacheliu3) [inline tests/src/test/java/alluxio/client/fs/LocalFirstPolicyIntegrationTest.java:110]: pls move this to a separate `@Test` method in the same class, instead of a new one

File: core/server/worker/src/test/java/alluxio/worker/block/stream/BlockWorkerDataReaderTest.java [hunk 5]
```diff
@@ -122,7 +122,7 @@ public void before() throws Exception {
     URIStatus dummyStatus =
         new URIStatus(new FileInfo().setBlockIds(Collections.singletonList(BLOCK_ID)));
     InStreamOptions options =
-        new InStreamOptions(dummyStatus, FileSystemOptions.openFileDefaults(mConf), mConf);
+        new InStreamOptions(dummyStatus, FileSystemOptions.openFileDefaults(mConf), mConf, null);
```
Comment (jiacheliu3) [inline core/server/worker/src/test/java/alluxio/worker/block/stream/BlockWorkerDataReaderTest.java:125]: Actually, if you create a `FileSystemContext` here can we already be sure that in the constructor the `FileSystemContext` is never null? Then we can just do `Precondition.notNull(fsContext)` in that constructor?

**Review by jiacheliu3 — CHANGES_REQUESTED** [review]
Mostly LGTM, thanks for the work! I have one minor comment and [this](https://github.com/Alluxio/alluxio/pull/15923/files#r973817290).

**Review by jiacheliu3 — APPROVED** [review]
LGTM with this minor comment https://github.com/Alluxio/alluxio/pull/15923/files#r975379536
If that comment can be resolved with a few lines of code then pls try to do it in this PR. Otherwise I'm good with the current approach. Thanks!

**Comment by jiacheliu3** [comment]
@dbw9580 could you take anther look?

**Comment by maobaolong** [comment]
> LGTM with this minor comment https://github.com/Alluxio/alluxio/pull/15923/files#r975379536 If that comment can be resolved with a few lines of code then pls try to do it in this PR. Otherwise I'm good with the current approach. Thanks!

Thanks for your kindly review and suggestion, I push a new commit to make the fileSystemContext argument nonnull

File: core/client/fs/src/main/java/alluxio/client/file/options/InStreamOptions.java [hunk 6]
```diff
@@ -74,8 +91,11 @@ public InStreamOptions(URIStatus status, OpenFilePOptions options,
 
     mStatus = status;
     mProtoOptions = openOptions;
-    mUfsReadLocationPolicy = BlockLocationPolicy.Factory.create(
-        alluxioConf.getClass(PropertyKey.USER_UFS_BLOCK_READ_LOCATION_POLICY), alluxioConf);
+    mUfsReadLocationPolicy = context.getReadBlockLocationPolicy(alluxioConf);
+    if (mUfsReadLocationPolicy == null) {
+      mUfsReadLocationPolicy = BlockLocationPolicy.Factory.create(
+          alluxioConf.getClass(PropertyKey.USER_UFS_BLOCK_READ_LOCATION_POLICY), alluxioConf);
```
Comment (dbw9580) [inline core/client/fs/src/main/java/alluxio/client/file/options/InStreamOptions.java:97]: Can `mUfsReadLocationPolicy` be null?  I think this check is redundant.

File: core/client/fs/src/main/java/alluxio/client/file/options/OutStreamOptions.java [hunk 7]
```diff
@@ -113,23 +114,24 @@ public OutStreamOptions(CreateFilePOptions options, ClientContext context,
...
     mCommonOptions = FileSystemOptions.commonDefaults(alluxioConf);
     mBlockSizeBytes = alluxioConf.getBytes(PropertyKey.USER_BLOCK_SIZE_BYTES_DEFAULT);
-    mLocationPolicy = BlockLocationPolicy.Factory.create(
-        alluxioConf.getClass(PropertyKey.USER_BLOCK_WRITE_LOCATION_POLICY),
-        alluxioConf);
+    mLocationPolicy = context.getWriteBlockLocationPolicy(alluxioConf);
+    if (mLocationPolicy == null) {
+      mLocationPolicy = BlockLocationPolicy.Factory.create(
+          alluxioConf.getClass(PropertyKey.USER_BLOCK_WRITE_LOCATION_POLICY), alluxioConf);
+    }
```
Comment (dbw9580) [inline core/client/fs/src/main/java/alluxio/client/file/options/OutStreamOptions.java:130]: same as above

File: core/server/worker/src/test/java/alluxio/worker/block/stream/BlockWorkerDataReaderTest.java [hunk 8]
```diff
@@ -151,7 +153,7 @@ public void createAndCloseManyReader() throws Exception {
       mBlockWorker.commitBlock(SESSION_ID, blockId, true);
       InStreamOptions inStreamOptions = new InStreamOptions(
           new URIStatus(new FileInfo().setBlockIds(Collections.singletonList(blockId))),
-          FileSystemOptions.openFileDefaults(mConf), mConf);
+          FileSystemOptions.openFileDefaults(mConf), mConf, null);
```
Comment (dbw9580) [inline core/server/worker/src/test/java/alluxio/worker/block/stream/BlockWorkerDataReaderTest.java:156]: The last argument is annotated with `NonNull`.

**Review by dbw9580 — CHANGES_REQUESTED** [review]
Some minor issues

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java (hunk 2 above)
Comment (dbw9580) [reply core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java]: > `RoundRobinPolicy` caches the worker infos the first time its `getWorker` method gets called:
> 
> https://github.com/Alluxio/alluxio/blob/da543a5b604cae9703d55dad4102996ab685c3b1/core/client/fs/src/main/java/alluxio/client/block/policy/RoundRobinPolicy.java#L75-L79
> 
> When the policy's lifetime is tied to a specific file stream, it's totally fine. But if it's tied to the lifetime of the client, the information can get stale and is likely to cause unavailable exceptions.

Is this getting addressed in a separate PR?

File: core/client/fs/src/main/java/alluxio/client/file/options/InStreamOptions.java (hunk 6 above)
Comment (maobaolong) [reply core/client/fs/src/main/java/alluxio/client/file/options/InStreamOptions.java:97]: It can be null for ut, some ut mock the `FileSystemContext`

File: core/server/worker/src/test/java/alluxio/worker/block/stream/BlockWorkerDataReaderTest.java (hunk 8 above)
Comment (maobaolong) [reply core/server/worker/src/test/java/alluxio/worker/block/stream/BlockWorkerDataReaderTest.java:156]: Thank you, corrected it.

File: core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java (hunk 2 above)
Comment (jiacheliu3) [reply core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java]: This can be addressed in a separate PR later

Comment (maobaolong) [reply core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java]: #16228

**Comment by maobaolong** [comment]
It seems test2 will failed if we decouple these into to individual test file.

```
Error: 6.599 [ERROR] Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 132.405 s <<< FAILURE! - in alluxio.client.fs.LocalFirstPolicyIntegrationTest
Error: 6.627 [ERROR] alluxio.client.fs.LocalFirstPolicyIntegrationTest.test2  Time elapsed: 61.393 s  <<< ERROR!
java.lang.RuntimeException: Timed out waiting for process Alluxio master @e0b60b05f1fe:19998 to start
	at alluxio.master.TestUtils.waitForReady(TestUtils.java:34)
	at alluxio.client.fs.LocalFirstPolicyIntegrationTest.test2(LocalFirstPolicyIntegrationTest.java:126)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

Error: 6.651 [ERROR] alluxio.client.fs.LocalFirstPolicyIntegrationTest.test2  Time elapsed: 61.927 s  <<< ERROR!
java.lang.RuntimeException: Timed out waiting for process Alluxio master @e0b60b05f1fe:19998 to start
	at alluxio.master.TestUtils.waitForReady(TestUtils.java:34)
	at alluxio.client.fs.LocalFirstPolicyIntegrationTest.test2(LocalFirstPolicyIntegrationTest.java:126)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by maobaolong** [comment]
@jiacheliu3 This test failed constant, it will be passed if I combine this test2 with test in LocalFirstPolicyIntegrationTest

```
Error: 2.994 [ERROR] Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 130.608 s <<< FAILURE! - in alluxio.client.fs.LocalFirstPolicyIntegrationTest
Error: 2.995 [ERROR] alluxio.client.fs.LocalFirstPolicyIntegrationTest.test2  Time elapsed: 61.163 s  <<< ERROR!
java.lang.RuntimeException: Timed out waiting for process Alluxio master @c1f6413de002:19998 to start
	at alluxio.master.TestUtils.waitForReady(TestUtils.java:34)
	at alluxio.client.fs.LocalFirstPolicyIntegrationTest.test2(LocalFirstPolicyIntegrationTest.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

Error: 3.005 [ERROR] alluxio.client.fs.LocalFirstPolicyIntegrationTest.test2  Time elapsed: 61.49 s  <<< ERROR!
java.lang.RuntimeException: Timed out waiting for process Alluxio master @c1f6413de002:19998 to start
	at alluxio.master.TestUtils.waitForReady(TestUtils.java:34)
	at alluxio.client.fs.LocalFirstPolicyIntegrationTest.test2(LocalFirstPolicyIntegrationTest.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Review by jiacheliu3 — APPROVED** [review]
LGTM

**Comment by jiacheliu3** [comment]
alluxio-bot, merge this please

**Comment by maobaolong** [comment]
@dbw9580 Thanks for fix the test for me, @jiacheliu3 Thanks for merge this PR
