### PR TITLE
Fix unencoded paths for the web ui

### LINKED ISSUE #9465: Path components are not uri encoded in the webui
**Alluxio Version:**
2.0.0

**Describe the bug**
Path components are not uri encoded causing pages for files with reserved characters (ie. `=`) to fail to render.

**To Reproduce**
Browse to a file with and `=` in it.

### PR DESCRIPTION
**Pull request by calvinjia**
Fixes #9465 

Invariants -
Paths presented to the user are not encoded.
Paths in URLs/links are encoded, except for specific references to the root path (a constant `/`).

### CODE REVIEW

**Comment by calvinjia** [comment]
Jenkins, test this please.

**Comment by calvinjia** [comment]
@ggezer Have we deflaked this test? `alluxio.client.cli.JournalToolTest.dumpHeapCheckpointFromEmbeddedJournal`

File: core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java [hunk 1]
```diff
@@ -367,8 +368,8 @@ public Response getWebUIBrowse(@DefaultValue("/") @QueryParam("path") String req
           ServerConfiguration.getBoolean(PropertyKey.SECURITY_AUTHORIZATION_PERMISSION_ENABLED))
           .setMasterNodeAddress(mMasterProcess.getRpcAddress().toString()).setInvalidPathError("");
       List<FileInfo> filesInfo;
-      String path = requestPath;
-      if (path == null || path.isEmpty()) {
+      String path = URLDecoder.decode(requestPath, "UTF-8");
+      if (path.isEmpty()) {
         path = AlluxioURI.SEPARATOR;
```
Comment (apc999) [inline core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java]: don't we need to encode this too?

**Comment by ggezer** [comment]
@calvinjia it still flakes, but less frequently. I'll need to have a deeper look into checkpoint rpc in raft journal as it mostly fails during that.

File: core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java (hunk 1 above)
Comment (calvinjia) [reply core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java]: We only need to decode what is sent to us by the client in `requestPath`.

**Comment by calvinjia** [comment]
alluxio-bot, merge this please.

**Comment by calvinjia** [comment]
alluxio-bot, cherry-pick this to branch-2.0 please.
