### PR TITLE
[#8481] Remove deprecated alluxio filesystem commands

### LINKED ISSUE #8481: Remove Deprecated FileSystem commands
**Alluxio Version:** 1.8.1

**Describe the bug**

There are numerous commands that we have deprecated or handle some special alias cases (the aliases however still warn the user's about deprecation). We should remove everything that is referenced as deprecated so that it doesn't exist after the Alluxio 2.0 release.

The commands which should be removed:

- Aliases
  - `umount`
  - `rmr`
  - `lsr`
- Commands
  - FileInfoCommand (`./bin/alluxio fs fileInfo`)
  - LoadMetadataCommand (`./bin/alluxio fs loadMetadata`)

**To Reproduce**
N/A

**Expected behavior**

The deprecated commands should be removed

**Additional context**

### PR DESCRIPTION
**Pull request by ZacBlanco**
- Alias commands removed: lsr, rmr, umount
- FileInfoCommand removed
- LoadMetadataCommand removed

Fixes #8481

### CODE REVIEW

File: shell/src/main/java/alluxio/cli/fs/FileSystemShell.java [hunk 1]
```diff
@@ -36,11 +36,7 @@
 public final class FileSystemShell extends AbstractShell {
   private static final Logger LOG = LoggerFactory.getLogger(FileSystemShell.class);
 
-  private static final Map<String, String[]> CMD_ALIAS = ImmutableMap.<String, String[]>builder()
-      .put("lsr", new String[] {"ls", "-R"})
-      .put("rmr", new String[] {"rm", "-R"})
-      .put("umount", new String[] {"unmount"})
-      .build();
+  private static final Map<String, String[]> CMD_ALIAS = ImmutableMap.<String, String[]>builder().build();
```
Comment (apc999) [inline shell/src/main/java/alluxio/cli/fs/FileSystemShell.java]: we should keep `umount` as an alias of `unmount`

Comment (ZacBlanco) [reply shell/src/main/java/alluxio/cli/fs/FileSystemShell.java]: why?

Comment (ZacBlanco) [reply shell/src/main/java/alluxio/cli/fs/FileSystemShell.java]: command aliases mark warn the user that the use of the alias is deprecated. It should be removed if that is the case. Otherwise we should have another mechanism for handling non-deprecated aliases.

Comment (apc999) [reply shell/src/main/java/alluxio/cli/fs/FileSystemShell.java]: Previously, Alluxio fs supports `unmount` only and Alluxio fuse supports `umount` only, which to me is confusing. So I actually added this alias recently to make it easier for users so they don't need to remember if it is `umount` or `unmount` --- we will support both.

Comment (apc999) [reply shell/src/main/java/alluxio/cli/fs/FileSystemShell.java]: I see. Agree to have a separate mechanism (without showing deprecation warnings). Up to you if you want to solve it in this PR or separate PR

Comment (ZacBlanco) [reply shell/src/main/java/alluxio/cli/fs/FileSystemShell.java]: We should unify this then. Either a user uses `unmount` or `umount` for all Alluxio related operations. Is there a point to having both?

**Comment by ZacBlanco** [comment]
jenkins, test this please

File: shell/src/main/java/alluxio/cli/fs/FileSystemShell.java (hunk 1 above)
Comment (apc999) [reply shell/src/main/java/alluxio/cli/fs/FileSystemShell.java]: In Unix/Linux world  it is `umount` for historical reasons as a abbreviated version of `unmount`. However, Alluxio has been supporting `unmount` but not `umount` for years since very early releases. I don't see any benefits to require users to remember Alluxio supports only `umount` or `unmount`.

Comment (ZacBlanco) [reply shell/src/main/java/alluxio/cli/fs/FileSystemShell.java]: I think I'm just trying to get out of the extra work here 😅 

I'll implement something for non-deprecated aliases in this PR.

**Comment by apc999** [comment]
@ZacBlanco is this draft ready to review ?

**Comment by ZacBlanco** [comment]
No, I still need to add functionality for non-deprecated aliases. I need another 1-2 days

**Comment by ZacBlanco** [comment]
@apc999 Just added in last touches on this. Feel free to review the rest

File: core/common/src/main/java/alluxio/cli/AbstractShell.java [hunk 2]
```diff
@@ -39,18 +40,22 @@
...
 
   /**
    * Creates a new instance of {@link AbstractShell}.
    *
    * @param commandAlias replacements for commands
+   * @param unstableAlias set of unstable aliases which may be removed in the future
    * @param conf Alluxio configuration
    */
-  public AbstractShell(Map<String, String[]> commandAlias, InstancedConfiguration conf) {
+  public AbstractShell(Map<String, String[]> commandAlias,
```
Comment (apc999) [inline core/common/src/main/java/alluxio/cli/AbstractShell.java]: I actually feel this constructor is not ideal --- there are three or four subclasses and most of them just passing two `null`s, meaning this constructor is very specialized only to make `FilesystemShell` work.

Instead of having the static private member  `CMD_ALIAS` and `UNSTABLE_ALIAS`, can we define alias in each Command and add something like `getAliases` into the `Command` interface?  The current way looks less clean to me (passing two alias sets).

If we are running out of time, I am cool with the current approach for preview.

**Comment by ZacBlanco** [comment]
I agree this first solution felt more like a stopgap measure as I was writing it. Another idea I had been thinking of was to instead create some kind of inner class `CommandAlias` 

```
